### PR TITLE
Specify ADD_RT for android platform, which embeds librt in libc

### PR DESCRIPTION
**Pull request by xloem**
I needed this change to build tesseract 3.05.02 using the android ndk.

### CODE REVIEW

**Comment by zdenop** [comment]
3.05 is nut supported and you push it to master branch (5.0)

**Comment by stweil** [comment]
@Robyer, does this change help for Android builds?

**Comment by egorpugin** [comment]
Assuming https://developer.android.com/ndk/guides/stable_apis
Note that on Android, unlike Linux, there are no separate libpthread or librt libraries. That functionality is included directly in libc, which does not need to be explicitly linked against.

**Comment by Robyer** [comment]
@egorpugin It looks like this PR was too old and it's fix is already included in current code, so the merge should be reverted, See: https://github.com/xloem/tesseract/blob/fed6603a77dfb628bd4bcde43484c68f89532e92/configure.ac#L106-L108

**Comment by egorpugin** [comment]
Uh-oh.

**Pull request merged**
