### PR TITLE
new API method for setting producer for TessPDFRenderer

### PR DESCRIPTION
**Pull request by mato7d5**
- enable to set up producer property in Info dict.

### CODE REVIEW

**Comment by jbreiden** [comment]
1. What is the reason for this change?  Shouldn't Tesseract get credit for its PDF output?
2. As written, this creates a new security vulnerability. See issue #636.

**Comment by mato7d5** [comment]
Ok, I understand. Please reject this PR.

**Comment by amitdo** [comment]
>What is the reason for this change? Shouldn't Tesseract get credit for its PDF output?

If someone embeds libtesseract in his his product 'myOwnOCR', he probably prefer that any output will use this name instead of 'Tesseract'...

Maybe it will be more fair if 'libtesseract x.yz' will be kept in the output, especially if the developer doesn't apply any change to it, or apply only minor changes.

**Comment by mato7d5** [comment]
> If someone embeds libtesseract in his his product 'myOwnOCR', he probably prefer that any output will use this name instead of 'Tesseract'...

Exactly, that is my case. I use libtesseract and in"about" of my app is mentioned that's is based on tesseract. I would like to set another producer as "tesseract <version>"

**Comment by jbreiden** [comment]
Aside from any credit issues, there is also a matter of compatibility. We know that 3.0.4 Tesseract PDF does better with Firefox, and 3.0.5 Tesseract PDF does better with ghostscript. Maybe 3.0.6 will finally do better with Arabic / Hebrew. That sort of information gets lost when we override Producer. That said, reasonable people can probably disagree here.

I think the escaping issue is very clear. We don't want to create opportunities for creating corrupt or malicious PDF files, and therefore issue #636 is a hard requirement.

**Comment by jbreiden** [comment]
There is now a fix for issue #636 which demonstrates how to safely set a metadata field.

**Comment by jbarlow83** [comment]
I'm against this as well. It's too important to be able to trace Tesseract-produced PDFs back to the version of Tesseract that produced them. Tesseract should not allow changing the /Producer field.

The /Creator field, which Tesseract does not set, is the appropriate one for this use case.

**Comment by mato7d5** [comment]
OK, I think you can close/deny this PR.

**Pull request closed without merging**
