### PR TITLE
class and struct are incompatible in MSVC2013 compiler.

### PR DESCRIPTION
**Pull request by spSerg**
At least as a template parameter.
```cpp
  GenericVector<UnicharRating>
```

### CODE REVIEW

**Comment by spSerg** [comment]
It's another fix of https://github.com/tesseract-ocr/tesseract/commit/cdc84a5dd79b20beae9dd0a2400211630f361916

**Comment by zdenop** [comment]
Can you please provide error message from MSVC2013?

**Comment by spSerg** [comment]
Something like this:
<code>
OCRLib.Win32.lib(adaptmatch.obj) : error LNK2001: unresolved external symbol "public: virtual int __thiscall tesseract::ShapeClassifier::UnicharClassifySample(class tesseract::TrainingSample const &,struct Pix ,int,int,class GenericVector&lt;class tesseract::UnicharRating&gt; )" (?UnicharClassifySample@ShapeClassifier@tesseract@@UAEHABVTrainingSample@2@PAUPix@@HHPAV?$GenericVector@VUnicharRating@tesseract@@@@@Z)
</code>
or this:
<code>
OCRLib.Win32.lib(tessclassifier.obj) : error LNK2019: unresolved external symbol "public: int thiscall tesseract::Classify::CharNormTrainingSample(bool,int,class tesseract::TrainingSample const &,class GenericVector&lt;struct tesseract::UnicharRating&gt; *)" (?CharNormTrainingSample@Classify@tesseract@@QAEH_NHABVTrainingSample@2@PAV?$GenericVector@UUnicharRating@tesseract@@@@@Z) referenced in function "public: virtual int thiscall tesseract::TessClassifier::UnicharClassifySample(class tesseract::TrainingSample const &,struct Pix ,int,int,class GenericVector&lt;struct tesseract::UnicharRating&gt; )" (?UnicharClassifySample@TessClassifier@tesseract@@UAEHABVTrainingSample@2@PAUPix@@HHPAV?$GenericVector@UUnicharRating@tesseract@@@@@Z)
</code>

**Comment by spSerg** [comment]
<code>UnicharRating</code> is a structure. But such forward declaration as a class will confuse MS compiler in parameter of template.

**Pull request merged**
