### PR TITLE
Move googletest to unittest/third_party/googletest

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
All sw builds fail. @egorpugin, how can that be fixed?

**Comment by egorpugin** [comment]
Try to add here
https://github.com/tesseract-ocr/tesseract/blob/main/sw.cpp#L325
```
        tw -= "unittest/third_party/googletest/.*"_rr;
```

**Comment by egorpugin** [comment]
If it fails just merge, I'll fix it.

**Review by egorpugin — APPROVED** [review]

**Comment by amitdo** [comment]
Thanks!

**Pull request merged**
