### PR TITLE
Add example in README.md

### PR DESCRIPTION
**Pull request by ajschaeper**
Added an example in the README for newbies like me to have a place to get started.
Also added a link to the wiki where there are more helpful examples.

### CODE REVIEW

**Comment by zdenop** [comment]
we have there in past 2 examples images and they were removed from source...

**Comment by zdenop** [comment]
black&white text image: 126 KB seriously? no image size optimization?

**Comment by stweil** [comment]
Please don't add new images (binaries!) to the tesseract repository, as they increase the size of the Git data too much.

**Comment by ajschaeper** [comment]
Good points. 
* Removed everything, including the files
* Just left a link to the examples in the wiki

**Comment by stweil** [comment]
Thank you for this update. It's merged now.

**Pull request merged**
