### PR TITLE
simd: Check whether the OS supports FMA, AVX, ...

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@egorpugin, I could not test this with MSVC, and Appveyor CI still fails.

**Comment by egorpugin** [comment]
Isn't it will be better to use https://github.com/google/cpu_features
instead of our manual hand-crafted implementation?

**Comment by stweil** [comment]
A short look on that code shows that it might be used, but it looks a little bit oversized because it implements lots of things which are not needed for Tesseract. The current Tesseract code uses the Intel intrinsics which I think is better than the assembler code used by _cpu_features_.

**Comment by stweil** [comment]
@egorpugin, what is causing the build failure with Appveyer CI?

**Comment by egorpugin** [comment]
I have to update sw.
(Such errors are because of different ABI between sw.exe and compiled .dll module - build script.)

**Comment by egorpugin** [comment]
Fixed.

**Comment by AllofLife** [comment]
hi stweil thank you for your pay,if i want to deploy the tesseract to a arm linux like nvidia-jetson nano ubuntu18.04 ,what should i need to do to reduse the running time? 
If you can reply, I will be very grateful.

**Comment by stweil** [comment]
There are currently no special settings for Jetson Nano to make it faster.

**Comment by AllofLife** [comment]
We now understand that the reason why the deployment of jetson becomes slower.
Specifically in the same recognition rate, x86 is about eight times faster than arm.
 may be that the arm architecture does not have matrix operation acceleration instructions such as AVX.
 or it may be because we recognize Chinese and Chinese is too complex to bring slow speed.
 Can you give suggestions for optimization?  thank!

**Pull request merged**
