### PR TITLE
Make 'traineddata' in README.md clearer to users

### PR DESCRIPTION
**Pull request by edwinnyawoli**

### CODE REVIEW

**Comment by stweil** [comment]
@edwinnyawoli, do you have a suggestion how to describe that clearer to avoid more misunderstandings? Otherwise I suggest to close this pull request.

**Comment by edwinnyawoli** [comment]
Oh Ok, my bad. Maybe making it bold, or a hyperlink to its doc might make it clearer.

**Comment by stweil** [comment]
Thank you!

**Comment by edwinnyawoli** [comment]
Thanks as well 👍

**Pull request merged**
