### PR TITLE
Ensure PACKAGE_VERSION is defined, even without config.h

### PR DESCRIPTION
**Pull request by robinwatts**
If we aren't using config.h, then PACKAGE_VERSION is not
defined. Spot this, and include tess_version.h to get
TESSERACT_VERSION_STR instead.

### CODE REVIEW

**Comment by stweil** [comment]
Tesseract uses `config_auto.h`, not `config.h`. Why do you want to compile without `config_auto.h`?

**Comment by robinwatts** [comment]
"Tesseract uses config_auto.h, not config.h."

Yes, indeed, that's a typo. If you set the HAVE_CONFIG_H define, then tesseract does indeed look for a config_auto.h file.

Given that tesseract requires you to set HAVE_CONFIG_H to use config_auto.h, it seems reasonable that it should compile without HAVE_CONFIG_H being set (otherwise, why check that define at all?)

"Why do you want to compile without config_auto.h?"

Because for various reasons I'm not using the autoconf based build.

Now, it's entirely reasonable that this fix isn't right. Possibly we should ALWAYS be including tess_version.h and always using TESSERACT_VERSION_STR. That'd seem neater to me. I'm happy to prepare a patch like that if that's what it takes to get a fix committed.

**Comment by stweil** [comment]
I suggest to drop this pull request and add a `config_auto.h` to your code.

**Comment by robinwatts** [comment]
Actually, there is a nicer way to do this. Let me have one last go at getting your approval :)

**Comment by robinwatts** [comment]
There you go, this version seems much nicer.

**Pull request merged**
