### PR TITLE
Enable pango_font_info_test and fix crash for MacOS with M1

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
`pango_font_info_test` passes on Linux. On MacOS with M1 it at least no longer crashes and passes most parts of that test.

**Comment by stweil** [comment]
See also issue #2599.

**Comment by zdenop** [comment]
build is failing for [ubuntu](https://travis-ci.org/github/tesseract-ocr/tesseract/jobs/750986447):
```
[ 92%] Building CXX object src/training/CMakeFiles/text2image.dir/pango_font_info.cpp.o
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp: In function ‘PangoGlyph tesseract::get_glyph(PangoFont*, gunichar)’:
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:76:3: error: ‘hb_font_t’ was not declared in this scope
   hb_font_t* hb_font = pango_font_get_hb_font(font);
   ^
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:76:14: error: ‘hb_font’ was not declared in this scope
   hb_font_t* hb_font = pango_font_get_hb_font(font);
              ^
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:76:51: error: ‘pango_font_get_hb_font’ was not declared in this scope
   hb_font_t* hb_font = pango_font_get_hb_font(font);
                                                   ^
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:77:3: error: ‘hb_codepoint_t’ was not declared in this scope
   hb_codepoint_t glyph;
   ^
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:78:43: error: ‘glyph’ was not declared in this scope
   hb_font_get_nominal_glyph(hb_font, wc, &glyph);
                                           ^
/home/travis/build/tesseract-ocr/tesseract/src/training/pango_font_info.cpp:78:48:m error: ‘hb_font_get_nominal_glyph’ was not declared in this scope
   hb_font_get_nominal_glyph(hb_font, wc, &glyph);
```

**Comment by stweil** [comment]
The new code requires Pango 1.44. I now added the old code as a fallback for older Pango versions, so please retry.

**Comment by amitdo** [comment]
> `pango_font_info_test` passes on Linux. On MacOS with M1 it at least no longer crashes and passes most parts of that test.

Which parts do not pass? Mayby you can add TODO above each one?

**Comment by stweil** [comment]
It looks like on MacOS the test sees all MacOS fonts instead of the limited set which is installed in `test/testing`. I don't know the reason for that, but it explains the failure of several test steps.

**Comment by amitdo** [comment]
The was design to work with the FontConfig backend, even on macOS, and it appears that your pango version uses the CoreText backend.

**Comment by stweil** [comment]
It's from Homebrew, and that should work with FontConfig.
`text2image --list_available_fonts --fonts_dir tesseract/test/testing` works.

**Comment by stweil** [comment]
> [...] it appears that your pango version uses the CoreText backend.

You are right, thank you. The test passes with `export PANGOCAIRO_BACKEND=fc`.

**Comment by amitdo** [comment]
It workes with text2image thanks to this code:

https://github.com/tesseract-ocr/tesseract/blob/45413e6c423207ee631df7c33dbcdb59eaf3cf54/src/training/text2image.cpp#L720-L726

**Comment by zdenop** [comment]
thanks

**Pull request merged**
