### PR TITLE
Fix compiler warnings [-Wmissing-variable-declarations]

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by zdenop** [comment]
there is error reported by travis:
```
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:23:23: error: redeclaration ‘tesseract::kLRM’ differs in ‘constexpr’
 constexpr const char *kLRM = "\u200E";  // Left-to-Right Mark
                       ^
In file included from /home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:19:0:
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.h:24:26: error: from previous declaration ‘tesseract::kLRM’
 extern const char* const kLRM;  ///< Left-to-Right Mark
                          ^
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:24:23: error: redeclaration ‘tesseract::kRLM’ differs in ‘constexpr’
 constexpr const char *kRLM = "\u200F";  // Right-to-Left Mark
                       ^
In file included from /home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:19:0:
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.h:25:26: error: from previous declaration ‘tesseract::kRLM’
 extern const char* const kRLM;  ///< Right-to-Left Mark
                          ^
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:25:23: error: redeclaration ‘tesseract::kRLE’ differs in ‘constexpr’
 constexpr const char *kRLE = "\u202A";  // Right-to-Left Embedding
                       ^
In file included from /home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:19:0:
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.h:26:26: error: from previous declaration ‘tesseract::kRLE’
 extern const char* const kRLE;  ///< Right-to-Left Embedding
                          ^
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:26:23: error: redeclaration ‘tesseract::kPDF’ differs in ‘constexpr’
 constexpr const char *kPDF = "\u202C";  // Pop Directional Formatting
                       ^
In file included from /home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.cpp:19:0:
/home/travis/build/tesseract-ocr/tesseract/src/ccutil/unicodes.h:27:26: error: from previous declaration ‘tesseract::kPDF’
 extern const char* const kPDF;  ///< Pop Directional Formatting
```

**Comment by stweil** [comment]
That's obviously a problem of the old g++ 4.8 version.

**Comment by stweil** [comment]
> error reported by travis

I modified the new code, and Travis / gcc 4.8 now works, too.
Appveyor still fails, but that looks unrelated.

**Comment by zdenop** [comment]
thanks

**Pull request merged**
