### PR TITLE
RFC – doc: Remove generated files and add rules to build manpages

### PR DESCRIPTION
**Pull request by stweil**
Those files can be built by doc/generate_manpages.sh.

The manpages are needed for the installation,
so add Makefile rules for them.

Git must ignore the generated manpages.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This is a request for comments. The patch removes documentation files which can be easily created if `asciidoc` is available in the build environment. Man pages are now not built and installed by default. They are build and installed in maintainer mode (`./configure --enable-maintainer-mode`).

**Comment by amitdo** [comment]
I just tried to install the asciidoc package on Debian with Synaptic.
Synaptic lists additional **59** required packages.

**Comment by stweil** [comment]
Are you sure that those packages are _required_? On my Debian Stretch, I see 4 required packages (1.4 MB disk space): `asciidoc`, `asciidoc-base`, `asciidoc-common`, `libxml2-utils`.

**Comment by Shreeshrii** [comment]
It may depend on what is already installed on the system. I get the following list:

```
 sudo apt-get install asciidoc
sudo: unable to resolve host ALL-IN-1-TOUCH
[sudo] password for shree:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  dblatex docbook-dsssl docbook-utils fonts-lmodern fonts-texgyre jadetex
  latex-beamer latex-xcolor libkpathsea6 libosp5 libostyle1c2 libptexenc1
  libreadline5 libruby1.9.1 libsgmls-perl libsp1c2 lmodern luatex openjade pgf
  preview-latex-style prosper ps2eps ruby ruby1.9.1 sgmlspl sp tcl tcl8.6
  tex-common tex-gyre texlive texlive-base texlive-bibtex-extra
  texlive-binaries texlive-extra-utils texlive-font-utils
  texlive-fonts-recommended texlive-fonts-recommended-doc
  texlive-generic-recommended texlive-latex-base texlive-latex-base-doc
  texlive-latex-extra texlive-latex-extra-doc texlive-latex-recommended
  texlive-latex-recommended-doc texlive-luatex texlive-math-extra
  texlive-pictures texlive-pictures-doc texlive-pstricks texlive-pstricks-doc
  tipa tk tk8.6 xmlto xsltproc
Suggested packages:
  source-highlight vim-addon-manager docbook latex-cjk-all opensp
  texlive-lang-cyrillic texlive-xetex transfig docbook-dsssl-doc sgmls-doc
  doc-base ri ruby-dev ruby1.9.1-examples ri1.9.1 graphviz ruby1.9.1-dev
  tcl-tclreadline perl-tk chktex fragmaster xindy latexdiff lacheck latexmk
  dvidvi purifyeps dvipng t1utils psutils libfile-which-perl python-pygments
  dot2tex libtcltk-ruby xmltex
Recommended packages:
  wish
The following NEW packages will be installed:
  asciidoc dblatex docbook-dsssl docbook-utils fonts-lmodern fonts-texgyre
  jadetex latex-beamer latex-xcolor libkpathsea6 libosp5 libostyle1c2
  libptexenc1 libreadline5 libruby1.9.1 libsgmls-perl libsp1c2 lmodern luatex
  openjade pgf preview-latex-style prosper ps2eps ruby ruby1.9.1 sgmlspl sp
  tcl tcl8.6 tex-common tex-gyre texlive texlive-base texlive-bibtex-extra
  texlive-binaries texlive-extra-utils texlive-font-utils
  texlive-fonts-recommended texlive-fonts-recommended-doc
  texlive-generic-recommended texlive-latex-base texlive-latex-base-doc
  texlive-latex-extra texlive-latex-extra-doc texlive-latex-recommended
  texlive-latex-recommended-doc texlive-luatex texlive-math-extra
  texlive-pictures texlive-pictures-doc texlive-pstricks texlive-pstricks-doc
  tipa tk tk8.6 xmlto xsltproc
0 upgraded, 58 newly installed, 0 to remove and 171 not upgraded.
Need to get 727 MB of archives.
After this operation, 1,145 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by stweil** [comment]
Try `apt-get install --no-install-recommends asciidoc`. This will reduce the list a lot, because all TeX related packages are only recommended (needed for PDF generation, but not for simple man pages).

**Comment by Shreeshrii** [comment]
Thanks. That does the trick.

```
sudo apt-get install --no-install-recommends asciidoc
sudo: unable to resolve host ALL-IN-1-TOUCH
[sudo] password for shree:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  source-highlight vim-addon-manager
Recommended packages:
  dblatex docbook-utils xmlto
The following NEW packages will be installed:
  asciidoc
0 upgraded, 1 newly installed, 0 to remove and 171 not upgraded.
Need to get 688 kB of archives.
After this operation, 2,370 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main asciidoc all 8.6.9-2ubuntu1 [688 kB]
Fetched 688 kB in 2s (239 kB/s)
Selecting previously unselected package asciidoc.
(Reading database ... 103366 files and directories currently installed.)
Preparing to unpack .../asciidoc_8.6.9-2ubuntu1_all.deb ...
Unpacking asciidoc (8.6.9-2ubuntu1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up asciidoc (8.6.9-2ubuntu1) ...

```

**Comment by amitdo** [comment]
```
amit@debian:~$ apt-cache depends asciidoc
asciidoc
  Depends: python
  Depends: <python:any>
    python
  Suggests: source-highlight
  Suggests: vim-addon-manager
  Recommends: dblatex
  Recommends: docbook-utils
  Recommends: libxml2-utils
  Recommends: xmlto
```

```
amit@debian:~$ apt-get install --dry-run --no-install-recommends asciidoc
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  source-highlight vim-addon-manager
Recommended packages:
  dblatex docbook-utils libxml2-utils xmlto
The following NEW packages will be installed:
  asciidoc
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst asciidoc (8.6.9-3 Debian:8.7/stable [all])
Conf asciidoc (8.6.9-3 Debian:8.7/stable [all])
```

**Comment by amitdo** [comment]
https://www.macports.org/ports.php?by=name&substr=asciidoc

**Comment by stweil** [comment]
By the way, builds which use `cmake` don't install any man pages.

**Comment by amitdo** [comment]
Cmake is used by people that use MSVC and the by the CI.

**Comment by zdenop** [comment]
Any objection to merge this PR?

**Comment by amitdo** [comment]
If this PR is accepted, we will need to add this to the `Compiling` wiki page:
`apt-get install --no-install-recommends asciidoc`, but we only have instructions for Debian-based distros. If other package managers in non-Debian-based distros have a similar behavior like `apt-get install asciidoc` (install also recommended packages) users will get a lot of unneccary packages.

@stweil, what do think about this issue?

**Comment by stweil** [comment]
Yes, we have to add documentation for package maintainers who want to install the man pages with the Tesseract package.

I expect that a person who wants to build a distro package won't have problems with installing too many packages with `asciidoc`. My main machine, for example, already had TeX installed, so the installation of `asciidoc` did not add many more packages.

Normal users who want to build Tesseract would not automatically build man pages, so they don't need `asciidoc`. The main question is whether that is acceptable.

Instead of building man pages in maintainer mode only, it would also be possible to build them only if `asciidoc` was found. Would that be better?

**Comment by amitdo** [comment]
OK. No objection to this PR.

BTW, Git does the same thing:
https://github.com/git/git/tree/master/Documentation

**Comment by amitdo** [comment]
https://github.com/git/git/blob/v2.13.0-rc1/INSTALL#L160
Stefan, I suggest to do something similar in Tesseract.
(Of course, don't copy even a single line from that GPL codebase)

**Comment by Shreeshrii** [comment]
Making all in doc
make[2]: Entering directory `/mnt/c/Users/User/shree/tesseract/doc'
make[2]: *** No rule to make target `cntraining.1', needed by `all-am'.  Stop.
make[2]: Leaving directory `/mnt/c/Users/User/shree/tesseract/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/c/Users/User/shree/tesseract'
make: *** [all] Error 2

**Comment by Shreeshrii** [comment]
Making install in doc
make[1]: Entering directory `/mnt/c/Users/User/shree/tesseract/doc'
make[1]: *** No rule to make target `cntraining.1', needed by `all-am'.  Stop.
make[1]: Leaving directory `/mnt/c/Users/User/shree/tesseract/doc'
make: *** [install-recursive] Error 1

**Comment by Shreeshrii** [comment]
The above errors came while building using the regular automake method with plain ./configure

**Comment by stweil** [comment]
Thank you for the report. This is fixed in PR #862. Don't forget to run `./autogen.sh` after that patch.

**Comment by Shreeshrii** [comment]
Thanks! I usually follow the following for rebuilding tesseract.

```
git pull origin

./autogen.sh
./configure 
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
sudo make install
sudo ldconfig
make training
sudo make training-install
```

**Pull request merged**
