### PR TITLE
Update TESSERACT_VERSION_STR

### PR DESCRIPTION
**Pull request by amitdo**

### CODE REVIEW

**Comment by zdenop** [comment]
thanks

**Comment by stweil** [comment]
@zdenop, did you intend to merge this PR?

**Comment by zdenop** [comment]
Yes. It should reflect current tag/prerelease. Do you see any problem with it?

**Comment by Shreeshrii** [comment]
There are other related changes in
https://github.com/tesseract-ocr/tesseract/pull/593

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
@zdenop, no, I don't see a problem – the PR is fine. I just wondered why you closed it without merging it. Maybe you have to re-open it before you can start the merge.

**Comment by amitdo** [comment]
@zdenop, you closed it without merging. Please reopen and merge.

**Comment by zdenop** [comment]
I see ;-) Thanks.

**Comment by stweil** [comment]
> There are other related changes

There are far too many related locations which need to be changed for every new version. I‌ just try some code which either gets the version from git (if it is available) or from a single file `VERSION` in the project root.

**Comment by Shreeshrii** [comment]
That would be great. Thanks.

**Pull request merged**
