### PR TITLE
Add an option to compile tesseract without the code of the legacy OCR engine

### PR DESCRIPTION
**Pull request by amitdo**

### CODE REVIEW

**Comment by amitdo** [comment]
To test this, use the option `--disable-legacy` with `./configure`.

**Comment by amitdo** [comment]
When using 
`./configure --disable-legacy --disable-static`

The linker complains:

```
./.libs/libtesseract.so: undefined reference to ...

tesseract::TessBaseAPI::MakeTessOCRRow()
tesseract::TessBaseAPI::RunAdaptiveClassifier()
tesseract::TessBaseAPI::NormalizeTBLOB./.libs/litesseract::TessBaseAPI::AdaptToWordStr()
tesseract::TessBaseAPI::MakeTBLOB()
tesseract::TessBaseAPI::FindLinesCreateBlockList()
tesseract::TessBaseAPI::RecognizeForChopTest()
tesseract::TessBaseAPI::DeleteBlockList()
tesseract::TessBaseAPI::ClearAdaptiveClassifier()
tesseract::TessBaseAPI::GetFeaturesForBlob()
tesseract::TessBaseAPI::InitLangMod()
tesseract::TessBaseAPI::DetectOrientationScript()
tesseract::TessBaseAPI::FindRowForBox()

collect2: error: ld returned 1 exit status
```

**Comment by amitdo** [comment]
@stweil , can you help solving this issue?

**Comment by stweil** [comment]
Yes. I'm preparing a pull request.

**Comment by amitdo** [comment]
the capi.cpp needs some more #ifndef.

**Comment by stweil** [comment]
Please, no.

**Comment by stweil** [comment]
That's only part of the fix, see pull request #1744.

**Comment by amitdo** [comment]
Yes, the second issue was that the `capi.cpp/h` needed to include `config_auto.h`

**Comment by stweil** [comment]
I did not like the idea to add that include to every file (via `baseapi.h`). That's why I had chosen a different solution.

**Pull request merged**
