### PR TITLE
dailycmake run for Linux matrix combos

### PR DESCRIPTION
**Pull request by Shreeshrii**
sw already runs with cmake for  windows and macos .

### CODE REVIEW

**Comment by egorpugin** [comment]
> and macos .

Where?

**Comment by Shreeshrii** [comment]
> > and macos .
> 
> Where?

https://github.com/tesseract-ocr/tesseract/blob/8b7fdb75c8c45cba7bfc5fa0e7344e1b9a1fb1c7/.github/workflows/sw.yml#L16

**Comment by egorpugin** [comment]
It is sw, not cmake.

**Comment by Shreeshrii** [comment]
> It is sw, not cmake.

But in the earlier cmake version also, wasn't I was using sw ????

https://github.com/tesseract-ocr/tesseract/pull/3253/files#diff-4f23d66762e498f2f50859d2a535598dc863bdffe369f7194641cf5a60ee7ea6

```
      - name: Checkout
        uses: actions/checkout@v2
      - uses: egorpugin/sw-action@master
  ```

With that, the windows build was failing with 

```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find SW (missing: SW_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:577 (_FPHSA_FAILURE_MESSAGE)
-- Configuring incomplete, errors occurred!
See also "D:/a/tesseract/tesseract/build/CMakeFiles/CMakeOutput.log".
  C:/Users/runneradmin/.sw/storage/etc/sw/static/SWConfig.cmake:22 (find_package_handle_standard_args)
See also "D:/a/tesseract/tesseract/build/CMakeFiles/CMakeError.log".
  CMakeLists.txt:304 (find_package)
```

and macOS build was failing with:

```
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'lept>=1.74'
--   No package 'lept' found
CMake Error at /usr/local/Cellar/cmake/3.19.1/share/cmake/Modules/FindPkgConfig.cmake:553 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.1/share/cmake/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  CMakeLists.txt:324 (pkg_check_modules)

```

I will check the compiling page again to see what I am missing.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/2424
https://stackoverflow.com/questions/38128260/cmake-and-tesseract-how-to-link-using-cmake

These have hints for fixing error for macos/ I will make that change and resubmit. CLosing this.

**Pull request closed without merging**
