### PR TITLE
Add missing linker flags for Leptonica

### PR DESCRIPTION
**Pull request by stweil**
They were removed in commit d70f3c36635c251ac3286063c6c29d10b815a565.
The old code implicitly added `-llept` by using the `AC_CHECK_LIB` macro.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by Wikinaut** [comment]
(can you tell me, how I can directly cherry-pick or merge your pr into my local repo?)

**Comment by Wikinaut** [comment]
(I am just trying something from https://mispdev.blogspot.de/2013/02/github-cherry-picking-commits-from-pull.html )

**Comment by stweil** [comment]
(untested)

    git checkout -b stweil master
    git pull https://github.com/stweil/tesseract.git
    git checkout master
    git cherry-pick 7c684be7245a24bd4c97878424fb14bc394fef4e

**Comment by Wikinaut** [comment]
(I just wanted to confirm, that it solves the problem! ty all)

**Comment by dylanjw** [comment]
Don't want to be a bother, but could the 3.05 stable release be bumped with a version that includes this change?  https://github.com/tesseract-ocr/tesseract/releases/tag/3.05.01 is missing this commit.

**Comment by Shreeshrii** [comment]
@zdenop You should release 3.05.02 as a bug fix for 3.05 branch.

**Pull request merged**
