### PR TITLE
lstm: Update AVX / SSE support

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This PR fixes issue #517. The detection code was tested with Mingw-w64 (which supports both the gcc and the MSVC specific code), but I cannot test builds with MSVC.

**Comment by stweil** [comment]
@zdenop, https://ci.appveyor.com/project/zdenop/tesseract/build/3.05.560 still includes 3.05 in the URL.

**Comment by zdenop** [comment]
@stweil I change build version format to "{branch}.{build}" (from "3.05..{build}". Lets see if it helps.

**Comment by stweil** [comment]
Looks good, thank you.

**Comment by amitdo** [comment]
Nice!
What about moving the SIMD detection code to a separate file?
(maybe to `arch/simddetection.h`)

**Comment by stweil** [comment]
Good idea. Done in PR #618.

**Pull request merged**
