### PR TITLE
Remove class STRING

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
There remains a single usage of `STRING`. Replacing that by `std::string` results in a memory leak which still has to be examined.

**Comment by stweil** [comment]
> There remains a single usage of `STRING`

This is solved now. `STRING` is now completely removed.

**Comment by egorpugin** [comment]
Great! Thank you.

**Comment by amitdo** [comment]
Goodbye STRING.
:-)

Thanks!

**Pull request merged**
