### PR TITLE
Replace pdf.ttf with sharp2.ttf, keep name the same

### PR DESCRIPTION
**Pull request by jbarlow83**
As discussed at length in issue #182, the existing pdf.ttf causes difficulties
for certain PDF viewers, in part because the old file had zero advance width.

With testing, sharp2.ttf seems to be the best available compromise, although
it's not perfect and causes some visual difficulties in Evince.  It does
seem to fix Kindle and OS X Preview.

### CODE REVIEW

**Comment by amitdo** [comment]
Did someone test that there is no regression in pdf output with Adobe Acrobat
and Chromium?

**Comment by jbarlow83** [comment]
Test PDF is here:
https://github.com/tesseract-ocr/tesseract/files/119875/simple-1.pdf

**Comment by jbarlow83** [comment]
I have checked: Acrobat XI, Google Chrome PDF Viewer, OS X Preview, Safari PDF viewer; all on El Capitan.

**Comment by jbarlow83** [comment]
See #182 for other tests people did with sharp2.ttf

**Comment by jbreiden** [comment]
Chromium and Adobe Reader on Linux are fine. I have reports that Ghostscipt and friends are okay. I should probably double check Android right now.

**Comment by jbreiden** [comment]
Latest stock Android (Marshmallow) is fine.

**Comment by amitdo** [comment]
Okay, but I think you should also test this with an image that has more than two words...

**Comment by rossj** [comment]
Using `sample-1.pdf` from above in the latest pdf.js results in the 2nd word highlighting properly, while the 1st word's highlight is offset. I don't think this is a regression (and it might actually be an improvement) as there were highlighting-offset issues using the previous pdf.ttf with pdf.js. Related to https://github.com/mozilla/pdf.js/issues/6863. 

screen shot 2016-02-12 at 8 10 39 am

**Comment by jbreiden** [comment]
I've been tracking the Firfox offset problem in https://github.com/mozilla/pdf.js/issues/6509

**Pull request merged**
