### PR TITLE
Don't drop words with low certainty

### LINKED ISSUE #681: LSTM: Words dropped during recognition
Please see attached OCR evaluation reports. The words highlighted in green in the ground truth are being dropped during recognition.

[kan-words-dropped.zip](https://github.com/tesseract-ocr/tesseract/files/736761/kan-words-dropped.zip)

### PR DESCRIPTION
**Pull request by amitdo**
Fix #681.

### CODE REVIEW

**Comment by amitdo** [comment]
@theraysmith, @jbreiden,
Please review and approve this PR. I want this in to be in Ubuntu 18.04.

**Comment by zc813** [comment]
Hi amitdo, I encountered the same problem. Is there anything I can do to help with this pull request?

**Comment by amitdo** [comment]
I think it's a good idea to test it on several languages and variety of pages.

Apart from this, someone with the right permissions will need to merge it...

**Comment by zc813** [comment]
@amitdo Seems not working on Tibetan. Results remain the same as before.
p.s. different sentences are missing if a different psm (3 or 6) is used.

Any idea? Thanks a lot!

**Comment by zc813** [comment]
@amitdo Some of the results are better on Tibetan. Previously missing words are recognized after this commit.
However, there are still several entire lines of text missing. Different lines are skipped if a different psm (3, 6, or 11) is used.

Any idea? Thanks a lot!

**Pull request merged**
