### PR TITLE
Modify api example to use text fixtures and parameters

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by Shreeshrii** [comment]
@stweil @amitdo Please review.

**Comment by Shreeshrii** [comment]
[apiexample_test.log.txt](https://github.com/tesseract-ocr/tesseract/files/1670057/apiexample_test.log.txt)

**Comment by Shreeshrii** [comment]
@stweil 

I had modified this test to use specific directories for tessdata as I wanted to test for traineddata files from tessdata, tessdata_best and tessdata_fast.

`    ASSERT_FALSE(api->Init(tessdatadir, lang)) << "Could not initialize tesseract.";`

and

`  OCRTester("../testing/phototest.tif" ,"../testing/phototest.txt" , "../../tessdata_fast/", GetParam());`

While testing today with the latest code, the test fails (I think it is related to search for traineeddata without tessdata in path).

```
Error opening data file ../../tessdata_fast/tessdata/Latin.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'Latin'
Tesseract couldn't load any languages!
apiexample_test.cc:50: Failure
Value of: api->Init(tessdatadir, lang)
```

Shouldn't  the directory given as part of api init be used for search without the addition of tessdata? That's how --tessdata-dir from command line works.

**Comment by Shreeshrii** [comment]
Re-opening - need to test tessdatadir implementation.

**Comment by Shreeshrii** [comment]
If I specify NULL for tessdatadir, the error is

```
Error opening data file /usr/local/share/tessdata/Latin.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'Latin'
Tesseract couldn't load any languages!
apiexample_test.cc:50: Failure
```

**Comment by stweil** [comment]
> Shouldn't the directory given as part of api init be used for search without the addition of tessdata?

Yes, of course. It looks like some more code changes are needed. I'll have a look later.

**Comment by stweil** [comment]
See PR #1328.

**Comment by Shreeshrii** [comment]
@stweil Thanks. Seems to be working OK with the new changes.

**Pull request closed without merging**
