### PR TITLE
Add debug configuration for LSTM

### PR DESCRIPTION
**Pull request by stweil**
It was provided by Jeff Breidenbach <jbreiden@google.com>.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by zdenop** [comment]
I am out but can your check if file is included in Makefile.am? I do not
sebe it there.

Dňa so 27. 10. 2018, 8:05 Stefan Weil <notifications@github.com> napísal(a):

**Comment by stweil** [comment]
Do you think that file should be added to the distribution? Or is it only useful for developers who typically use git, so they can use it from the source tree?

**Comment by zdenop** [comment]
IMO if it is in official report, it should be also installed and added to distribution. Otherwise it should be enough to document it on wiki.

**Comment by jbreiden** [comment]
It's for developers, but I don't see a problem distributing.

**Pull request merged**
