### PR TITLE
add cli `-c` parameter(s) to init vectors

### PR DESCRIPTION
**Pull request by zdenop**
see #4354

### CODE REVIEW

**Comment by amitdo** [comment]
Thanks!

**Comment by stweil** [comment]
What happens now if I want to override parameters which are normally set by the model file?

old: model file parameters could be overridden by command line parameters
new: command line parameters are evaluated before the model file parameters are set?

**Comment by stweil** [comment]
Old error message for wrong usage:
```
Missing = in configvar assignment
```

New error message:
```
libc++abi: terminating due to uncaught exception of type std::invalid_argument: Missing '=' in configvar assignment
zsh: abort      tesseract x - -c x
```

Throwing an error changes the error message which is presented to users. Why not simply print the old error message?

**Comment by amitdo** [comment]
Responding for your first comment:

It not clear if you wonder if there is an issue here or **know** there is an issue.

Regarding your second comment, yes, we should change this to print a simple error message.

**Comment by amitdo** [comment]
stweil,

See the code in:
https://github.com/tesseract-ocr/tesseract/blob/2e5a114bd2aab932b53e103d1391e7f27d2d8cff/src/ccmain/tessedit.cpp#L288

**Comment by zdenop** [comment]
@stweil : Could it be like this?

```diff
diff --git a/src/tesseract.cpp b/src/tesseract.cpp
index 08a65e14..6025af5f 100644
--- a/src/tesseract.cpp
+++ b/src/tesseract.cpp
@@ -462,7 +462,8 @@ static bool ParseArgs(int argc, char **argv, const char **lang, const char **ima
       const std::string argument(argv[i + 1]);
       const auto equal_pos = argument.find('=');
       if (equal_pos == std::string::npos) {
-          throw std::invalid_argument("Missing '=' in configvar assignment");
+        fprintf(stderr, "Missing = in configvar assignment\n");
+        return false;
       }
       // Extract key and value
       const std::string key = argument.substr(0, equal_pos);
```

**Comment by zdenop** [comment]
@stweil : Are you fine with proposal above or does 0a9df94fffffb2182836e69b7a33d4d455a34fc7 solve the problem?

**Pull request merged**
