### PR TITLE
Cmake install

### PR DESCRIPTION
**Pull request by zdenop**
This is aim to sync with autotools make install to satisfied requests like #3674
Question is if to install also [pdf.tff](https://github.com/tesseract-ocr/tesseract/blob/main/tessdata/pdf.ttf) - autotools install it, but it is not needed as there is [pdf_ttf.h](https://github.com/tesseract-ocr/tesseract/blob/main/src/api/pdf_ttf.h).

Relevant code is here: 
https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/api/pdfrenderer.cpp#L619-L633

### CODE REVIEW

**Comment by egorpugin** [comment]
There is some `x` file in PR.

**Comment by amitdo** [comment]
>Question is if to install also pdf.tff - autotools install it, but it is not needed as there is pdf_ttf.h.

@stweil, should we do the same for autotools, not install pdf.tff?

**Comment by stweil** [comment]
That might be an incompatible change and require a new major version, even if the file was unused.

**Comment by egorpugin** [comment]
@stweil 
Please consider making 5.0 branch, so we can push modern c++ or big (and possibly breaking) changes into main.

**Comment by amitdo** [comment]
Egor, your request conflicts with mine from #3673 - to focus on 5.x in 2022.

**Comment by zdenop** [comment]
> That might be an incompatible change and require a new major version, even if the file was unused.

Any guidelines for this? I had a look at [https://semver.org/](https://semver.org/) and IMO such change has no effect on API and the new version would be backward compatible.

**Comment by stweil** [comment]
I think that the C / C++ API is only one aspect of compatibility.

Removing a file would break distributions which still have that file in their list of installed files. Users might have used that file for special applications.

Note that it is not necessary to add `pdf.tff` to the cmake install rules. They never installed it, so nothing breaks if they now install additional files, but not that one.

**Pull request merged**
