### PR TITLE
Backport changes from master to 4.1 branch

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
@zdenop, those changes should be API compatible. My local API compatibility test does not work (always shows 100 %), so maybe you can test it in your setting.

Can we also apply commit db08786d2d478b2b457a15350e0dabdfc7f97fa1? It removes `host.h` from the API.

**Comment by zdenop** [comment]
I am just testing it (removal of host.h).

**Comment by zdenop** [comment]
Removal of host.h should be ok according my tests.

**Comment by zdenop** [comment]
thanks will you backport also rest of changes?

**Pull request merged**
