### PR TITLE
3.05: Backports from master branch

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
Tesseract 3.05 still includes `vs2010` (which was removed in Tesseract 4.00). The VS2010 support for Tesseract 3.05 was not updated to use Leptonica 1.74, so it won't work. Should it be removed, or is it still used? Then it has to be fixed.

**Comment by amitdo** [comment]
Is there a real dependency in 3.05's code (not the build system) on Leptonica 1.74?

**Comment by Shreeshrii** [comment]
See
https://github.com/tesseract-ocr/tesseract/pull/835/commits/37478e7d99c3406a29dc31d76a749592171e4703

>Since commit 245eebd
<https://github.com/tesseract-ocr/tesseract/commit/245eebdf293ac19f1fb85c36e51daaaa1b5e5a3e>,
Tesseract 3.05

requires Leptonica 1.74.



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
OK. Thanks Shree.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/739#issuecomment-283608563

**Comment by stweil** [comment]
Tesseract 3.05 uses the function `pixReadFromMultipageTiff` which was added in Leptonica 1.74 unconditionally, so this is a hard dependency (not only for training or some special configurations).

**Comment by amitdo** [comment]
I already got an answer for the the dependency issue.

Please give an answer to my question:
https://github.com/tesseract-ocr/tesseract/pull/835#issuecomment-296431715

Another one to consider backporting:
https://github.com/tesseract-ocr/tesseract/issues/557

**Comment by stweil** [comment]
Sure, there are more commits which could be backported from the master branch. I did not add the libtiff related commits because 3.05 could be built without them.

**Comment by amitdo** [comment]
#233 has been fixed in both 3.05 and 4.00, but in 3.05 the OpenCL code path is slower **for multi page tiff** than the regular code path. in 4.00 the OpenCL code path was removed.

**Pull request merged**
