### PR TITLE
Adding --print-fonts-table parameter & tessedit_font_id configuration option

### PR DESCRIPTION
**Pull request by Lucas-C**
Follow-up of https://github.com/tesseract-ocr/tesseract/pull/2784 after rebasing the branch

### CODE REVIEW

**Comment by amitdo** [comment]
What will happen when this is used with a model that does not have a data for the legacy engine?

I seems it will print an empty file.

**Comment by Lucas-C** [comment]
The new CLI arguments are only available when `DISABLED_LEGACY_ENGINE` is not set.

Moreover no file is generated, only extra information on stdout

**Comment by amitdo** [comment]
> The new CLI arguments are only available when `DISABLED_LEGACY_ENGINE` is not set.

I'm taking about the trained models. Models from the tessdata_best and tessdata_fast were only trained with the LSTM engine. They won't have font info.
 
> Moreover no file is generated, only extra information on stdout

So, I guess that "nothing" (empty string) will be printed with this option is used models that does not have font info.

Ideally, a message will be printed to stderr:
"This model does not have font information."

**Comment by Lucas-C** [comment]
Feel free to submit a PR adding such message I guess.
The maintainers will review it

**Comment by amitdo** [comment]
That was just a comment for possible future enhancement.

Anyway, thanks for your contribution.

**Pull request merged**
