### PR TITLE
minor changes to unittests

### PR DESCRIPTION
**Pull request by Shreeshrii**
* Also added additional tests for tessdata_best and tessdata in apiexample.
* Split testcase in apiexample for better readability of code and results log.

### CODE REVIEW

**Comment by stweil** [comment]
`#include "tesseract/baseapi.h"` requires that the header files were installed.

**Comment by Shreeshrii** [comment]
@stweil is tesseract/ not needed here?

**Comment by stweil** [comment]
It is only needed for external code which uses the Tesseract library and the Tesseract API header files, and only if that code uses the compiler flags which are suggested by pkg-config.

**Comment by Shreeshrii** [comment]
@stweil Thanks. Have removed them now.

**Pull request merged**
