### PR TITLE
 Fix some issues with the shell scripts for training

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This replaces #2057.

**Comment by stweil** [comment]
I now updated the pull request after testing it on macOS – one more unbound variable had to be fixed.

**Comment by stweil** [comment]
We should consider making a 4.0.1 release after the last fixes for the training scripts because the issue with unbound variables affects all platforms, not only macOS.

**Comment by zdenop** [comment]
thanks

**Pull request merged**
