### PR TITLE
Add more unit tests

### PR DESCRIPTION
**Pull request by stweil**
Two of them currently fail because of missing test data.

### CODE REVIEW

**Comment by zdenop** [comment]
@stweil : can you please check current code? `./autogen.sh` reports:
```
...
src/api/Makefile.am: installing 'config/depcomp'
unittest/Makefile.am:144: warning: variable 'baseapi_thread_test_SOURCES' is defined but no program or
unittest/Makefile.am:144: library has 'baseapi_thread_test' as canonical name (possible typo)
unittest/Makefile.am:198: warning: variable 'pango_font_info_test_SOURCES' is defined but no program or
unittest/Makefile.am:198: library has 'pango_font_info_test' as canonical name (possible typo)
unittest/Makefile.am:145: warning: variable 'baseapi_thread_test_LDADD' is defined but no program or
unittest/Makefile.am:145: library has 'baseapi_thread_test' as canonical name (possible typo)
unittest/Makefile.am:199: warning: variable 'pango_font_info_test_LDADD' is defined but no program or
unittest/Makefile.am:199: library has 'pango_font_info_test' as canonical name (possible typo)
Running autoconf
```

and `./configure --prefix=/usr && make dist-xz` failes with:
```
...
 (cd unittest && make  top_distdir=../tesseract-4.0.0-rc2-50-gc504 distdir=../tesseract-4.0.0-rc2-50-gc504/unittest \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[1]: Entering directory '/data/src/tesseract/tesseract/unittest'
make[1]: *** No rule to make target '../abseil/absl/base/internal/cycleclock.cc', needed by 'distdir'.  Stop.
make[1]: Leaving directory '/data/src/tesseract/tesseract/unittest'
make: *** [Makefile:598: distdir] Error 1
```

**Comment by stweil** [comment]
Pull request #1983 fixes the warnings.

The build failure comes from the missing submodule abseil. Get it with `git submodule init && git submodule update`. I will send another pull request to fix builds with missing submodules (just have to look how this can be done).

**Comment by stweil** [comment]
I just noticed that `make dist-xz` also builds documentation for the submodules. I don't think this is something which we want because it takes build time for information which is not related to Tesseract. This should be fixed for 4.0.0.

**Comment by zdenop** [comment]
That's why[ I wrote](https://groups.google.com/forum/#!topic/tesseract-dev/GooowijCSgo) that IMO all *test* should to [test repository](https://github.com/tesseract-ocr/test) => outside of tesseract engine repository.

**Comment by zdenop** [comment]
I am still getting:

```
make[1]: Entering directory '/data/src/tesseract/tesseract/unittest'
make[1]: *** No rule to make target '../abseil/absl/base/internal/cycleclock.cc', needed by 'distdir'.  Stop.
make[1]: Leaving directory '/data/src/tesseract/tesseract/unittest'
make: *** [Makefile:599: distdir] Error 1
```

**Comment by zdenop** [comment]
I did:
```
git pull
git submodule update
./autogen.sh
./configure --prefix=/usr
make distclean
./configure --prefix=/usr && make dist-xz
```

**Comment by zdenop** [comment]
thanks. now it works.

**Comment by Shreeshrii** [comment]
I am getting the errors

Line 243: + git submodule init
	Line 244: + git submodule update
	Line 246: fatal: clone of 'https://github.com/abseil/abseil-cpp.git'
into submodule path 'abseil' failed

Line 863: make  libgtest.la libgtest_main.la libgmock.la
libgmock_main.la libabseil.la apiexample_test applybox_test
baseapi_test bitvector_test cleanapi_test colpartition_test
denorm_test fileio_test heap_test imagedata_test indexmapbidi_test
intfeaturemap_test intsimdmatrix_test lang_model_test linlsq_test
loadlang_test mastertrainer_test matrix_test nthitem_test osd_test
paragraphs_test progress_test qrsequence_test rect_test stats_test
tablefind_test tablerecog_test tabvector_test tfile_test
tesseracttests commandlineflags_test validator_test
	Line 869: make[2]: *** No rule to make target
'../abseil/absl/base/internal/cycleclock.cc', needed by
'../abseil/absl/base/internal/cycleclock.lo'.  Stop.
	Line 869: make[2]: *** No rule to make target
'../abseil/absl/base/internal/cycleclock.cc', needed by
'../abseil/absl/base/internal/cycleclock.lo'.  Stop.

On 10/12/18, Stefan Weil <notifications@github.com> wrote:
> Pull request #1983 fixes the warnings.
>
> The build failure comes from the missing submodule abseil. Get it with `git
> submodule init && git submodule update`. I will send another pull request to
> fix builds with missing submodules (just have to look how this can be
> done).
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/tesseract/pull/1982#issuecomment-429370516


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Making check in unittest
make[1]: Entering directory '/home/ubuntu/tesseract/unittest'
make  libgtest.la libgtest_main.la libgmock.la libgmock_main.la
libabseil.la apiexample_test applybox_test baseapi_test bitvector_test
cleanapi_test colpartition_test denorm_test fileio_test heap_test
imagedata_test indexmapbidi_test intfeaturemap_test intsimdmatrix_test
lang_model_test linlsq_test loadlang_test mastertrainer_test
matrix_test nthitem_test osd_test paragraphs_test progress_test
qrsequence_test rect_test stats_test tablefind_test tablerecog_test
tabvector_test tfile_test tesseracttests commandlineflags_test
validator_test
make[2]: Entering directory '/home/ubuntu/tesseract/unittest'
make[2]: 'libgtest.la' is up to date.
make[2]: 'libgtest_main.la' is up to date.
make[2]: 'libgmock.la' is up to date.
make[2]: 'libgmock_main.la' is up to date.
make[2]: 'libabseil.la' is up to date.
make[2]: 'apiexample_test' is up to date.
make[2]: 'applybox_test' is up to date.
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11
-o baseapi_test baseapi_test.o libabseil.la libgtest.la
libgtest_main.la ../src/api/libtesseract.la -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/baseapi_test
baseapi_test.o  ./.libs/libabseil.a ./.libs/libgtest.a
./.libs/libgtest_main.a ../src/api/.libs/libtesseract.so -lpthread
-fopenmp
/usr/bin/powerpc64le-linux-gnu-ld: baseapi_test.o: undefined reference
to symbol 'pixRead'
//usr/lib/powerpc64le-linux-gnu/liblept.so.5: error adding symbols:
DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1122: recipe for target 'baseapi_test' failed
make[2]: *** [baseapi_test] Error 1
make[2]: Leaving directory '/home/ubuntu/tesseract/unittest'
Makefile:1880: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ubuntu/tesseract/unittest'
Makefile:497: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
ubuntu@tesseract-ocr:~/tesseract$ tesseract -v
tesseract 4.0.0-rc2-56-g9040
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 :
libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
ubuntu@tesseract-ocr:~/tesseract$ git submodule init && git submodule update


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by zdenop** [comment]
@Shreeshrii: You need to fix errors first:
 ```
Line 246: fatal: clone of 'https://github.com/abseil/abseil-cpp.git'
into submodule path 'abseil' failed
```
Why git is not able to clone repository???
And also this one:
```
//usr/lib/powerpc64le-linux-gnu/liblept.so.5: error adding symbols:
DSO missing from command line
```
Booth seems to be your local issue.

**Comment by Shreeshrii** [comment]
baseapi_test_SOURCES = baseapi_test.cc
baseapi_test_LDADD = $(ABSEIL_LIBS) $(GTEST_LIBS) $(TESS_LIBS) $(LEPTONICA_LIBS)

It works after adding leptonica in the unittest/makefile.am for baseapi_test.cc

-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
@zdenop I deleted the abseil folder and then did
git submodule init && git submodule update
again and it worked.

@stweil I am getting test failures on 3 tests - I am using
langdata_lstm as the langdata directory.

PASS: indexmapbidi_test
FAIL: intfeaturemap_test
PASS: intsimdmatrix_test
FAIL: lang_model_test
PASS: linlsq_test
PASS: loadlang_test
../config/test-driver: line 107: 30194 Segmentation fault      (core
dumped) "$@" > $log_file 2>&1
FAIL: mastertrainer_test
PASS: matrix_test


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Running main() from ../googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from IntFeatureMapTest
[ RUN      ] IntFeatureMapTest.Exhaustive
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] IntFeatureMapTest.Exhaustive (442 ms)
[----------] 1 test from IntFeatureMapTest (471 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (471 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IntFeatureMapTest.Exhaustive

 1 FAILED TEST
FAIL intfeaturemap_test (exit status: 1)


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Running main() from ../googletest/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from MasterTrainerTest
[ RUN      ] MasterTrainerTest.Il1Test
Warning: No shape table file present: shapetable
fontinfo table is of size 6164
Failed to load font xheights from
/home/ubuntu/tesseract/test/testing/eng.xheights
mastertrainer_test.cc:201: Failure
Value of: master_trainer_ != nullptr
  Actual: false
Expected: true
mastertrainer_test.cc:202: Failure
Value of: shape_table_ != nullptr
  Actual: false
Expected: true
FAIL mastertrainer_test (exit status: 139)


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Is it missing the following file??
  std::string unicharset_path = TestDataNameToPath("eng_beam.unicharset");


Running main() from ../googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from LangModelTest
[ RUN      ] LangModelTest.AddACharacter
lang_model_test.cc:43: Failure
Value of: unicharset.load_from_file(unicharset_path.c_str())
  Actual: false
Expected: true
Config file is optional, continuing...
Failed to read data from: /home/ubuntu/langdata_lstm/eng/eng.config
Null char=2
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Encoding of string failed! Failure bytes: 53 69 6d 70 6c 65 20 41 53
43 49 49 20 73 74 72 69 6e 67 20 74 6f 20 65 6e 63 6f 64 65 20 21 40
23 24 25 26
[INFO]  Output dir=.lang_model_test.cc:70: Failure
Value of: trainer1.EncodeString(kTestString, &labels1)
  Actual: false
Expected: true
Config file is optional, continuing...
Failed to read data from: /home/ubuntu/langdata_lstm/extended/extended.config
Null char=2
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Encoding of string failed! Failure bytes: 53 69 6d 70 6c 65 20 41 53
43 49 49 20 73 74 72 69 6e 67 20 74 6f 20 65 6e 63 6f 64 65 20 21 40
23 24 25 26
lang_model_test.cc:90: Failure
Value of: trainer2.EncodeString(kTestString, &labels2)
  Actual: false
Expected: true
lang_model_test.cc:97: Failure
Expected equality of these values:
  null1 + 1
    Which is: 4
  null2
    Which is: 2
Encoding of string failed! Failure bytes: 41 53 43 49 49 20 73 74 72
69 6e 67 20 77 69 74 68 20 52 75 70 65 65 20 73 79 6d 62 6f 6c 20 e2
82 b9
Encoding of string failed! Failure bytes: 41 53 43 49 49 20 73 74 72
69 6e 67 20 77 69 74 68 20 52 75 70 65 65 20 73 79 6d 62 6f 6c 20 e2
82 b9
lang_model_test.cc:110: Failure
Value of: trainer2.EncodeString(kTestStringRupees, &labels2)
  Actual: false
Expected: true
[  FAILED  ] LangModelTest.AddACharacter (2599 ms)
[----------] 1 test from LangModelTest (2599 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2599 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LangModelTest.AddACharacter

 1 FAILED TEST
FAIL lang_model_test (exit status: 1)


On 10/12/18, Shree Devi Kumar <shreeshrii@gmail.com> wrote:
> Running main() from ../googletest/googletest/src/gtest_main.cc
> [==========] Running 2 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 2 tests from MasterTrainerTest
> [ RUN      ] MasterTrainerTest.Il1Test
> Warning: No shape table file present: shapetable
> fontinfo table is of size 6164
> Failed to load font xheights from
> /home/ubuntu/tesseract/test/testing/eng.xheights
> mastertrainer_test.cc:201: Failure
> Value of: master_trainer_ != nullptr
>   Actual: false
> Expected: true
> mastertrainer_test.cc:202: Failure
> Value of: shape_table_ != nullptr
>   Actual: false
> Expected: true
> FAIL mastertrainer_test (exit status: 139)
>
>
> --
>
> ____________________________________________________________
> भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
>


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
`intfeaturemap_test` works for me (with langdata/, not langdata-lstm/).

The other two failed tests are expected because of missing files. I hope we can get those files soon.

**Comment by Shreeshrii** [comment]
1. intfeaturemap_test  got error only in one run. After that I tested
with both langdata and langdata_lstm and it worked (the program does
not seem to use langdata).

2. However the following error appears while running make check.

../config/test-driver: line 107: 30194 Segmentation fault      (core
dumped) "$@" > $log_file 2>&1

Where should I look for this $log_file?



-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Pull request merged**
