### PR TITLE
Update ScrollView.java

### PR DESCRIPTION
**Pull request by Parryword**
typo fixed

### CODE REVIEW

**Review by stweil — COMMENTED** [review]
I'll wait until you have more updates for comments. Please combine them all then in a single pull request.

**Comment by stweil** [comment]
Hi @Parryword. We appreciate your contributions, but please don't create a new pull request for every small update. Just add more commits to the pull request here.

And please also set your full name and e-mail address, so people can see who contributed to the Tesseract code.

**Comment by Parryword** [comment]
Thank you! I will be fixing typos in this PR.

**Comment by Parryword** [comment]
@stweil think it is good to go.

**Pull request merged**
