### PR TITLE
Clean ambigs.h and replace octal characters by UTF-8 string in universalambigs

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
The `LoadUniversal` method is always called for each language (plus typically for `osd`) and requires significant resources (time and memory) although the `unichar_ambigs` are often unused.

So there remains potential for optimizations.

**Comment by Shreeshrii** [comment]
Is unichar_ambigs used only by legacy engine/models?

**Comment by zdenop** [comment]
thanks!

**Comment by egorpugin** [comment]
VS now says
```
C:/projects/tesseract/src/ccutil/universalambigs.cpp(7321): fatal error C1091: compiler limit: string exceeds 65535 bytes in length
```

**Comment by zdenop** [comment]
What it version of VS? I just try clang 9 with VS compatibility and build is without problem.

**Comment by egorpugin** [comment]
This is from appveyor (VS2017).
Any VS has such string limit. Other compilers obviously don't.
And clang usually do not repeat bad parts of VS in compat mode.

**Comment by zdenop** [comment]
OK. I see....  On SO there is [suggestion to use array instead of long string](https://stackoverflow.com/questions/2481998/how-do-i-include-extremely-long-literals-in-c-source) .

**Comment by stweil** [comment]
That VS compilers are always good for a surprise. They accept long character arrays if those arrays are initialized using integers (like in the old code), but not if they are initialized by a string (like in the new code), although that is the more natural form.

I already considered to move the string into an external config file. That would reduce the size of the tesseract binary, but cost a little extra time for the file handling. I think that might be acceptable if it is only done when it is really used – I still have to find out that.

**Comment by zdenop** [comment]
VS standard is to use resource file for such purposes. Similar technique is used by Qt library (on all supported platforms). But there is nothing like that in pure C or C++ that would be portable...

Unfortunately on your idea to move it to external file is in conflict with [my idea](https://github.com/tesseract-ocr/tesseract/issues/2551) ;-) to have just library where is everything needed excluding language data. So packagers do not need to distribute config files and care about their location.

**Comment by egorpugin** [comment]
I do similar embedding of needed files.
Cppan/Sw unpacks them when running.

**Comment by amitdo** [comment]
The 'temporary' hack done in b8079d8ce18996a should be fixed somehow.

**Comment by amitdo** [comment]
The langdata repo also contains unicharambigs files:
https://github.com/tesseract-ocr/langdata/blob/master/eng/eng.unicharambigs

**Comment by amitdo** [comment]
The content of `universalambigs.cpp` looks strange to me.

**Pull request merged**
