### PR TITLE
Add missing % char from format specifier in tlog()

### PR DESCRIPTION
**Pull request by amitdo**
- In training/ango_font_info.cpp

### CODE REVIEW

**Comment by stweil** [comment]
Good catch. There seem to be more errors of this kind.

**Comment by amitdo** [comment]
>Good catch. 

Thanks. I've noticed that missing symbol in #195.

>There seem to be more errors of this kind.

I see you already hunted two... :-)

**Comment by stweil** [comment]
The trick is to compile with `-Wmissing-format-attribute`, fix all related warnings and iterate this until no format related warnings remain. Projects like Tesseract which never used gcc's format attribute typically have lots of format errors. I just started the search, and the current count is 6.

Fixing those format errors is one task, another one is adding the format attribute and the compiler options where needed, so future contributions won't introduce new errors.

**Comment by amitdo** [comment]
Would that flag catch that missing % from format specifier?

**Comment by stweil** [comment]
That flag would result in warnings for all functions with printf or scanf like arguments which don't use the format attribute. Then it is necessary to add a format function attribute to each of those function declarations. After this, gcc will know which functions work similar to printf or scanf and report all errors (if that warning is enabled, for example with `-Wall -Wextra`).

**Pull request merged**
