### PR TITLE
Fix some typos in comments and documentation

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by amitdo** [comment]
You can add` [skip ci]` to a commit title/message when you send non-code fixes.

**Comment by stweil** [comment]
Thanks, that is good to know. Especially the AppVeyor CI takes a lot of (unnecessary) time and energy.

**Comment by amitdo** [comment]
Maybe we should disable the 2015 builds by commenting 2 lines), and uncomment it once a month and before a release.

We can also do the same to the VS 201**7** 32-bit build.

**Comment by Shreeshrii** [comment]
That is a good idea. If possible automate this in the script, either based
on date or on commit number, every 50th or 100th.

And, manually, as needed.

**Comment by Shreeshrii** [comment]
https://help.appveyor.com/discussions/questions/1076-separate-configuration-for-pull-requests

**Comment by Shreeshrii** [comment]
https://help.appveyor.com/discussions/questions/1172-scheduled-nightly-builds

**Comment by Shreeshrii** [comment]
Enable commit filtering in specialized matrix job configuration #2299


https://github.com/appveyor/ci/issues/2299

**Comment by amitdo** [comment]
CC: @egorpugin, 
About AppVeyor...

**Comment by amitdo** [comment]
https://ci.appveyor.com/project/zdenop/tesseract/build/master.1878
One job is taking 7 minutes to complete, the others ~40. Why?

**Comment by egorpugin** [comment]
Cache limit is 100 MB across all configs. Cppan build deps and they take much space, so cache is not working anymore and builds are done from scratch each time.

**Comment by Shreeshrii** [comment]
FYI 
https://github.com/appveyor/ci/issues/2299#issuecomment-403561551

**Comment by amitdo** [comment]
Thanks Shree :-)

**Comment by amitdo** [comment]
@egorpugin, 

Can you do one of these: 

>* Would it be sufficient to test 32 bit with Visual Studio 2015 and 64 bit with Visual Studio 2017? I think yes.
>* Maybe it would be sufficient to test 64 bit with Visual Studio 2017 for pull requests and run extended tests only for merged code.

**Comment by egorpugin** [comment]
Let's start with p.1.

**Pull request merged**
