### PR TITLE
Remove old code which was used for Ocropus

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This should fix issue #2926.

**Comment by zdenop** [comment]
thanks

**Comment by amitdo** [comment]
SetFillLatticeFunc(FillLatticeFunc() was not part of the ocropus stuff.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/search?q=fill_lattice_&unscoped_q=fill_lattice_

**Comment by stweil** [comment]
@amitdo, maybe the code which refers to `fill_lattice_` could be removed, too. Or is there someone who uses that?

**Comment by amitdo** [comment]
Maybe that code is/was used by Google internal version.

**Comment by amitdo** [comment]
Here's another SetSomethingFunc

https://github.com/tesseract-ocr/tesseract/blob/23be532f7d91c88fd3d3c32199526438b3990092/src/api/baseapi.cpp#L1993

[probability_in_context_](https://github.com/tesseract-ocr/tesseract/search?q=probability_in_context_)


https://groups.google.com/forum/?hl=en#!topic/tesseract-dev/YsJogVVFbGk


>Ray 9/9/14
>
>There is no code in tesseract to implement or train an n-gram model, only to make use of one.
>
>There is a "hook" function and code to set it to an external function.
TessBaseAPI::SetProbabilityInContextFunc is used to set it.
>
>We experimented with it in Google with some existing Google-specific n-gram library. It didn't help very much in most languages, although it does in cases where the dictionary is particularly weak for some reason, like CJK.
>
>A single function is required that returns the probability of the current "character" (in general a utf-8 string) given the context of a previous utf-8 string.
It is fairly simple to write and train, given appropriate training data.
>
>The difficulty is with balancing the strength of the n-gram model and the shape classifier confidences. For speech recognition, where typical system accuracies are 80-90%, it is easy to use language models to combine with a poor accuracy phoneme classifier, but in OCR, where typical word accuracies exceed 95% (for alphabetic, word-segmented languages) language models of any kind can easily start replacing infrequent, but correct results with more frequent, but wrong results, and nobody has properly solved the problem in a way that is mathematically and statistically rigorous. Looking at OCR output, it is easy to spot cases where language models could help, but not so easy to see the already-correct results that would be made worse.

**Comment by amitdo** [comment]
@stweil,

GetPageRes() is used in unittest/baseapi_test.cc

**Comment by stweil** [comment]
Thank you. Sorry that I missed that. Pull request #2962 should fix it.

**Pull request merged**
