### PR TITLE
Move LSTMTrainer from libtesseract to libtesseract_training

### PR DESCRIPTION
**Pull request by stweil**
LSTMTrainer is only used for training, so the shared library for
Tesseract can be made smaller.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by egorpugin** [comment]
Seems `sw.cpp` must be changed also.

**Comment by stweil** [comment]
Yes, indeed. I missed that file. Now the pull request was updated, so let's see whether the Windows build works again.

**Comment by egorpugin** [comment]
kMinCertainty is missing from recodebeam.cpp/.h
These files are completely missing from sw.cpp.

**Comment by stweil** [comment]
It is part of libtesseract which is included using a wildcard pattern.

**Comment by egorpugin** [comment]
Oh, yes. I mean that symbol is not public - not `TESS_API`.

**Comment by stweil** [comment]
Rewriting `src/lstm/recodebeam.*` simplified the code and fixed that.

**Pull request merged**
