### PR TITLE
Optimize calculation of dot product for double vectors with AVX

### PR DESCRIPTION
**Pull request by stweil**
This improves the performance with best models and should also
make training faster.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This replaces pull request #954. See timing results for OCR there.

Feedback on more timing results on other hardware with AVX (also with training) would be interesting.

**Comment by stweil** [comment]
The current test results show a large performance increase on server hardware, but on typical other platforms (tested on a virtual machine and on a MacBook Pro) the increase is small (about 2 %).

**Comment by amitdo** [comment]
You might want to try using FMA.

https://en.wikipedia.org/wiki/FMA_instruction_set
https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation

**Comment by stweil** [comment]
All my machines with AVX also support FMA, so I can try that. Thank you for the hint.

**Comment by zdenop** [comment]
thanks.

**Comment by amitdo** [comment]
@stweil, a reminder about FMA...

**Comment by stweil** [comment]
Thank you for the reminder. The first test results with debug code look promissing:

    $ time -p tesseract test/testing/phototest.tif - -l tessdata_best/script/Latin -c dotproduct=fma
    Page 1
    This is a lot of 12 point text to test the
    ocr code and see if it works on all types
    of file format.

    The quick brown dog jumped over the
    lazy fox. The quick brown dog jumped
    over the lazy fox. The quick brown dog
    jumped over the lazy fox. The quick
    brown dog jumped over the lazy fox.

    real 10.25
    user 9.87
    sys 0.26
    $ time -p tesseract test/testing/phototest.tif - -l tessdata_best/script/Latin -c dotproduct=fma
    Page 1
    This is a lot of 12 point text to test the
    ocr code and see if it works on all types
    of file format.

    The quick brown dog jumped over the
    lazy fox. The quick brown dog jumped
    over the lazy fox. The quick brown dog
    jumped over the lazy fox. The quick
    brown dog jumped over the lazy fox.

    real 10.35
    user 9.94
    sys 0.27
    $ time -p tesseract test/testing/phototest.tif - -l tessdata_best/script/Latin -c dotproduct=avx
    Page 1
    This is a lot of 12 point text to test the
    ocr code and see if it works on all types
    of file format.

    The quick brown dog jumped over the
    lazy fox. The quick brown dog jumped
    over the lazy fox. The quick brown dog
    jumped over the lazy fox. The quick
    brown dog jumped over the lazy fox.

    real 12.39
    user 11.96
    sys 0.27
    $ time -p tesseract test/testing/phototest.tif - -l tessdata_best/script/Latin -c dotproduct=avx
    Page 1
    This is a lot of 12 point text to test the
    ocr code and see if it works on all types
    of file format.

    The quick brown dog jumped over the
    lazy fox. The quick brown dog jumped
    over the lazy fox. The quick brown dog
    jumped over the lazy fox. The quick
    brown dog jumped over the lazy fox.

    real 12.73
    user 12.17
    sys 0.30

**Comment by stweil** [comment]
FMA is supported in the latest code and gives about the same performance as AVX.

**Comment by amitdo** [comment]
Thanks!

**Pull request merged**
