### PR TITLE
Change dummy test to OSD Tests for Tesseract.

### PR DESCRIPTION
**Pull request by Shreeshrii**
based on gist by @amitdo

@stweil please review.

Should this be moved to unittest folder?

### CODE REVIEW

**Comment by Shreeshrii** [comment]
Running main() from gtest_main.cc
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from OSDTestCase/OSDTest
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/0
[ LOG MSG ] ../../tessdata_best/ for image: ../testing/phototest.tif
Orientation in degrees: 0
Orientation confidence: 10.86
Script: Latin
Script confidence: 10.56
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/0 (2667 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/1
[ LOG MSG ] ../../tessdata_fast/ for image: ../testing/phototest.tif
Orientation in degrees: 0
Orientation confidence: 10.86
Script: Latin
Script confidence: 10.56
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/1 (2516 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/2
[ LOG MSG ] ../../tessdata/ for image: ../testing/phototest.tif
Orientation in degrees: 0
Orientation confidence: 10.86
Script: Latin
Script confidence: 10.56
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/2 (1889 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/3
[ LOG MSG ] ../../tessdata_best/ for image: ../testing/eurotext.tif
Orientation in degrees: 0
Orientation confidence: 30.13
Script: Latin
Script confidence: 5.75
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/3 (2294 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/4
[ LOG MSG ] ../../tessdata_fast/ for image: ../testing/eurotext.tif
Orientation in degrees: 0
Orientation confidence: 30.13
Script: Latin
Script confidence: 5.75
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/4 (2130 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/5
[ LOG MSG ] ../../tessdata/ for image: ../testing/eurotext.tif
Orientation in degrees: 0
Orientation confidence: 30.13
Script: Latin
Script confidence: 5.75
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/5 (2242 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/6
[ LOG MSG ] ../../tessdata_best/ for image: ../testing/hebrew.png
Orientation in degrees: 0
Orientation confidence: 25.54
Script: Hebrew
Script confidence: 41.11
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/6 (1727 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/7
[ LOG MSG ] ../../tessdata_fast/ for image: ../testing/hebrew.png
Orientation in degrees: 0
Orientation confidence: 25.54
Script: Hebrew
Script confidence: 41.11
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/7 (1870 ms)
[ RUN      ] OSDTestCase/OSDTest.EngEuroHebrew/8
[ LOG MSG ] ../../tessdata/ for image: ../testing/hebrew.png
Orientation in degrees: 0
Orientation confidence: 25.54
Script: Hebrew
Script confidence: 41.11
[       OK ] OSDTestCase/OSDTest.EngEuroHebrew/8 (1626 ms)
[----------] 9 tests from OSDTestCase/OSDTest (18972 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test case ran. (18973 ms total)
[  PASSED  ] 9 tests.

**Comment by Shreeshrii** [comment]
The test is run using osd.traineddata in tessdata, tessdata_best and tessdata_fast. 

While currently all three repositories have the same version of osd.traineddata, this test would have helped identify problems with osd.traineddata in the best and fast repos.

**Comment by amitdo** [comment]
You might want to add at least 2 rotated images and add tests that use them.

**Comment by Shreeshrii** [comment]
Thanks for the suggestion @amitdo . Please review new version.

**Pull request closed without merging**
