### PR TITLE
Edit pthread link position

### PR DESCRIPTION
**Pull request by zhbanito**
Linux problem.
First need link libraries that using function, then libraries, that implementing this function.
Now libwebp linking issue

### CODE REVIEW

**Comment by zdenop** [comment]
I did plenty builds of tesseract (linux and windows) and never meet this. Can you describe process how to reproduce problem?

**Comment by zhbanito** [comment]
Building static library via VCPKG
- gcc 7.4.0
- Ubuntu 18.04.3 LTS via WSL

Have link error

> /mnt/d/projects/utilities/vcpkg/installed/x64-linux-static/debug/lib/libwebpd.a(thread_utils.c.o): In function 'ThreadLoop':
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:211: undefined reference to 'pthread_cond_wait'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:220: undefined reference to 'pthread_cond_signal'
> /mnt/d/projects/utilities/vcpkg/installed/x64-linux-static/debug/lib/libwebpd.a(thread_utils.c.o): In function 'ChangeState':
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:238: undefined reference to 'pthread_cond_wait'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:243: undefined reference to 'pthread_cond_signal'
> /mnt/d/projects/utilities/vcpkg/installed/x64-linux-static/debug/lib/libwebpd.a(thread_utils.c.o): In function 'Reset':
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:280: undefined reference to 'pthread_cond_init'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:281: undefined reference to 'pthread_mutex_destroy'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:289: undefined reference to 'pthread_mutex_destroy'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:290: undefined reference to 'pthread_cond_destroy'
> /mnt/d/projects/utilities/vcpkg/installed/x64-linux-static/debug/lib/libwebpd.a(thread_utils.c.o): In function 'End':
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:325: undefined reference to 'pthread_join'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:326: undefined reference to 'pthread_mutex_destroy'
> /mnt/d/projects/utilities/vcpkg/buildtrees/libwebp/src/v1.0.2-de523ffe87/src/utils/thread_utils.c:327: undefined reference to 'pthread_cond_destroy'

**Comment by stweil** [comment]
`src/utils/thread_utils.c` is third party software. So why do you think it is related to Tesseract?

**Comment by zdenop** [comment]
You probably choose wrong project for reporting issues: linking error are not from tesseract build, but from libwebp.
If you use Ubuntu in WLS, why you do not use standard linux build tools? IMO also libwebp should be installed by Ubuntu package tools to avoid mess in system....

**Pull request closed without merging**
