### PR TITLE
Fix some issues reported by LGTM

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by zdenop** [comment]
This pull request **fixes 6 alerts** when merging f0c9b753c624870e98271fa3446b6e2f7cde38f7 into 9c2d1aad966eca8af7b615ba181eb3ea50e20576 - [view on LGTM.com](https://lgtm.com/projects/g/tesseract-ocr/tesseract/rev/pr-65c5d12b941ee9a8f917454d97ff2d517f7c63e7)

**fixed alerts:**

* 6 for Inconsistent definition of copy constructor and assignment \(&#39;Rule of Two&#39;\)

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by amitdo** [comment]
https://docs.microsoft.com/en-us/cpp/cpp/explicitly-defaulted-and-deleted-functions?view=vs-2017

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbclx01/deleted_functions.htm

**Comment by stweil** [comment]
Thank you for the link. It's always nice to learn. So there is a more elegant C++11 way for the last three commits. I suggest to apply the pull request as it is and would use the C++11 form later (maybe after 4.0.0), as there is more Tesseract code which can be updated for C++11.

**Comment by amitdo** [comment]
Okay.

Apart from `=delete` for the three last commits, I think `=default` could be used for the first one.

**Comment by stweil** [comment]
Just to celebrate #2000 ...

**Pull request merged**
