### PR TITLE
fixes issue #3099

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by amitdo** [comment]
To link to an issue you need to add the `#` symbol before the issue number.

Fix issue #3099.

**Comment by amitdo** [comment]
Does the test pass with this patch?

**Comment by Shreeshrii** [comment]
Yes, it does.

I used the actual results from the test run and put those as expected
results. See the original report which had the lines with the error.

**Comment by amitdo** [comment]
Thanks, Shree.

**Pull request merged**
