### PR TITLE
Lstm choice ril

### PR DESCRIPTION
**Pull request by noahmetzger**
Reworked lstm_choice_mode to make api independent from the choice mode value.
Added a new function to get timesteps segmented by the suggested symbol separator.
Reworked the choice Iterator to show correct choices for lstm-based traineddata now

### CODE REVIEW

**Comment by zdenop** [comment]
This pull request **introduces 1 alert** when merging caa0392dece4e96cc35ebab4da0d398c737e62c1 into e78b5f2af396b0498fed5ce861fb466bd583a458 - [view on LGTM.com](https://lgtm.com/projects/g/tesseract-ocr/tesseract/rev/pr-d48a217bf66a2728ee0c82d4a8f96710bd5fef1b)

**new alerts:**

* 1 for Empty branch of conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by noahmetzger** [comment]
> 
> 
> This pull request **introduces 1 alert** when merging [caa0392](https://github.com/tesseract-ocr/tesseract/commit/caa0392dece4e96cc35ebab4da0d398c737e62c1) into [e78b5f2](https://github.com/tesseract-ocr/tesseract/commit/e78b5f2af396b0498fed5ce861fb466bd583a458) - [view on LGTM.com](https://lgtm.com/projects/g/tesseract-ocr/tesseract/rev/pr-d48a217bf66a2728ee0c82d4a8f96710bd5fef1b)
> 
> **new alerts:**
> 
>     * 1 for Empty branch of conditional
> 
> 
> _Comment posted by [LGTM.com](https://lgtm.com)_

oh thanks,
thought i had deleted this already.
Now it's fixed

**Comment by stweil** [comment]
Noah, Codacy suggests to use prefix ++/-- operators for non-primitive types (see CI result above).

**Comment by noahmetzger** [comment]
> 
> 
> Noah, Codacy suggests to use prefix ++/-- operators for non-primitive types (see CI result above).

done

**Pull request merged**
