### PR TITLE
Switch to semantic versioning

### PR DESCRIPTION
**Pull request by egorpugin**
@theraysmith @zdenop 

This PR replaces all 4.00.00 version numbers to 4.0.0.
The idea is to follow semantic versioning since 4.0.0 branch. https://semver.org
Following git tags should be also named as `X.Y.Z[-name]`, e.g. `4.0.0`, `4.0.1`, `4.0.0-beta`, `4.0.0-rc.1` etc.

### CODE REVIEW

**Comment by Shreeshrii** [comment]
@egorpugin Isn't it better to change to the new versioning scheme while 4.0 is still in development branch?

Does @zdenop need to change the git tag?

**Comment by egorpugin** [comment]
No need to change old git tags (even 4.00.00alphas), but we need to decide versioning until release.

**Comment by Shreeshrii** [comment]
@jbreiden @AlexanderP 

Should this be implemented before Ubuntu freeze?

**Comment by AlexanderP** [comment]
@Shreeshrii  
I think not.

**Comment by egorpugin** [comment]
This was applied with other commits/PRs.

**Pull request closed without merging**
