### PR TITLE
Update from Leptonica 1.74.1 to 1.74.2

### PR DESCRIPTION
**Pull request by stweil**
The newer version contains fixes for the pixUnsharpMaskingGray*
functions which are relevant for Tesseract (used in ImageData::PreScale
which calls pixScale).

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See [Dan's comment](https://github.com/tesseract-ocr/tesseract/issues/644#issuecomment-306073620) for issue #644.

**Comment by stweil** [comment]
Should we refuse builds with Leptonica < 1.74.2? Then additional changes for `CMakeLists.txt` and `configure.ac` would be needed. The newer version not only fixes problems with undefined memory for `lstmtraining`, but also for `tesseract --oem 1`.

**Comment by stweil** [comment]
Tesseract cmake builds are broken with Leptonica 1.74.2 because Leptonica now requires an installation: the Leptonica_INSTALL_DIRS refer to /usr/local/include. Therefore Travis CI fails. @egorpugin, how should we fix that?

**Comment by egorpugin** [comment]
Someone broke my leptonica cmake scripts? :)

**Comment by egorpugin** [comment]
> Should we refuse builds with Leptonica < 1.74.2?

We can do anything, because it's dev branch.

**Pull request merged**
