### PR TITLE
URW Bookman and Century Schoolbook are no longer valid

### PR DESCRIPTION
**Pull request by mozbugbox**
The fonts are not proper rendered by text2image anymore.

### CODE REVIEW

**Comment by zdenop** [comment]
any prove /example/details to you statement?

**Comment by mozbugbox** [comment]
Since pango 1.44.0 (Released 2009):
- Use harfbuzz for shaping on all platforms
- Stop using freetype for font loading; this
    drops support for type1 and bitmap fonts

And the Century fonts are type1 fonts. The resulting `tif` file generated was a blank canvas with no glyph in it. Therefore 0byte `.box` file,  then no `.lstmf` file were generated.

``` 
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.Century_Schoolbook_L_Bold.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.Century_Schoolbook_L_Bold.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.Century_Schoolbook_L_Bold_Italic.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.Century_Schoolbook_L_Bold_Italic.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.Century_Schoolbook_L_Italic.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.Century_Schoolbook_L_Italic.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.Century_Schoolbook_L_Medium.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.Century_Schoolbook_L_Medium.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.URW_Bookman_L_Bold.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.URW_Bookman_L_Bold.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.URW_Bookman_L_Bold_Italic.exp0.box
-rw------- 1 1000 1000 3184 Aug  1 15:03 eng.URW_Bookman_L_Bold_Italic.exp0.tif
-rw------- 1 1000 1000    0 Aug  1 15:03 eng.URW_Bookman_L_Italic.exp0.box
-rw------- 1 1000 1000 2390 Aug  1 15:03 eng.URW_Bookman_L_Italic.exp0.tif

```

This  can be verified with
```
text2image --fonts_dir /usr/share/fonts --list_available_fonts
```

Issue #2593 was caused by this. 

Actually, there are 
```
2111: URW Bookman Light
2112: URW Bookman Light Italic
2113: URW Bookman Semi-Bold
2114: URW Bookman Semi-Bold Italic
```
But not `URW Bookman L Bold` etc.

Googling return a post said that the 
```
 14: C059
 15: C059 Bold
 16: C059 Bold Italic
 17: C059 Italic
```
were replacement for the Century Schoolbooks, though.
`C059`'s were in the `fonts-urw-base35` package.

**Comment by amitdo** [comment]
https://packages.debian.org/buster/fonts-texgyre

**Comment by amitdo** [comment]
BTW, the font list in language-specific.sh should use for training the legacy engine.

For LSTM see https://github.com/tesseract-ocr/langdata_lstm/blob/master/eng/okfonts.txt.

**Comment by Shreeshrii** [comment]
Why is this not being merged?

**Comment by stweil** [comment]
Instead of just removing the old ones, it might be reasonable to add the replacements, too.

**Comment by amitdo** [comment]
I reject this PR.

Shree, you can open a new PR which replace the font names with their compatible font name from the TeX Gyre collection.

URW Bookman L -> Bonum

Century Schoolbook L -> Schola

**Comment by amitdo** [comment]
```
    "URW Bookman L Bold" \
    "URW Bookman L Italic" \
    "URW Bookman L Bold Italic" \
```

Should be replaced with:

```
    "Tex Gyre Bonum Bold" \
    "Tex Gyre Bonum Italic" \
    "Tex Gyre Bonum Bold Italic" \
```

```
    "Century Schoolbook L Bold" \
    "Century Schoolbook L Italic" \
    "Century Schoolbook L Bold Italic" \
    "Century Schoolbook L Medium" \
```

Should be replaced with:

```
    "Tex Gyre Schola Bold" \
    "Tex Gyre Schola Italic" \
    "Tex Gyre Schola Bold Italic" \
    "Tex Gyre Schola Regular" \
```

**Pull request closed without merging**
