### PR TITLE
Use clang-format for code formatting

### PR DESCRIPTION
**Pull request by ZaMaZaN4iK**
For fixing I used clang-format -i -style=Google **/*.h && clang-format -i -style=Google **/*.cpp

clang-format 6.0.0

In this PR I suggest to discuss about code-style for Tesseract. Because FMPOV Google style isn't ideal for Tesseract and we can add some Tesseract-specific options.

### CODE REVIEW

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/pull/848#issuecomment-298099240
#854

**Comment by stweil** [comment]
Why is https://github.com/stweil/tesseract/tree/format different?

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/pull/1598 is using clang-format 6.0.0

**Comment by stweil** [comment]
I now created https://github.com/stweil/tesseract/tree/clang-format-6 with clang-format 6.0.0-3. The result is identical to that from clang-format 7.0.0 (that means not the same as https://github.com/ZaMaZaN4iK/tesseract/tree/fix_format). It needs three iterations to stabilize. The formatting was done on Debian Buster.

**Comment by stweil** [comment]
https://github.com/stweil/tesseract/tree/clang-format-4 and https://github.com/stweil/tesseract/tree/clang-format-5 give different results.

**Comment by amitdo** [comment]
Run with clang 5 and 6/7:

`clang-format -style=google -dump-config > .clang-format`

Do you get the same result?

**Comment by amitdo** [comment]
appveyor failed.
It doesn't like the openmp formatting in lstm.cpp.

**Comment by stweil** [comment]
Appveyor fails in my four tests, too. https://github.com/stweil/tesseract/commit/4ee0fdccbd36bef919051b4c23f4c068c11b7df5 shows the dumped configurations.

**Comment by amitdo** [comment]
>I suggest to use the same variant everywhere.

:+1: 

`type *variable` vs. `type* variable`

>Personally I  prefer the first one, but using only the second one would also be fine.  What do you think?

It seems that Ray prefers `type* variable` (it's also my favorite style).
https://github.com/tesseract-ocr/tesseract/commit/c1c1e426b32794d5e84134ee81bf895ff0228fe5#diff-f5c88d7e2ff4fc9424ae517ce7b4e1a6

**Comment by ZaMaZaN4iK** [comment]
@amitdo I also prefer `type* variable`

**Comment by ZaMaZaN4iK** [comment]
I think we should dump existing one format profile (suggest use Google code style), correct it a little bit and push to Tesseract repo

**Comment by stweil** [comment]
https://github.com/stweil/tesseract/tree/format now uses uniform left aligned pointers and also includes a `.clang-format` file. Stil missing: build fix for Appveyor.

**Comment by zdenop** [comment]
If yes, than we should do it before 4.0 release.

**Comment by ekene90** [comment]
it is good

**Comment by kingmoduk** [comment]
were are you

**Comment by zdenop** [comment]
@ZaMaZaN4iK , @stweil : Can be this PR fixed / replaced / closed this week?

**Comment by stweil** [comment]
Yes, it can be closed. I think we won't reformat the whole code for 4.0.0.

**Comment by amitdo** [comment]
I suggest to re-format the whole codebase for 5.0.0.

**Comment by amitdo** [comment]
First step - reformat all headers in 'include/tesseract'.

**Pull request closed without merging**
