### PR TITLE
Unittest: Fix Thai valid text and add Thai illegal sequences

### PR DESCRIPTION
**Pull request by bact**
## Fix a typo in "valid text" `kScriptText`

- Replace the word "ท่ำ" with "ทำ"
- Replace the word "ธปเทียน" with "ธูปเทียน"

## Add two illegal sequence in `kBadlyFormedThaiWords`

The code was:
```cpp
const char* kBadlyFormedThaiWords[] = {"ฤิ", "กา้ํ", "กิำ"};
```

proposed:
```cpp
const char* kBadlyFormedThaiWords[] = {"ฤิ", "กา้ํ", "กิำ", "นำ้", "เเก"};
```

**First one added is an illegal sequence of "น้ำ" (water)**

The legal sequence for is
- น `(0E19)` + ้ `(0E49)` + ำ `(0E33)`

but sometimes found in this sequence (wrong order, and sometimes can be rendered visually similar)
- น `(0E19)` + ำ `(0E33)` +  ้ `(0E49)`

**Second one added is an illegal sequence of "แก" (you)**

The legal sequence for is
- แ `(0E41)` + ก `(0E01)`

sometimes found in this sequence (use two `0E40`s instead of `0E41`, visually similar)
- เ `(0E40)` + เ `(0E40)` + ก `(0E01)`

### CODE REVIEW

**Comment by zdenop** [comment]
@Shreeshrii : Are you able to check this PR?

**Comment by Shreeshrii** [comment]
@zdenop I do not know Thai language/script.

@bact 
Please describe the changes you have made so that non-Thai speakers can understand. 
Explain what fix you have made in Thai valid text and Thai illegal sequences. 
Thanks.

**Comment by bact** [comment]
@zdenop @Shreeshrii thank you. I edited the descrption above, added the explanation.

**Comment by zdenop** [comment]
thanks.

**Pull request merged**
