### PR TITLE
Show names of failing lstmf files in error messages 

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
Especially "Compute CTC targets failed" is [reported quite often](https://github.com/tesseract-ocr/tesseract/issues?q=%22Compute+CTC+targets+failed%22). Hopefully the enhanced error messages help users to fix the problems in their training data.

**Comment by Shreeshrii** [comment]
This is a welcome addition. It will reduce a lot of user queries too. Thanks @stweil.

**Comment by Shreeshrii** [comment]
Question: WIll it also identify a line number for those who use multi-page tifs created by text2image via tesstrain.sh?

**Comment by stweil** [comment]
> Question: WIll it also identify a line number for those who use multi-page tifs created by text2image via tesstrain.sh?

A page number for multi-page TIFF files is also available, but currently not shown in the error messages. It can easily be added. How should the error message look like? Can we use the same message format for single line images and multi-page TIFFS, or should it be different?

**Comment by Shreeshrii** [comment]
Currently during lstmtraining with multipage tifs, debug info is shown as below:

```
Iteration 25135: GROUND  TRUTH : ميلاعت تءاج دقو . ةيما ينب ديب تناك شيرق يف ايلعلا ةطلسلا نا ريغ لئابقلا
File /tmp/ara-2021-01-20.hRX/ara.Amiri.exp0.lstmf line 1057 (Perfect):
Mean rms=0.462%, delta=0.428%, train=1.369%(3.172%), skip ratio=0%
Iteration 25136: GROUND  TRUTH : ٢
File /tmp/ara-2021-01-20.hRX/ara.Amiri.exp0.lstmf line 5256 (Perfect):
Mean rms=0.462%, delta=0.428%, train=1.369%(3.172%), skip ratio=0%
Iteration 25137: GROUND  TRUTH : ةفاطللا ةياغ يف امهناف مرفسهاشلاو درولاک ادًج ةريثك ةرخبأ اهنم ينحل يتلا ءايشالا مشو . هطشمو
Iteration 25137: BEST OCR TEXT : ةفاطللا ةياغ يف امهناف مرفسهاشلاو درولاك ادج ةريثك ةرخبأ اهنم ينحل يتلا ءايشالا مشو . هطشمو
File /tmp/ara-2021-01-20.hRX/ara.Amiri.exp0.lstmf line 303 :
Mean rms=0.463%, delta=0.43%, train=1.372%(3.184%), skip ratio=0%
Iteration 25138: GROUND  TRUTH : نسحلا ىدل درو امب دورابلا حلمب مهتفرعم ديأتت نيذلا . يمالسالا ملاعلا - ٢
File /tmp/ara-2021-01-20.hRX/ara.Amiri.exp0.lstmf line 8383 (Perfect)
```

I think the page number = line number as shown above.  A format consistent with the above should be ok.

**Pull request merged**
