### PR TITLE
RFC: Add support for image or image list by URL

### PR DESCRIPTION
**Pull request by stweil**
This allows OCR of images from the internet without downloading them first:

    tesseract http://IMAGE_URL OUTPUT ...

It uses libcurl.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Is this a feature which is useful for others, too?

I want to use it for distributed OCR of books and newspapers with thousands of pages to avoid
downloading of temporary image files to disk.

libcurl not only supports http: and https:, but also other schemas like ftp: or ssh:, which could be added
to the new code, too, if needed.

**Comment by jbreiden** [comment]
Tesseract already accepts images on stdin. Why not use the curl binary and
pipes to avoid temp files?

**Comment by jbreiden** [comment]
I also wonder if it might cause any issues for larger software that uses
Tesseract as a component, such as ffmpeg or opencv.

>

**Comment by egorpugin** [comment]
Maybe it's possible to add this into tesseract binary, not library, in case if you need this on command line.
If you use tesslib it is possible to integrate curl into your app.

**Comment by zdenop** [comment]
This works for me:
```
curl "http://d2jaiao3zdxbzm.cloudfront.net/wp-content/uploads/figure-65.png" | tesseract - -
```
If the feature is already available, way to add additional dependency to tesseract?

**Comment by stweil** [comment]
The current implementation adds curl in baseapi,cpp, so it's part of the library. Of course I could make curl support optional with `--disable-curl` being the default configure setting.

The pipe solution needs an additional step to add the image name to the hOCR output.

**Comment by stweil** [comment]
See https://groups.google.com/forum/#!topic/tesseract-dev/ZFn38UEOWM8 with a discussion to extend URL support to get traineddata models, too.

**Comment by Shreeshrii** [comment]
I think this will be a useful addition, specially from command line.

The concerns raised are addressed by @stweil's suggestion:

> I could make curl support optional with --disable-curl being the default configure setting.

**Comment by zdenop** [comment]
@Shreeshrii : see my comment at [tesseract-dev forum](https://groups.google.com/d/msg/tesseract-dev/ZFn38UEOWM8/VBmPEn2WAAAJ)

**Comment by MakaWeli** [comment]
https://twitter.com/@xsamas12

**Comment by MakaWeli** [comment]
https://twitter.com/@xsamas12

**Comment by egorpugin** [comment]
Is PR ready for merging?
If yes, no need to keep it longer unmerged.

**Comment by stweil** [comment]
> Is PR ready for merging?

Technically it is ready, but it currently only works with `autoconf` (CMake support is still missing), and there is also no `configure` option like `--disable-curl` which allows disabling it at build time.

**Pull request merged**
