### PR TITLE
Add XML_CATALOG_FILES for MacOS with Homebrew

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by nnnikolay** [comment]
Hey @stweil , with this PR I receive 

```
checking for pangoft2... yes
checking that generated files are newer than configure... done
configure: error: conditional "HAVE_XML_CATALOG_FILES" was never defined.
Usually this means the macro was only invoked conditionally.
```

**Comment by stweil** [comment]
That happens obviously for builds without `asciidoc`. Does commit d13e08bd85b1b7ef7cb3ac65515e7c489079ea7d in git master fix it for you? Maybe you have to run `./autogen.sh` first.

**Comment by nnnikolay** [comment]
right after you fixed the [issue](https://github.com/tesseract-ocr/tesseract/commit/421ebf0418f415c2ca270521243d4edc36dd44bf) (big thank you!) I've done

```
make clean
./autogen.sh
./configure
make -j
make training
sudo make training-install
```

and on the configuring step, I've got the message what you see above.

However, this [commit](https://github.com/tesseract-ocr/tesseract/commit/d13e08bd85b1b7ef7cb3ac65515e7c489079ea7d) fixes it all.

Thank you.

**Comment by stweil** [comment]
You can simplify `make -j; make training` by just `make training -j`.

**Pull request merged**
