### PR TITLE
Add initial support for Intel AVX512F

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This implementation improves the performance for recognition with best models and for training. `intsimdmatrixavx512.cpp` for fast models is still to be implemented.

**Comment by zdenop** [comment]
thanks!

**Comment by wollmers** [comment]
@stweil Just for interest: Can you give a rough measure of of throughput increase (or runtime decrease) in % of a complete run compared to AVX2 (or no SIMD)? Just to get a feeling for the magnitude.

**Comment by stweil** [comment]
I still only have numbers for my standard testcase `lstm_squashed_test`. For that test which only partially uses the float dotproduct the execution time is reduced by about 10 %. But the performance also seems to depend on other factors. For example the test runs slower directly after a build process which exercised all CPU cores, so maybe the Intel Core i3 CPU uses a higher clock rate for the single threaded test as long as the CPU temperature is within some limit.

The throughput is still much better on Apple M1.

**Comment by Matthew-Bradley** [comment]
> The throughput is still much better on Apple M1.

What acceleration, if any, is being used on the M1?

**Comment by stweil** [comment]
M1 currently uses Neon (like other ARM64 platforms, too).

**Comment by amitdo** [comment]
This PR was referenced here:

https://www.phoronix.com/scan.php?page=news_item&px=Tesseract-OCR-5.2-Released

**Comment by amitdo** [comment]
You didn't mentioned the model/spec of the AVX512 machine and the AVX2 machine.

**Comment by amitdo** [comment]
Another thing, did you try to do loop unrolling like is done in AVX2?

**Comment by stweil** [comment]
No, the current code does not do loop unrolling. Nor does AVX code for float do that.

**Pull request merged**
