### PR TITLE
configure: Enclose most macro arguments in []

### PR DESCRIPTION
**Pull request by stweil**
This is not strictly necessary, but recommended in the GNU autoconf manual.
No [] was added to arguments like true or false.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This PR addresses issue #100.

**Comment by amitdo** [comment]
Hi Stefan!

You missed `AC_PREREQ`.
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Versioning.html

**Comment by stweil** [comment]
Thanks, I added that one now, too.

**Comment by amitdo** [comment]
Thanks!

**Comment by elfring** [comment]
Thanks for [your improvement of a build configuration script](https://github.com/tesseract-ocr/tesseract/commit/4cbe9622d14572a460d27f5b1dbbce53d2e267fe "More quoting for macro parameters").

**Pull request merged**
