### PR TITLE
Fix some warnings from static code analyzer LGTM

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
@zdenop, do you want to add LGTM to the CI tests?
See https://lgtm.com/projects/g/tesseract-ocr/tesseract/ci/.

**Comment by zdenop** [comment]
Thanks - I activated it.

**Comment by amitdo** [comment]
Alerts: 
78 -> 45
 https://lgtm.com/projects/g/tesseract-ocr/tesseract/alerts?mode=list

Code quality:
A -> A+
https://lgtm.com/projects/g/tesseract-ocr/tesseract/context:cpp

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/c003a6041093117ac749b07004313e0689800776

**Comment by zdenop** [comment]
It was removed from code as outdated, by lgtm did not recognize it yet ;-)

**Pull request merged**
