### PR TITLE
Fix check for images which are too small to scale

### PR DESCRIPTION
**Pull request by stweil**
Images with width == min_width are not too small.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@Shreeshrii, this also affects the results of the UNLV tests. The results now look more consistent, but the recognition rates are slightly worse. This is caused by images with vertical lines. Tesseract fails to remove them, so they are often "detected" as a `|` character. With this pull requests some more are detected like that.

Example:

    --- unlvtests/old/doe3.3B/5373_008.3B.unlv       2019-02-14 17:25:52.783598953 +0100
    +++ unlvtests/new/doe3.3B/5373_008.3B.unlv       2019-02-15 10:52:56.196964557 +0100
    @@ -4,9 +4,9 @@
     Year| Date | Time i Locali Given| N. : Ww. 5 ,ghrea | Hlaximum | Ded i
     | te | pst. cality Mag. | Lat. Long. | oar | fensity wie D. Db:
     | |S -_ | ro
    -1906 | 04-18 | 05: 12.0 NW of San Francisco 8.3 138 | 123 ~; 375,000 | XT. 17.8 | 0.8 | 0.25
    +1906 | 04-18 | 05: 12.0 | NW of San Francisco 8.3 138 | 123 ~; 375,000 | XT. 17.8 | 0.8 | 0.25
     1915 10-02 | 22:52.8 Pleasant Valley, Nev. 7.6 40.5 | 117.85 500,000 | XN. | 7.5 OL | OOL
    -1927 | 09-17 | 18:07:07 | Near Bishop 6.0 | 37.5 | 118.75 | 75,000 | VII. P.$ 10.4 | 0.16
    +1927 | 09-17 | 18:07:07 | Near Bishop | 6.0 | 37.5 | 118.75 | 75,000 | VII. P.$ 10.4 | 0.16
     1930 | 01-15 | 16:24 | Fawnskin and Summit 5.2 | 34.2 | 116.9 50,000 | VII. 6.1 i-0.9: 0.81
     1930 | 02-25 | 18:30 | Imperial Valley | 5.0 | 33 | 115.5 | 20,000 | VIII. | 5.6 |~0.6 | 0.36
     1930 | 03-01 | 15:44 | Imperial Valley 4.5 | 33 115.5 | 11,000 | VIII. | 5.2 1-0.7 | 0.49

**Comment by amitdo** [comment]
Could you attach the image?

**Comment by Shreeshrii** [comment]
[5373_008.3B.zip](https://github.com/tesseract-ocr/tesseract/files/2871531/5373_008.3B.zip)

**Comment by Shreeshrii** [comment]
@stweil What's the difference between .unlv output and .txt output from tesseract?

**Pull request merged**
