### PR TITLE
tesseractmain.cpp: Split huge main() to sub functions.

### PR DESCRIPTION
**Pull request by amitdo**

### CODE REVIEW

**Comment by amitdo** [comment]
@zdenop, FYI

Travis failed in linux build only. It had problems downloading cmake.
The code does compile in my machine, which is ubuntu 14.04 64bit.
I also tested the code. Everything seems fine!

Any questions?

**Comment by ArjanSchouten** [comment]
If I'm right the build will run again when you close this PR and reopen it.

**Comment by amitdo** [comment]
Thanks.
It failed twice to download cmake: yesterday (~18 hours ago) and today (~2 hours ago).
So it might failed again...

**Comment by amitdo** [comment]
@zdenop
I reorganised this PR. It has only one commit now.

**Comment by stweil** [comment]
The Travis problem should be fixed now (see #143), so please start a new try.

**Comment by amitdo** [comment]
@stweil, @zdenop
Done.

**Comment by amitdo** [comment]
@zdenop Please, commit or comment.

**Comment by stweil** [comment]
@amitdo, I'm afraid that your patch needs to be rebased on latest git master. One of my patches fixed a bug in main and was committed. This fix is still missing in your code, so there will be a merge conflict.

**Comment by zdenop** [comment]
@amitdo: I prefer to see whole help as default (as today) when I run "tesseract" or "tesseract -- help".
I am fine if there is '--help-psm', but at the moment the whole help is not very long so we do not need to remove part of it...

**Comment by amitdo** [comment]
@zdenop, I've update the code. Is it OK for you now?

**Comment by stweil** [comment]
@amitdo, I'afraid that the new function SetVariablesFromCLArgs did revert the bug fix #154.

**Comment by amitdo** [comment]
@stweil, sorry. fixed.

**Comment by zdenop** [comment]
@amitdo: No it is not (at least for me). I wrote: I prefer to see whole help as default (as today) when I run "tesseract" or "tesseract -- help".

**Comment by amitdo** [comment]
If you run "tesseract" or "tesseract -- help" you get this.
```
Usage:
  tesseract --help | --help-psm | --version
  tesseract --list-langs [--tessdata-dir PATH]
  tesseract --print-parameters [options...] [configfile...]
  tesseract imagename|stdin outputbase|stdout [options...] [configfile...]


Options:
  -h, --help	Show this help message.
  --help-psm	Show Page Segmentation Modes.
  -v,  --version	Show version information.

  --list-langs	list available languages for tesseract engine.

  --tessdata-dir PATH	specify the location of tessdata path.
  --print-parameters	print tesseract parameters to the stdout.
  --user-words PATH	specify the location of user words file.
  --user-patterns PATH	specify the location of user patterns file.
  -l LANG[+LANG]	specify language(s) used for OCR.
  -c VAR=VALUE	set value for config variables.
			Multiple -c arguments are allowed.
  -psm NUM	specify page segmentation mode.
  NOTE: The options above must occur before any configfile.

Page Segmentation Modes:
  0    Orientation and script detection (OSD) only.
  1    Automatic page segmentation with OSD.
  2    Automatic page segmentation, but no OSD, or OCR
  3    Fully automatic page segmentation, but no OSD. (Default)
  4    Assume a single column of text of variable sizes.
  5    Assume a single uniform block of vertically aligned text.
  6    Assume a single uniform block of text.
  7    Treat the image as a single text line.
  8    Treat the image as a single word.
  9    Treat the image as a single word in a circle.
 10    Treat the image as a single character.
```



So, what do you mean by 'whole help'?

'as default (as today)' - does it mean you want the help message to look like exactly as it looks now?  

Please clarify.

**Comment by zdenop** [comment]
@amitdo: I will recheck it - I got different out when I wrote my comment.

**Comment by zdenop** [comment]
@amitdo: I did clean fetch of pullrequest and I got the output as you presented. Thanks.

**Pull request merged**
