### PR TITLE
 Improve man page for tesseract  and add Makefile rule for PDF

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by Shreeshrii** [comment]
Please also check for new info in --help-extra.

You can add the new psms.

```
 11    Sparse text. Find as much text as possible in no particular order.
 12    Sparse text with OSD.
 13    Raw line. Treat the image as a single text line,
       bypassing hacks that are Tesseract-specific.
```

**Comment by stweil** [comment]
`--dpi N` is also still missing.

**Comment by Shreeshrii** [comment]
You can also consider whether some of the info in the following pages also needs to be added to `man` page.

https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage
https://github.com/tesseract-ocr/tesseract/wiki/FAQ

Examples of what could be added (IMO)...

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#what-page-separators-are-used-in-txt-output-by-tesseract-4-0-0

Info about pdf with text layer only

https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#integrate-original-image-file-and-detected-text-into-pdf

https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#ocr-single-page-of-a-multi-page-tiff

**Comment by Shreeshrii** [comment]
2 = Tesseract + LSTM.

How about adding that this is only available in the traineddata files from tessdata repo - though not all of them.

**Comment by stweil** [comment]
I added two commits for the missing `--psm` and `--dpi` options. See [old](https://digi.bib.uni-mannheim.de/tesseract/manuals/tesseract.1.html) and [new](https://digi.bib.uni-mannheim.de/tesseract/manuals/tesseract.new.html) man pages.

**Comment by stweil** [comment]
@Shreeshrii, thank you for your suggestions. I am currently a little bit short of time, as I am just preparing a [Tesseract workshop](https://www.professionalabstracts.com/bid2019/programme-bid2019.pdf) for next Monday.

**Comment by Shreeshrii** [comment]
>See old and new man pages.

The new format looks better. Thank you.

You could move the following lower on the page:

```
--user-words FILE
Specify the location of user words file.

--user-patterns FILE
Specify the location of user patterns file.
```

**Comment by stweil** [comment]
Those options are now sorted alphabetically.

**Comment by Shreeshrii** [comment]
>> I am just preparing a Tesseract workshop for next Monday.

@stweil 👍

**Pull request merged**
