### PR TITLE
Remove old code for string class (no longer needed)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Please wait with merging ... more changes are needed.

**Comment by stweil** [comment]
@jbreiden, I am not sure whether [your comment](https://github.com/tesseract-ocr/tesseract/issues/1045#issuecomment-368153043) also covers the code changes which I‌ present here. And what about the definition for `DISABLE_HEAP_LEAK_CHECK` in [training/util.h](https://github.com/tesseract-ocr/tesseract/blob/master/training/util.h#L59)? If that is no longer needed at Google, we could remove `USE_STD_NAMESPACE` completely (and `DISABLE_HEAP_LEAK_CHECK` as well).

**Comment by jbreiden** [comment]
@stweil I have not tested the heap check stuff. Suggest leaving it unless I can confirm. However, I think it is fair to switch the ifdef to make Google use an oddball build rather than the rest of the world.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/search?utf8=%E2%9C%93&q=%22%23ifdef+GOOGLE%22

https://gperftools.github.io/gperftools/heap_checker.html

**Comment by stweil** [comment]
Thank you. I now use `GOOGLE_TESSERACT` in pull request #1360.

**Pull request merged**
