### PR TITLE
Remove unused config variable tessedit_single_match

### PR DESCRIPTION
**Pull request by stweil**
Replace also TRUE, FALSE by true, false.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This is an API change, but I think it is uncritical because the config variable was unused.

**Comment by zdenop** [comment]
Thanks

**Comment by stweil** [comment]
@egorpugin, Appveyor CI is currently broken. Do you have an idea how to fix that?

**Comment by stweil** [comment]
@zdenop, there is another config variable `tessedit_module_name` which was added in commit 4523ce9f7d9a46faff9e8bca5432293bdd3a968b (only for Windows) but is unused in the Tesseract code.

Can it be removed, too? Then we could also get rid of the macro `WINDLLNAME`.

**Comment by zdenop** [comment]
yes, remove it.

**Comment by stweil** [comment]
Removed in commits 77a5f2623ebf9b0a3df51838c07ec1a3d9de42a9 and ab009fae9436bb41723a5a34d3fcb5b5b3aa708a.

**Comment by egorpugin** [comment]
Yes, I'm working on some sw updates, so build is unstable.
(I've did some fixes, one build was green, then I made more changes and it's broken again.) :)

**Pull request merged**
