### PR TITLE
Compile with musl libc

### PR DESCRIPTION
**Pull request by doughdemon**
Fix compilation on linux with musl libc library (http://musl-libc.org).

### CODE REVIEW

**Comment by wiiaboo** [comment]
This seems to break mingw building:
```
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../vs2010/port -DWINDLLNAME=\"libtesseract\" -I/local32/include -D__USE_MINGW_ANSI_STDIO=1 -I/local32/include/leptonica -mms-bitfields -IK:/Mingw642/local32/include -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include/cairo -IK:/Mingw642/msys64/mingw32/include/glib-2.0 -IK:/Mingw642/msys64/mingw32/lib/glib-2.0/include -IK:/Mingw642/msys64/mingw32/include/pixman-1 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -m32 -I/local32/include -mthreads -mtune=generic -O2 -pipe -std=c++11 -MT tessdatamanager.lo -MD -MP -MF .deps/tessdatamanager.Tpo -c tessdatamanager.cpp -o tessdatamanager.o
scanutils.cpp:42:14: error: conflicting declaration 'typedef long int off_t'
typedef long off_t;
^
In file included from K:/Mingw642/msys64/mingw32/i686-w64-mingw32/include/stdio.h:80:0,
from scanutils.cpp:32:
K:/Mingw642/msys64/mingw32/i686-w64-mingw32/include/_mingw_off_t.h:24:17: note: previous declaration as 'typedef off64_t off_t'
typedef off64_t off_t;
^
Makefile:579: recipe for target 'scanutils.lo' failed
make[3]: *** [scanutils.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../vs2010/port -DWINDLLNAME=\"libtesseract\" -I/local32/include -D__USE_MINGW_ANSI_STDIO=1 -I/local32/include/leptonica -mms-bitfields -IK:/Mingw642/local32/include -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -IK:/Mingw642/local32/include/freetype2 -IK:/Mingw642/msys64/mingw32/include/cairo -IK:/Mingw642/msys64/mingw32/include/glib-2.0 -IK:/Mingw642/msys64/mingw32/lib/glib-2.0/include -IK:/Mingw642/msys64/mingw32/include/pixman-1 -IK:/Mingw642/msys64/mingw32/include -IK:/Mingw642/msys64/mingw32/include/libpng16 -m32 -I/local32/include -mthreads -mtune=generic -O2 -pipe -std=c++11 -MT tprintf.lo -MD -MP -MF .deps/tprintf.Tpo -c tprintf.cpp -o tprintf.o
make[3]: Leaving directory '/build/tesseract-git/ccutil'
Makefile:621: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/build/tesseract-git/ccutil'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git'
Makefile:387: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by doughdemon** [comment]
For some reason the configure test has not detected that mingw has
off_t (but later on it is declared after all). You are using cmake? It
should have some *.log files indicating why off_t was not found in the
configure step.

**Comment by wiiaboo** [comment]
No, I'm using autotools. Lots of options missing from cmake, so I prefer the former.

**Comment by doughdemon** [comment]
Ricardo Constantino wrote:
> No, I'm using autotools. Lots of options missing from cmake, so I prefer the former.

Good. So could you look in config.log for the test for "off_t"? (It
would be interesting to compare the compilation options and to see the
compiler error message.)

**Comment by wiiaboo** [comment]
I edited the previous comment with the config.log.

**Comment by wiiaboo** [comment]
Here's the [config.log](http://j.fsbn.eu/zmM9.txt)

**Comment by doughdemon** [comment]
Ricardo Constantino wrote:
> Here's the [config.log](http://j.fsbn.eu/zmM9.txt)

It seems that off_t is detected after all. Try building after rerunning
./autogen.sh

**Comment by wiiaboo** [comment]
Yeah, seems running autogen.sh fixed it. I thought configure would force it for some reason, nevermind then.

**Pull request merged**
