### PR TITLE
Fix some typos (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by jbreiden** [comment]
Please slow down on the typo stuff for a bit while we  try to merge changes
between 3.x and 4.x.

**Comment by stweil** [comment]
Which changes are you referring to? Those from the 3.04 branch? As far as I can see, there is only commit 56c1a4a21fbfc0380d9ae4e78435842a7af61829 missing in master, and two small updates in `vs2010/`. If you want, I can send a pull request for the merge.

**Comment by amitdo** [comment]
They want to merge google private new LSTM codebase with the public github repo.

**Comment by stweil** [comment]
Are you sure? I assume that the LSTM codebase is also based on some release from the official Tesseract on GitHub. Then merging should not be too complicated. It would be rather straight forward if that code were a branch of the GitHub repository.

**Comment by amitdo** [comment]
>Are you sure?
Well, It quite obvious (to me at least) from reading his comment.

>It would be rather straight forward if that code were a branch of the GitHub repository.
It might be an old branch (3.03?)

**Comment by jbreiden** [comment]
Without going into the gory details, Amitdo is basically correct. There are about 10K lines of code being synchronized today with manual review. It's not a strict requirement to pause non-critical development activity (like fixing typos in comments). But it helps a little.

**Comment by stweil** [comment]
@jbreiden, my main focus is currently the OpenCL part – hopefully this does not interfere with the new code. Please tell us if you need more help with the merge or testing of the new code (like porting to Windows, for example).

**Comment by mindis** [comment]
Hi, what is expected release date of 4.0?

**Comment by amitdo** [comment]
The eagle has landed...

**Comment by stweil** [comment]
I rebased the PR, fixed the merge conflict and added another commit for some new typos.

**Pull request merged**
