### PR TITLE
Make font size estimation work with the lstm engine

### PR DESCRIPTION
**Pull request by amitdo**
**Partial** fix for issue #1074

### CODE REVIEW

**Comment by engycz** [comment]
This fix broke openalpr. See https://github.com/tesseract-ocr/tesseract/issues/1665 and https://github.com/openalpr/openalpr/issues/692

**Comment by amitdo** [comment]
Please send a PR.

**Comment by engycz** [comment]
Sorry, I don't know how to fix it.

**Comment by amitdo** [comment]
#1669 should fix the issue reported by @engycz.

**Pull request merged**
