### PR TITLE
Solve clang reporting unused variable in  ExtractMicros function

### PR DESCRIPTION
**Pull request by zdenop**
```
..\src\classify\mf.cpp(47,14): warning: unused variable 'f' [-Wunused-variable]
  for (auto &f : features) {
             ^
```

### CODE REVIEW

**Comment by zdenop** [comment]
I do not understand why there are 4 commits instead of one...

**Comment by zdenop** [comment]
so msvc does not understand it...

**Comment by stweil** [comment]
> I do not understand why there are 4 commits instead of one...

I squashed them for the merge, so now it's only a single commit.

**Comment by zdenop** [comment]
thanks

**Pull request merged**
