### PR TITLE
Improve help text for OCR engine mode

### PR DESCRIPTION
**Pull request by stweil**
The new text was suggested by Amit Dovev, see
https://github.com/tesseract-ocr/tesseract/pull/1325#issuecomment-366613553.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by amitdo** [comment]
If you mention me in the commit, I prefer that you'll use my user name

**Comment by amitdo** [comment]
Next time...

**Comment by stweil** [comment]
@amitdo, sorry, I had looked at your previous commits. Next time I'll know - @zdenop is simply too fast for us. :-)

**Comment by amitdo** [comment]
Stefan, :-)

In regular comments it's fine to use 'Amit' if you want...

**Pull request merged**
