### PR TITLE
OpenCL: Remove PERF_COUNT framework

### PR DESCRIPTION
**Pull request by stweil**
It was rarely used, but added a lot of code and an unconditional
dependency on openclwrapper.h.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by amitdo** [comment]
Why we still keep the OpenCL code (~4000 LOC) ?

**Comment by stweil** [comment]
Maybe because I am just evaluating it with even more lines of code for LSTM?

**Comment by amitdo** [comment]
Ok.

**Comment by amitdo** [comment]
Did you hear about SYCL?
https://en.wikipedia.org/wiki/SYCL

**Comment by stweil** [comment]
No, I did not up to now. Thank you for the hint.

**Pull request merged**
