### PR TITLE
Remove NEWS stub file

### PR DESCRIPTION
**Pull request by stweil**
It was created more than 10 years ago, never changed and never used.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by zdenop** [comment]
AFAIR NEWS file is required when you create distribution package by autotools...

**Comment by stweil** [comment]
Yes, normally it is needed like `README`, too. Tesseract [changed that](https://github.com/tesseract-ocr/tesseract/blob/master/configure.ac#L65), so neither `README` nor `NEWS` is needed here.

**Comment by stweil** [comment]
Me too. :-)

**Comment by amitdo** [comment]
http://norvig.com/21-days.html

**Comment by stweil** [comment]
@zdenop, I think this PR can be merged. Or would you suggest to remove more files (like AUTHORS or ChangeLog), too?

**Comment by amitdo** [comment]
>Or would you suggest to remove more files (like AUTHORS or ChangeLog), too?

Why do you want to remove `AUTHORS`?

**Comment by stweil** [comment]
I don't. AUTHORS, ChangeLog, NEWS and README are the files required for autoconf according to the GNU conventions. Tesseract does not have a README (it was replaced by README.md), and I want to remove NEWS.

**Comment by zdenop** [comment]
I will try to test this PR today evening or tomorrow ;-)

**Pull request merged**
