### PR TITLE
Add Google code for more unittests

### PR DESCRIPTION
**Pull request by stweil**
Some additional changes of the Tesseract code base make integration of the new tests easier.
As an example, bitvector_test and some more tests were now added to the Tesseract test set.

### CODE REVIEW

**Comment by Shreeshrii** [comment]
Welcome addition!!
Thank you @jbreiden  and @stweil .

**Comment by stweil** [comment]
Some of the new test files which are currently not activated use the Abseil API (https://abseil.io/, https://github.com/abseil/abseil-cpp). We have to decide whether we want to replace those calls, add a minimal implementation to Tesseract or require a full Abseil installation. These tests are affected:

    baseapi_test
    baseapi_thread_test
    fileio_test
    imagedata_test
    lang_model_test
    mastertrainer_test
    pango_font_info_test
    paragraphs_test
    stringrenderer_test
    unicharcompress_test

**Comment by stweil** [comment]
These tests neither depend on the Abseil API nor on unavailable TIFF images, so might be the next candidates to get fixed and added to our test set:

    commandlineflags_test
    dawg_test
    heap_test
    indexmapbidi_test
    intfeaturemap_test
    ligature_table_test
    linlsq_test
    lstm_recode_test
    lstm_squashed_test
    networkio_test
    normstrngs_test
    nthitem_test
    params_model_test
    qrsequence_test
    recodebeam_test
    rect_test
    scanutils_test
    shapetable_test
    stats_test
    stridemap_test
    tablefind_test
    tablerecog_test
    tabvector_test
    tatweel_test
    tfile_test
    unicharset_test
    unichar_test
    validate_grapheme_test
    validate_indic_test
    validate_khmer_test
    validate_myanmar_test
    validator_test

**Comment by Shreeshrii** [comment]
>a full Abseil installation (maybe as a Git submodule, about 10 MB).

> Abseil is an open-source collection of C++ code (compliant to C++11) designed to augment the C++ standard library.

We are already using Googletest and test (testdata) as submodules that are required only for testing, so I think it will be OK to add Abseil as a submodule too.

**Comment by amitdo** [comment]
>qrsequence_test – needs unknown data type CycleTimer

It is mentioned here:

https://github.com/abseil/abseil-cpp/blob/87a4c07856e7dc69958019d47b2f02ae47746ec0/absl/base/internal/unscaledcycleclock.h

Also check
https://www.google.com/search?q=%22CycleTimer%22+%22google%22+%22apache%22+%22github%22

**Comment by amitdo** [comment]
Try to extract a `eng.traindata` file that contains the data for the legacy engine.
`eng.params_model` should be there.

https://github.com/tesseract-ocr/tesseract/blob/5fdaa479da2c/doc/combine_tessdata.1.asc

**Comment by amitdo** [comment]
>needs unknown data type Array2D (class?)

Try to replace with GENERIC_2D_ARRAY

**Comment by amitdo** [comment]
https://www.google.com/search?q=%22StringPrintf%22+%22google%22+%22apache%22

**Comment by amitdo** [comment]
https://www.google.com/search?q=%22subprocess.h%22+%22google%22+%22apache%22

**Comment by amitdo** [comment]
>qrsequence_test – needs unknown data type CycleTimer

It is mentioned here:

https://github.com/abseil/abseil-cpp/blob/87a4c07856e7dc69958019d47b2f02ae47746ec0/absl/base/internal/unscaledcycleclock.h

Also check
https://www.google.com/search?q=%22CycleTimer%22+%22google%22+%22apache%22+%22github%22

>params_model_test – needs file eng.params_model

Try to extract a eng.traindata file that contains the data for the legacy engine.
eng.params_model should be there.

https://github.com/tesseract-ocr/tesseract/blob/5fdaa479da2c/doc/combine_tessdata.1.asc

>needs unknown data type Array2D (class?)

Try to replace with GENERIC_2D_ARRAY

>shapetable_test – needs unknown function StringPrintf

https://www.google.com/search?q=%22StringPrintf%22+%22google%22+%22apache%22

>tatweel_test – needs util/utf8/public/unicodetext.h

https://github.com/tensorflow/models/search?q=%22unicodetext.h%22

>dawg_test – needs util/process/subprocess.h

https://www.google.com/search?q=%22subprocess.h%22+%22google%22+%22apache%22

**Comment by stweil** [comment]
I'm just preparing the `baseapi_test`. It is the first test case which uses the Abseil API, and it also needs CycleTimer and LOG(). I am still struggling with the integration of Abseil into the build process, but hopefully will have finished that soon. Then adding more tests with similar requirements should be possible.

**Comment by jbreiden** [comment]
`absl::StrFormat` is the replacement for `StringPrintf`.  Tests should work with the `LOG` lines removed, but the logging library is probably https://github.com/google/glog

**Comment by stweil** [comment]
Latest Tesseract has now 40 unit tests (with lots of subtests) which pass successfully:

    ============================================================================
    Testsuite summary for tesseract 4.0.0-239-g7d39d
    ============================================================================
    # TOTAL: 40
    # PASS:  40
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  0
    # XPASS: 0
    # ERROR: 0

**Pull request merged**
