### PR TITLE
Add new option -l for combine_tessdata to list LSTM information

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This is a first step to show the same information as Ray had produced in https://github.com/tesseract-ocr/tesseract/issues/1404#issuecomment-374680492.

**Comment by Shreeshrii** [comment]
Thank you, @stweil. This is very useful.

```
(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata_best/eng.traineddata
LSTM: network=[1,36,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1], int_mode=0, recoding=1, iteration=814100, sample_iteration=814136, null_char=110, learning_rate=0.001, momentum=0.5, adam_beta=0.999

(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata/eng.traineddata
LSTM: network=[1,36,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1], int_mode=1, recoding=1, iteration=814100, sample_iteration=814136, null_char=110, learning_rate=0.001, momentum=0.5, adam_beta=0.999

(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata_fast/eng.traineddata
LSTM: network=[1,36,0,1Ct3,3,16Mp3,3Lfys48Lfx96Lrx96Lfx192O1c1], int_mode=1, recoding=1, iteration=6352400, sample_iteration=6352704, null_char=110, learning_rate=0.001, momentum=0.5, adam_beta=0.999
```

Now the int_mode can also be queried for START_MODEL in lstmtraining to give a user friendly error message/

**Comment by Shreeshrii** [comment]
```
(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata_best/script/Devanagari.traineddata
LSTM: network=[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx64Lrx64Lfx512O1c1], int_mode=0, recoding=1, iteration=2475100, sample_iteration=2475272, null_char=2, learning_rate=0.001, momentum=0.5, adam_beta=0.999

(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata_best/San20201216.traineddata
LSTM: network=[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx192 O1c285], int_mode=0, recoding=1, iteration=1579800, sample_iteration=1584900, null_char=285, learning_rate=0.002, momentum=0.5, adam_beta=0.999

(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l ~/tessdata_best/Sanskrit20201231.traineddata
LSTM: network=[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx64Lrx64Lfx512O1c1], int_mode=0, recoding=1, iteration=3466500, sample_iteration=3466581, null_char=2, learning_rate=0.001, momentum=0.5, adam_beta=0.999

(base) ubuntu@tesseract-ocr-1:~/tesseract$ combine_tessdata -l /home/ubuntu/tesstrain-San/data/SanLayer/tessdata_best/SanLayer_0.686_354028_1278900.traineddata
LSTM: network=[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx64Lrx64Lfx512O1c1][Lfx192O1c1], int_mode=0, recoding=1, iteration=1278900, sample_iteration=1278900, null_char=2, learning_rate=0.0001, momentum=0.5, adam_beta=0.999
```

**Comment by stweil** [comment]
Why has `San20201216.traineddata` a network string with blanks? And `SanLayer_0.686_354028_1278900.traineddata` also has an unusual network string. How did you get those?

**Comment by stweil** [comment]
> Now the int_mode can also be queried for START_MODEL in lstmtraining to give a user friendly error message/

That should be implemented in `lstmtraining` (which can also query `int_mode`).

**Comment by Shreeshrii** [comment]
>Should I merge this pull request, or should I wait for more feedback?

Please merge. Thank you.

**Pull request merged**
