### PR TITLE
Fix header file guards and replace reserved identifiers

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This also fixes issue #96.

**Comment by egorpugin** [comment]
What about moving to `#pragma once`?

**Comment by amitdo** [comment]
>What about moving to #pragma once?

https://google.github.io/styleguide/cppguide.html

>Do not use #pragma once; instead use the standard Google include guards. The path in the include guards should be relative to the top of your project tree.

**Comment by egorpugin** [comment]
Ah,ok. No objections in this case.

**Comment by stweil** [comment]
`#pragma once` is widely supported, but not a standard, while the include guards using macros only use standard code. Modern compilers like gcc or clang know include guards, so for those compilers `#pragma once` has no performance advantage.

**Comment by egorpugin** [comment]
But less to write :)

**Comment by stweil** [comment]
True.

**Comment by stweil** [comment]
@zdenop, I think this PR is ready to get merged. Issue #96 can be closed then.

**Pull request merged**
