### PR TITLE
Add test code for fuzzing

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
This adds the fuzzing code from https://github.com/guidovranken/tesseract-ocr-fuzzers/ to the Tesseract code base. I formatted the new code according to the Tesseract conventions and changed it to support `TESSDATA_PREFIX`.

**Comment by stweil** [comment]
See also the new [build instructions](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation#builds-for-fuzzing) in the Wiki.

**Comment by Shreeshrii** [comment]
Thanks @stweil 

Trying the build on Linux tesseract-ocr 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:40 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
with clang-8.0

```
make[3]: Entering directory '/home/ubuntu/tesseract/bin/fuzzer/src/arch'
/bin/bash ../../libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I. -I../../../../src/arch -I../..  -DNDEBUG -I../../../../src/ccstruct -I../../../../src/ccutil -I../../../../src/viewer  -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -std=c++14 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c -o libtesseract_avx_la-dotproductavx.lo `test -f 'dotproductavx.cpp' || echo '../../../../src/arch/'`dotproductavx.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../../../../src/arch -I../.. -DNDEBUG -I../../../../src/ccstruct -I../../../../src/ccutil -I../../../../src/viewer -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -std=c++14 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c ../../../../src/arch/dotproductavx.cpp -o libtesseract_avx_la-dotproductavx.o
clang-8: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
../../../../src/arch/dotproductavx.cpp:20:2: error: Implementation only for AVX capable architectures
#error Implementation only for AVX capable architectures
 ^
In file included from ../../../../src/arch/dotproductavx.cpp:23:
In file included from /usr/local/clang_8.0.0/lib/clang/8.0.0/include/immintrin.h:28:
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:47:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:47:5: note: '__builtin_isless' declared here
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:47:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:64:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:81:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:143:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/usr/local/clang_8.0.0/lib/clang/8.0.0/include/mmintrin.h:173:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
```

**Comment by stweil** [comment]
That's a build for PowerPC which should not use AVX. Did configure say that the compiler supports SSE / AVX / AVX2?

**Comment by Shreeshrii** [comment]
```
	Line 251: checking whether C++ compiler accepts -mavx... yes
	Line 252: checking whether C++ compiler accepts -mavx2... yes
	Line 434: /bin/bash ../../libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I. -I../../../../src/arch -I../..  -DNDEBUG -I../../../../src/ccstruct -I../../../../src/ccutil -I../../../../src/viewer  -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -std=c++14 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c -o libtesseract_avx_la-dotproductavx.lo `test -f 'dotproductavx.cpp' || echo '../../../../src/arch/'`dotproductavx.cpp
	Line 435: libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../../../../src/arch -I../.. -DNDEBUG -I../../../../src/ccstruct -I../../../../src/ccutil -I../../../../src/viewer -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -std=c++14 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c ../../../../src/arch/dotproductavx.cpp -o libtesseract_avx_la-dotproductavx.o
	Line 436: clang-8: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
	Line 437: ../../../../src/arch/dotproductavx.cpp:20:2: error: Implementation only for AVX capable architectures
	Line 438: #error Implementation only for AVX capable architectures
	Line 440: In file included from ../../../../src/arch/dotproductavx.cpp:23:
	Line 499: Makefile:593: recipe for target 'libtesseract_avx_la-dotproductavx.lo' failed
	Line 500: make[3]: *** [libtesseract_avx_la-dotproductavx.lo] Error 1
```

**Comment by Shreeshrii** [comment]
```
configure:4100: checking host system type
configure:4113: result: powerpc64le-unknown-linux-gnu
configure:4249: checking whether C++ compiler accepts -mavx
configure:4268: clang++ -c -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined  -mavx  conftest.cpp >&5
clang-8: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
configure:4268: $? = 0
configure:4276: result: yes
configure:4295: checking whether C++ compiler accepts -mavx2
configure:4314: clang++ -c -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined  -mavx2  conftest.cpp >&5
clang-8: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
configure:4314: $? = 0
configure:4322: result: yes
configure:4341: checking whether C++ compiler accepts -msse4.1
configure:4360: clang++ -c -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined  -msse4.1  conftest.cpp >&5
clang-8: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
configure:4360: $? = 0
configure:4368: result: yes
configure:4387: checking whether C++ compiler accepts -march=native
configure:4406: clang++ -c -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined  -march=native  conftest.cpp >&5
clang-8: warning: argument unused during compilation: '-march=native' [-Wunused-command-line-argument]
configure:4406: $? = 0
configure:4414: result: yes
```

**Comment by stweil** [comment]
So the PowerPC compiler accepts Intel options and warns that they ignored. configure only sees that those options are accepted and activates the Intel code which later fails.

Commit 4ccbb9f830e86f60d54b2e87c8936239b8ff8b91 tries to fix that. Please test with latest git code.

**Comment by Shreeshrii** [comment]
@stweil Thank you! It worked.

Getting a linker error now. 

```
 clang++ -v -g -O2 -Wall -Wextra -Wpedantic -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -std=c++14 -g -fsanitize=fuzzer \
>           -I ../../src/api \
>           -I ../../src/ccmain \
>           -I ../../src/ccstruct \
>           -I ../../src/ccutil \
>           -I src/api \
>           ../../unittest/fuzzers/fuzzer-api.cpp \
>           src/api/.libs/libtesseract.a -llept  -o fuzzer-api
clang version 8.0.0 (tags/RELEASE_800/final)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang_8.0.0/bin
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/local/clang_8.0.0/bin/clang-8" -cc1 -triple powerpc64le-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name fuzzer-api.cpp -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu ppc64le -mfloat-abi hard -target-abi elfv2 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -v -resource-dir /usr/local/clang_8.0.0/lib/clang/8.0.0 -D _GLIBCXX_DEBUG -I ../../src/api -I ../../src/ccmain -I ../../src/ccstruct -I ../../src/ccutil -I src/api -internal-isystem /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/c++/6.5.0 -internal-isystem /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/powerpc64le-linux-gnu/c++/6.5.0 -internal-isystem /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/powerpc64le-linux-gnu/c++/6.5.0 -internal-isystem /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/c++/6.5.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/local/clang_8.0.0/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/powerpc64le-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Wall -Wextra -Wpedantic -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /home/ubuntu/tesseract/bin/fuzzer -ferror-limit 19 -fmessage-length 197 -fsanitize-coverage-type=1 -fsanitize-coverage-type=3 -fsanitize-coverage-indirect-calls -fsanitize-coverage-trace-cmp -fsanitize-coverage-inline-8bit-counters -fsanitize-coverage-pc-table -fsanitize-coverage-stack-depth -fsanitize=address,fuzzer,fuzzer-no-link,alignment,array-bounds,bool,builtin,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize-recover=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,object-size,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,vla-bound,vptr -fsanitize-blacklist=/usr/local/clang_8.0.0/lib/clang/8.0.0/share/asan_blacklist.txt -fsanitize-address-use-after-scope -fno-assume-sane-operator-new -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/fuzzer-api-15e5ab.o -x c++ ../../unittest/fuzzers/fuzzer-api.cpp -faddrsig
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target powerpc64le-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/powerpc64le-linux-gnu/c++/6.5.0"
#include "..." search starts here:
#include <...> search starts here:
 ../../src/api
 ../../src/ccmain
 ../../src/ccstruct
 ../../src/ccutil
 src/api
 /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/c++/6.5.0
 /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/powerpc64le-linux-gnu/c++/6.5.0
 /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../../include/c++/6.5.0/backward
 /usr/local/include
 /usr/local/clang_8.0.0/lib/clang/8.0.0/include
 /usr/include/powerpc64le-linux-gnu
 /usr/include
End of search list.
 "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf64lppc -dynamic-linker /lib64/ld64.so.2 -o fuzzer-api /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../powerpc64le-linux-gnu/crt1.o /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../powerpc64le-linux-gnu/crti.o /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/crtbegin.o -L/usr/lib/gcc/powerpc64le-linux-gnu/6.5.0 -L/usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../powerpc64le-linux-gnu -L/lib/powerpc64le-linux-gnu -L/lib/../lib64 -L/usr/lib/powerpc64le-linux-gnu -L/usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../.. -L/usr/local/clang_8.0.0/bin/../lib -L/lib -L/usr/lib --whole-archive /usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.fuzzer-powerpc64le.a --no-whole-archive -lstdc++ --whole-archive /usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.asan-powerpc64le.a --no-whole-archive --dynamic-list=/usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.asan-powerpc64le.a.syms --whole-archive /usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.asan_cxx-powerpc64le.a --no-whole-archive --dynamic-list=/usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.asan_cxx-powerpc64le.a.syms /tmp/fuzzer-api-15e5ab.o src/api/.libs/libtesseract.a -llept -lstdc++ -lm --no-as-needed -lpthread -lrt -lm -ldl -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/crtend.o /usr/lib/gcc/powerpc64le-linux-gnu/6.5.0/../../../powerpc64le-linux-gnu/crtn.o
/usr/bin/ld: cannot find /usr/local/clang_8.0.0/lib/clang/8.0.0/lib/linux/libclang_rt.fuzzer-powerpc64le.a: No such file or directory
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
ubuntu@tesseract-ocr:~/tesseract/bin/fuzzer$

```

**Comment by Shreeshrii** [comment]
@stweil 

>A newer Clang++ compiler is required.

Will https://packages.ubuntu.com/search?keywords=clang-6.0 work?

I have used 8.00 from the following. Hope linker error is not because of that.

### https://solarianprogrammer.com/2017/12/13/linux-wsl-install-clang-libcpp-compile-cpp-17-programs/
curl -SL http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-powerpc64le-unknown-unknown.tar.xz | tar -xJC .
mv clang+llvm-8.0.0-powerpc64le-unknown-unknown clang_8.0.0
sudo mv clang_8.0.0 /usr/local
export PATH=/usr/local/clang_8.0.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/clang_8.0.0/lib:$LD_LIBRARY_PATH

**Comment by stweil** [comment]
I tested on x86_64 with Debian packages for clang 6, 8 and 9.
On PowerPC I only have a preinstalled clang version 3.4.2 which is too old.

**Comment by Shreeshrii** [comment]
I tested with both 6.0 and 8.00 on Power8. Looks like libclang_rt.fuzzer-powerpc64le.a is not included in either. So I won't be able to try out the fuzzer.

**Comment by guidovranken** [comment]
Once this is merged, I will update the [oss-fuzz build procedure](https://github.com/google/oss-fuzz/tree/master/projects/tesseract-ocr) to use the fuzzer code in the tesseract repository.

**Pull request merged**
