### PR TITLE
Add test cases

### PR DESCRIPTION
**Pull request by Shreeshrii**
Added test cases including one based on comment in issue 3312 (https://github.com/tesseract-ocr/tesseract/issues/3312#issuecomment-791792015)

### CODE REVIEW

**Review by egorpugin — CHANGES_REQUESTED** [review]
Still failing.

**Comment by Shreeshrii** [comment]
The issue regarding filenames was:

```
tesseract could not open unicode file name image.

tesseract "d:\test\2019 оны акт-page1.jpg" "d:\test\2019 оны акт-page1.txt" -l mon

TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0.20190623 with Leptonica Error, cannot read input file d:\test\2019 ??? ???-page1.jpg: Invalid argument Error during processing.')
```

Travis is able to process it but the filename seems to be dropping the utf8 characters.

**Comment by egorpugin** [comment]
Can you rename those files? It is known that leptonica has issues reading utf8 files (cannot read or smth).

**Comment by Shreeshrii** [comment]
Well, the test was to see if the utf-8 names work. 

Please see https://travis-ci.org/github/tesseract-ocr/tesseract/jobs/761930393#L1077

The file seems to have been read and OCRed but the name (at least as displayed in travis)  is dropping the utf8 characters.

@DanBloomberg Is the filename issue fixed in Leptonica 80.0?

**Comment by egorpugin** [comment]
> Well, the test was to see if the utf-8 names work.

We do not want to test utf8 names here.
If you want, just add them to normal test suite which is executed on github actions CI.
Just test other archs here without any tricky stuff.

**Comment by Shreeshrii** [comment]
ok

**Pull request closed without merging**
