### PR TITLE
Small improvements for documentation

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by amitdo** [comment]
You've missed this typo:

> Repository it huge

**Comment by stweil** [comment]
@amitdo: that was intentional, so more pull requests can follow.

No, I was just joking. I'm sure that there are more typos, but as I am not a native speaker,
I'm also sure that I won't find them all. :-)

**Comment by stweil** [comment]
Ah, on a 2nd view I now see the typo.

**Comment by amitdo** [comment]
> ..as I am not a native speaker

Me neither! :-)

**Pull request merged**
