### PR TITLE
Use default keyword instead of empty ctors/dtors.

### PR DESCRIPTION
**Pull request by ZaMaZaN4iK**
In C++11 was introduced default keyword. It's useful for declaring empty ctors/dtors. In this PR I have replaced empty ctors/dtors by default keyword.

### CODE REVIEW

**Comment by egorpugin** [comment]
@stweil @zdenop Any objections, comments?

**Comment by stweil** [comment]
Commit message: 
s/intoruced/introduced/
s/dtros/dtors/

@ZaMaZaN4iK, is it still possible to set a breakpoint on the default constructor in the debugger?

**Comment by ZaMaZaN4iK** [comment]
@stweil No, it is not. Because there is no place, where you can set breakpoint. I think it's not so useful with empty ctors/dtors, but if you want, for debugging you can replace default ctor/dtor with empty version, finish debug and revert changes.

**Comment by egorpugin** [comment]
> is it still possible to set a breakpoint on the default constructor in the debugger?

It's possible - 
image

**Comment by ZaMaZaN4iK** [comment]
@egorpugin Hm, didn't know that Qt Creator can do it. Thank you!

**Comment by stweil** [comment]
s/emty/empty/ in the commit message, but that's not a real objection. As breakpoints work, the code modifications are fine for me.

**Pull request merged**
