### PR TITLE
Fix Myanmar validation rules as per Unicode charts

### PR DESCRIPTION
**Pull request by Shreeshrii**
Fixes PR add missed letters ( ၌ ၍ ၎ ၏ ) and symbols ( ၊ ။ ) - 0x104a to 0x104f - #2070
Fixes issue unicharset_extractor not generating some characters for Burmese Language #2232

NOTE: Still testing, please DO NOT MERGE.

### CODE REVIEW

**Comment by zdenop** [comment]
Please do not make PR to official repository you do not want to merge. 
If you need playground, please create your own.

**Comment by amitdo** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

https://www.infoq.com/news/2019/02/github-draft-pull-requests

**Comment by Shreeshrii** [comment]
@amitdo Thank you for the info. That applies perfectly to this PR :-)

I have found that tesstrain.sh, specifically language_specific.sh does not setup the norm_mode correctly. Mainly for RTL languages.

I had opened issues with questions to Ray re this when first trying LSTM training but did not create a PR.

Please check the code and comments in unicode_extractor and combine_lang_model and let me know your feedback.

A similar change also maybe required for 'mya'. I will submit it for merging after that.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/src/training/unicharset_extractor.cpp#L103

https://github.com/tesseract-ocr/tesseract/blob/master/src/training/language-specific.sh#L1181

**Comment by Shreeshrii** [comment]
@amitdo (I am testing norm_mode 3 for mya also, similar to Thai ?)

  case "${LANG_CODE}" in
    ara | div| fas | pus | snd | syr | uig | urd | kur_ara | heb | yid )
      LANG_IS_RTL="1"
      NORM_MODE="3" ;;
    bod | tha | mya)
      LANG_IS_RTL="0"
      NORM_MODE="3" ;;
    asm | ben | bih | hin | mar | nep | guj | kan | mal | tam | tel | pan | \
    dzo | sin | san | ori | khm | lao | jav  | jav_java )
      LANG_IS_RTL="0"
      NORM_MODE="2" ;;
    * )
      LANG_IS_RTL="0"
      NORM_MODE="1" ;;
  esac

**Comment by Shreeshrii** [comment]
@amitdo See my original comment for 
https://github.com/tesseract-ocr/tesseract/commit/a912967cc3e98e7aafe380dc15b24d825766cd33

Do we know if tesstrain.sh is used at Google?

**Comment by amitdo** [comment]
>Do we know if tesstrain.sh is used at Google?

I don't think that they use this script. I believe they have something similar, that also distribute the training to multi-machines in their network.

**Comment by Shreeshrii** [comment]
@zdenop This PR can be merged now. Please see https://github.com/tesseract-ocr/tesseract/issues/2232#issuecomment-467931003 

> Yes, I tested codes from PR #2244 just a few hours ago. It seems to be working, although I haven't run it on large training texts. I will let you know again.

**Pull request merged**
