### PR TITLE
automake: Flat build for src/training

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
The flat build allows massive parallel builds, reducing the time for `make training -j64` to about 10 s.

**Comment by stweil** [comment]
Note that the training tools are now built in the build root directory (not in `src/training`).

**Comment by Shreeshrii** [comment]
Will they be built by running make alone or will it still be a two step
process of make and make training?

**Comment by stweil** [comment]
`make training` also builds the `tesseract` executable – like before.
`make` or `make all` does not build the training tools – like before.

**Pull request merged**
