### PR TITLE
Rename function to TessBaseAPIGetTsvText to be consistent to Create method

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by zdenop** [comment]
Why? [TSV](https://en.wikipedia.org/wiki/Tab-separated_values) is equivalent for CSV. Also C++ method use TSV.  I never see Csv or Tsv. Search for TSV file...

**Comment by Shreeshrii** [comment]
Tsv is being used within tesseract already.

https://github.com/tesseract-ocr/tesseract/blob/master/src/api/renderer.cpp#L145

```
TessTsvRenderer::TessTsvRenderer(const char* outputbase)
    : TessResultRenderer(outputbase, "tsv") {
  font_info_ = false;
}

TessTsvRenderer::TessTsvRenderer(const char* outputbase, bool font_info)
    : TessResultRenderer(outputbase, "tsv") {
  font_info_ = font_info;
}

bool TessTsvRenderer::BeginDocumentHandler() {
  // Output TSV column headings
  AppendString(
      "level\tpage_num\tblock_num\tpar_num\tline_num\tword_"
      "num\tleft\ttop\twidth\theight\tconf\ttext\n");
  return true;
}

bool TessTsvRenderer::EndDocumentHandler() { return true; }

bool TessTsvRenderer::AddImageHandler(TessBaseAPI* api) {
  const std::unique_ptr<const char[]> tsv(api->GetTSVText(imagenum()));
  if (tsv == nullptr) return false;

  AppendString(tsv.get());

  return true;
}```

**Comment by zdenop** [comment]
it is ok to have variable lower case (tsv). IMO `Tsv` should be corrected to `TSV`.

**Comment by amitdo** [comment]
Correcting the name in the C++ code will break the API.

**Comment by Shreeshrii** [comment]
My change was only for my earlier commit for C-API.

**Comment by amitdo** [comment]
Yes Shree, I know.

My comment was directed to Zdenko.

**Comment by zdenop** [comment]
@amitdo: We already [modified API](https://abi-laboratory.pro/index.php?view=objects_report&l=tesseract&v1=4.0.0&v2=current)
I really wonder if anybody use renderer part of API  (e.g. storing output to disk) ;-) for simple formats like TSV or txt  if they have access to ResultIterator...

**Comment by zdenop** [comment]
@stwei : What is your opinion here?

**Comment by stweil** [comment]
If we think that the API is not used for TSV, then removing those API functions would be a simple solution.

Regarding upper and lower case: it's already a mess, as there is also `TessAlto...`, `TessHOcr...`, `TessUnlv...`.

**Comment by Shreeshrii** [comment]
I think there are developers who would use it when available. Please see https://github.com/tesseract-ocr/tesseract/pull/2231#issuecomment-468855255

**Pull request merged**
