### PR TITLE
RFC: #pragma omp simd (don't merge)

### PR DESCRIPTION
**Pull request by rfschtkt**
If OpenMP 4.0 is available, use it for vectorisation.

Now how should I test this, I wonder...

### CODE REVIEW

**Comment by zdenop** [comment]
Just remark Visual studio 2015 [support only OpenMP 2.0](https://msdn.microsoft.com/en-us/library/tt15eb9t.aspx) standard. For VS 2017 there is not even documentation page for it :-(
[Community reques](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/13495731-add-support-for-openmp-4-5-to-vc)t for new standard was declined.

**Comment by zdenop** [comment]
@amitdo: thanks. I misunderstand [link ](https://msdn.microsoft.com/en-us/library/tt15eb9t.aspx) - I was expecting that there would be option to select version 2017 in combo "Other version".  I tried to search on [docs.microsoft.com](https://docs.microsoft.com/sk-sk/search/index?search=openmp&scope=VS+IDE) but nothing usefull found there.

**Comment by amitdo** [comment]
@zdenop

>Visual C++ supports the OpenMP 2.0 standard.

From #954: 

amitdo commented on Jun 6, 2017

>Just a note: #pragma omp simd is not supported with MSVC.

rfschtkt commented on Jun 6, 2017

>@amitdo I don't think that the laggard should set the pace, considering how relatively easy the pragma is to use.

:-)

**Comment by amitdo** [comment]
https://devblogs.microsoft.com/cppblog/msvc-backend-updates-in-visual-studio-2019-preview-2/

**Comment by zdenop** [comment]
@stweil : what about this? Even we do not suggest to use openmp, I think this could be merged for future development/test. Recent version of our most common [compilers support it](https://www.openmp.org/resources/openmp-compilers-tools/):

- From GCC 4.9.1, OpenMP 4.0 is fully supported
- OpenMP 4.5 has been available since Clang 3.9
- VS 2019 should [support #pragma omp simd](https://devblogs.microsoft.com/cppblog/simd-extension-to-c-openmp-in-visual-studio/)

**Comment by zdenop** [comment]
Closing this PR because function `WeightMatrix::DotProduct` was removed and `WeightMatrix::MatrixDotVector` rewritten.

**Pull request closed without merging**
