### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by amitdo**
https://github.com/blog/1184-contributing-guidelines

This should replace https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

Any comments?

### CODE REVIEW

**Comment by zdenop** [comment]
I would keep it in FAQ too, or provide link with short description...

**Comment by amitdo** [comment]
Yeah, this was my intention :-)
 I'm more in favor for the link option.

**Comment by amitdo** [comment]
@zdenop
Yesterday there was an option to "squash and merge" in the PR web interface. I don't see it right now. Did you change the setting?
https://github.com/blog/2141-squash-your-commits

**Comment by zdenop** [comment]
No I did not make any changes.

**Comment by stweil** [comment]
The option is visible in the 2nd step of the merge process: first you select "Merge pull request", then you can change the kind of merge during the confirmation.

**Comment by amitdo** [comment]
Okay :)

**Comment by amitdo** [comment]
I wanted to choose this option, but accidentally push the button itself instead of the arrow :(
Not a big deal...

**Comment by amitdo** [comment]
IMHO, this is bad UX design.

**Comment by stweil** [comment]
Yes, it is not so nice.

Squashing can also be done in your local copy of the repository (`git rebase -i`, then update your pull request with `git push -f`). I personally prefer that variant as it avoids the problem with the GitHub user interface.

**Comment by amitdo** [comment]
Right. but it's too tempting  to use the GUI - just a few clicks...

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

**Pull request merged**
