### PR TITLE
Remove code for _MSC_VER < 1900

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by amitdo** [comment]
DON'T MERGE.

https://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-a-particular-visual-studio-version

We don't support _MSVC_VER < 1900.

Change the code to remove this check.

**Comment by zdenop** [comment]
Visual Studio >= 2015  supports [snprintf](https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx), so whole condition it is not need.

**Comment by stweil** [comment]
@amitdo, @zdenop, thank you for the review. I updated the commit to remove all code for `_MSC_VER < 1900`.

**Comment by amitdo** [comment]
LGTM.

AppVeyor runs faster than before.

**Comment by amitdo** [comment]
@stweil,

https://github.com/tesseract-ocr/tesseract/commit/f94b3fd9fc1ec443.patch

>Date: Mon, 30 Apr 2018 18:14:34 +0200

Hmmm, do you a time machine? :-)

**Comment by stweil** [comment]
Of course, without I could not manage my work. :-)

That's the time stamp of the old commit. Obviously `git gui` did not update it when I added more changes. :-(

**Pull request merged**
