### PR TITLE
Implemented improved character bounding box algorithm

### PR DESCRIPTION
**Pull request by noahmetzger**
The algorithm is using the new character bounding boxes which were calculated
to create better symbol choices for the lstm_choice_mode.

Signed-off-by: Noah Metzger <noah.metzger@bib.uni-mannheim.de>

### CODE REVIEW

**Comment by noahmetzger** [comment]
Here are some examples of the old bounding boxes vs the new ones:

Old:
52Old
New:
52New

Old:
smaraOld
New:
smaraNew

Old:
rbbOld
New:
rbbNew

**Comment by stweil** [comment]
Hopefully this fixes several issues: #1276, #2024, #2521.

**Comment by zdenop** [comment]
thanks!

**Comment by StephenRUK** [comment]
Fantastic, sure this will fix our issues too 👍

**Pull request merged**
