### PR TITLE
Add build script for oss-fuzz fuzzers (improved copy from google/oss-fuzz)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
@guidovranken, please review. As soon as this pull request was merged, `build.sh` in oss-fuzz should be modified to use it. Commit https://github.com/stweil/oss-fuzz/commit/8c3169a62085ba93daf3600d08f932f6812877f9 can be used for that.

**Comment by stweil** [comment]
@AdamKorcz, ready for updating oss-fuzz. :-)

**Comment by AdamKorcz** [comment]
@stweil Sounds good. The build script you had made on your fork looked like it would get the job done. Do you want to make a PR for it with that on oss-fuzz and I will keep an eye out on Travis?

**Comment by stweil** [comment]
> Do you want to make a PR for it with that on oss-fuzz?

I cannot, because they won't let me without signing that lengthy CLA, not even for trivial commits. :-(

**Comment by AdamKorcz** [comment]
Ok. Let me do it then.

**Pull request merged**
