### PR TITLE
Replace most malloc / realloc / free by new / delete / std::vector

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by egorpugin** [comment]
separate note
There are many static arrays over the codebase.
I think we can try to replace them with `std::array`. This might help in iterating over them.
Like
```
ADAPTED_CONFIG Config[MAX_NUM_CONFIGS];
->
std::array<ADAPTED_CONFIG, MAX_NUM_CONFIGS> Config;
```

**Comment by amitdo** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-c-arrays.html

**Comment by stweil** [comment]
`clang-tidy` reports more than 600 warnings for code which can be updated to use `std::array`, but those updates have to be made manually.

**Comment by egorpugin** [comment]
clang-tidy can't do that or it gives a lot of misuses and compilation errors?

**Comment by stweil** [comment]
Citing the documentation linked above: "However, fix-it are potentially dangerous in header files and are therefore not emitted right now."

clang-tidy only warns, but does not change the code.

**Pull request merged**
