### PR TITLE
Add SPDX-License-Identifier to public include files

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See issue #3688. Adding SPDX license identifiers to the public API allows automated parsing of license information.

**Review by egorpugin — APPROVED** [review]

**Comment by egorpugin** [comment]
I don't like existing ///////////////////////////// first line.
Can we remove it later too?

**Comment by stweil** [comment]
> Can we remove it later too?

Yes, I can add a commit which removes it. But maybe the `////` line at the end of the header comments should then be removed, too.

**Comment by stweil** [comment]
Is PR #3690 fine?

**Pull request merged**
