### PR TITLE
Update unichar.h

### PR DESCRIPTION
**Pull request by atuc17**
add `using namespace std;` into unichar.h

### CODE REVIEW

**Comment by stweil** [comment]
Could you please test latest Tesseract and see whether this pull request is still needed? If not, please close it (and also issue #1047).

**Comment by fifothekid** [comment]
I think that you should replace string with std::string on line:
https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/unichar.h#L164
It worked for me with this change

**Comment by fifothekid** [comment]
Created pull request
https://github.com/tesseract-ocr/tesseract/pull/1082

**Comment by amitdo** [comment]
See https://github.com/tesseract-ocr/tesseract/pull/1082#issuecomment-323009498

**Comment by amitdo** [comment]
@zdenop, I suggest to close this PR.

**Pull request closed without merging**
