### PR TITLE
Avoid lots of messages for training with single line images

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
I hope that nobody will miss those messages.

**Comment by egorpugin** [comment]
In theory such messages should be in trace verbosity.
One log level is definitely not enogh.

**Comment by Shreeshrii** [comment]
@stweil I see that the `Loaded` messages are no longer there. Thanks, it will certainly make the log files smaller.

If possible, as suggested by @egorpugin they can be kept for trace verbosity. It will be helpful when trying to track an error.

```
Loaded 1/1 lines (1-1) of document data/San-ground-truth/bugfix/san.Segoe_UI_Semi-Light.0000002.exp0_0.lstmf
Loaded 1/1 lines (1-1) of document data/San-ground-truth/bugfix/san.Mandala_Italic.0000080.exp0_0.lstmf
Loaded 1/1 lines (1-1) of document data/San-ground-truth/bugfix/san.Segoe_UI_Semi-Light_Italic.0000040.exp0_0
```

**Comment by stweil** [comment]
All warning and error messages report the filename. Example:

    Compute CTC targets failed for data/gt/AustrianNewspapers/train/ONB_ibn_19110701_010/ONB_ibn_19110701_010.tif_line_1547100903812_34.lstmf!

So the removed message should not be needed for error tracking.

**Pull request merged**
