### PR TITLE
tesstrain: check failure of subjobs

### LINKED ISSUE #2313: tesstrain continues on text2image error
```
Stripped 5 unrenderable words
Error in pixCreateNoInit: pix_malloc fail for data
Error in pixCreateTemplateNoInit: pixd not made
Error in pixGetData: pix not defined
Error in pixGetWpl: pix not defined
Error in composeRGBPixel: &pixel not defined
Rendered page 56 to file /tmp/tam-2019-03-12.PQP/tam.Noto_Sans_Tamil_Bold.exp0.tif
Stripped 1 unrenderable words
ERROR: Program text2image failed. Abort.
Rendered page 57 to file /tmp/tam-2019-03-12.PQP/tam.TAMu_Kadambri_Regular.exp0.tif
Stripped 50 unrenderable words
Rendered page 57 to file /tmp/tam-2019-03-12.PQP/tam.Noto_Sans_Tamil_Bold.exp0.tif
Stripped 3 unrenderable words
ERROR: Program text2image failed. Abort.
```

Even on error the bash script continues and dies only at end of phase:

```
Stripped 2 unrenderable words
Rendered page 117 to file /tmp/tam-2019-03-12.PQP/tam.e-Grantamil.exp0.tif
Rendered page 118 to file /tmp/tam-2019-03-12.PQP/tam.e-Grantamil.exp0.tif
Rendered page 119 to file /tmp/tam-2019-03-12.PQP/tam.e-Grantamil.exp0.tif
ERROR: /tmp/tam-2019-03-12.PQP/tam.Arial_Unicode_MS.exp0.box does not exist or is not readable
```

*Expected* - End script at the first error itself so that problem can be investigated early.

### PR DESCRIPTION
**Pull request by bertsky**
in an attempt to fix #2313

### CODE REVIEW

**Comment by stweil** [comment]
@Shreeshrii, could you test this commit and can it be merged? Technically it looks good for me, but I currently don't have time to test it.

**Comment by stweil** [comment]
A side remark: since some time there is also a Python3 script for training. Certain modifications for the shell script (e.g. enhancements) are also needed for the Python3 script.

Maybe we should drop the shell script one day.

**Comment by bertsky** [comment]
@stweil, I have seen the Python script, it looks fine to me. The changes so far are all against bash-specific problems. (My guess is that someone introduced `errexit` later-on, without cross-checking all its implications.)

**Comment by stweil** [comment]
Yes, exiting on error was added in commit 486940687.

**Comment by Shreeshrii** [comment]
@bertsky I tested the updated bash script. It is running `text2image `only for the first font in the list (no parallel processing) and then hangs (waits) at end of that. 

You can test with the following command:

```
rm -rf  ~/tesstutorial/engtrain 
bash ~/tesseract/src/training/tesstrain.sh \
  --fonts_dir /usr/share/fonts \
  --lang eng \
  --linedata_only \
  --noextract_font_properties \
  --langdata_dir ~/langdata \
  --tessdata_dir ~/tessdata  \
  --training_text ~/langdata/eng/eng.training_text \
  --exposures "0" \
  --save_box_tiff \
  --maxpages 0 \
  --workspace_dir ~/tmp \
  --fontlist \
    "Arial Bold" \
    "Arial Bold Italic" \
    "Arial Italic" \
    "Arial" \
    "Courier New Bold" \
    "Courier New Bold Italic" \
    "Courier New Italic" \
    "Courier New" \
    "Times New Roman, Bold" \
    "Times New Roman, Bold Italic" \
    "Times New Roman, Italic" \
    "Times New Roman," \
    "Georgia Bold" \
    "Georgia Italic" \
    "Georgia" \
    "Georgia Bold Italic" \
    "Trebuchet MS Bold" \
    "Trebuchet MS Bold Italic" \
    "Trebuchet MS Italic" \
    "Trebuchet MS" \
    "Verdana Bold" \
    "Verdana Italic" \
    "Verdana" \
    "Verdana Bold Italic" \
    "URW Bookman L Bold" \
    "URW Bookman L Italic" \
    "URW Bookman L Bold Italic" \
    "Century Schoolbook L Bold" \
    "Century Schoolbook L Italic" \
    "Century Schoolbook L Bold Italic" \
    "Century Schoolbook L Medium" \
    "DejaVu Sans Ultra-Light" \
  --output_dir ~/tesstutorial/engtrain
```

**Comment by bertsky** [comment]
@Shreeshrii sorry, I really should have tested this. Apparently, in bash the return status of `let counter++` is nonzero when `counter` was zero before, so the loop broke after the very first run (and should have given your prompt back). It does not in the form `let ++counter`, though! 

Nevertheless, I used a different method altogether (based on explicit `$!` control) so one can ensure that all jobs are successful in the end.

**Comment by Shreeshrii** [comment]
@bertsky  

1. The english example runs fine. 
2. If I try to kill the job with CTRL C/CTRL Z etc. the subjobs are not killed.

```
Rendered page 100 to file /tmp/tam-2019-03-14.rYu/tam.Hind_Madurai.exp0.tif
Stripped 2 unrenderable words
Rendered page 99 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
Stripped 1 unrenderable words
Rendered page 100 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
Stripped 3 unrenderable words
^C
ubuntu@tesseract-ocr:~/tesstutorial$ Rendered page 101 to file /tmp/tam-2019-03-14.rYu/tam.Hind_Madurai.exp0.tif
Stripped 6 unrenderable words
Rendered page 101 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
^C
ubuntu@tesseract-ocr:~/tesstutorial$ Rendered page 102 to file /tmp/tam-2019-03-14.rYu/tam.Hind_Madurai.exp0.tif
Stripped 10 unrenderable words
Rendered page 102 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
Stripped 1 unrenderable words

```
3. When running the larger files which got the earlier error, script is still failing.

```
Rendered page 35 to file /tmp/tam-2019-03-14.rYu/tam.Hind_Madurai.exp0.tif
Rendered page 33 to file /tmp/tam-2019-03-14.rYu/tam.Latha.exp0.tif
Rendered page 34 to file /tmp/tam-2019-03-14.rYu/tam.FreeSerif.exp0.tif
Stripped 8 unrenderable words
Stripped 4 unrenderable words
Rendered page 34 to file /tmp/tam-2019-03-14.rYu/tam.Latha.exp0.tif
Stripped 2 unrenderable words
Rendered page 35 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
Stripped 1 unrenderable words
/home/ubuntu/tesseract/src/training/tesstrain_utils.sh: line 62:  4481 Killed                  "${cmd}" "$@" 2>&1
      4482 Done                    | tee -a ${LOG_FILE}
ERROR: Program text2image failed. Abort.
Rendered page 35 to file /tmp/tam-2019-03-14.rYu/tam.Kavivanar.exp0.tif
Stripped 10 unrenderable words
Rendered page 35 to file /tmp/tam-2019-03-14.rYu/tam.FreeSerif.exp0.tif
Stripped 2 unrenderable words
Rendered page 35 to file /tmp/tam-2019-03-14.rYu/tam.Latha.exp0.tif
Rendered page 36 to file /tmp/tam-2019-03-14.rYu/tam.Lohit_Tamil_Classical.exp0.tif
Stripped 1 unrenderable words
Rendered page 36 to file /tmp/tam-2019-03-14.rYu/tam.Kavivanar.exp0.tif

```

**Comment by bertsky** [comment]
@Shreeshrii 
>     2\. If I try to kill the job with CTRL C/CTRL Z etc. the subjobs are not killed.

Well `C-z` (SIGTSTP/SIGCONT with `fg` or `bg`) does work perfectly for me. Which version of bash do you have?

As for `C-c`, indeed, very strange behaviour! Attaching with gdb I always see the program stalled at SIGINT, despite the bash manual stating ...

> When bash is interactive, in the absence of any traps, [...] SIGINT is caught and handled (so that the wait builtin is interruptible). [...] When bash is waiting for an asynchronous command via the wait builtin, the reception of a signal for which a trap has been set will cause the wait builtin to return immediately with an exit status greater than 128

Whatever, I added a workaround.

>     1. When running the larger files which got the earlier error, script is still failing.

How can I reproduce this? Also, have you been using the relevant changesets from #2294, i.e. 349558d and 91a7e86?

**Comment by Shreeshrii** [comment]
> Which version of bash do you have?

bash --version
GNU bash, version 4.3.48(1)-release (powerpc64le-unknown-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

>How can I reproduce this?

The problem seems to be lack of memory on the VM I use. I tried adding a swapfile but it didn't help - see https://github.com/tesseract-ocr/tesseract/issues/2313#issuecomment-472947300

This is happening when I use `--distort-image=true` with text2image. This is recently enabled option by me, `false` by default.

**Comment by bertsky** [comment]
> The problem seems to be lack of memory on the VM I use.

Well I tried simulating this with a `ulimit -v 286000` in the above run for English (and even removing the sleep statements in tesstrain_utils.sh). This works as expected, the whole scripts terminates as soon as its children do. (I advise to merge with #2294, though.)

**Comment by bertsky** [comment]
Regarding memory limitation in general, maybe the number of processes should be made a CLI parameter, or at least equipped with a better/saner guess in the runtime environment?

**Comment by bertsky** [comment]
> > Which version of bash do you have?
> 
> bash --version
> GNU bash, version 4.3

Interesting. I am using 4.4, where I see some changes in the vicinity of above discussed behaviour:

> Bash now retains the exit status only of asynchronous jobs, as opposed to all
jobs. This means that it is not possible to use `wait' to retrieve the status of a previously-completed synchronous command.

> Bash now treats SIGINT received when running a non-builtin command in a loop the way it has traditionally treated running a builtin command: running any trap handler and breaking out of the loop.

> Interactive shells now behave as if SIGTSTP/SIGTTIN/SIGTTOU are set to SIG_DFL when the shell is started, so they are set to SIG_DFL in child processes.

I am _not_ sure whether any of these actually is responsible for differences we might observe here (whatever just exactly these are).

**Comment by bertsky** [comment]
> maybe the number of processes should be made a CLI parameter, or at least equipped with a better/saner guess in the runtime environment?

For example, one could do the following in a (quite) portable way:
```sh
((echo "$(LC_ALL=C uptime | cut -d: -f5 | cut -d, -f1) > MAX_LOAD" | bc)) && wait -n
```

**Comment by Shreeshrii** [comment]
I upgraded bash to 4.4 and applied both PRs - 2294 and 2319 and training is completing without any error on subjobs.

bash --version
GNU bash, version 4.4.18(1)-release (powerpc64le-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by stweil** [comment]
Thank you, @bertsky and @Shreeshrii, for the contribution and the tests.

**Pull request merged**
