### PR TITLE
Fix Inappropriate string causes abnormal loop

### PR DESCRIPTION
**Pull request by junsik-kim0**
Soultion to issue https://github.com/tesseract-ocr/tesseract/issues/3604 (Inappropriate string causes abnormal loop).

If increment operator(++) returns a value longer than the string length, the loop may behave abnormally.
So it has been modified to work only when the range is smaller than string length.

### CODE REVIEW

**Review by stweil — COMMENTED** [review]
Did you test your code change? It looks wrong.

**Comment by afosscontact** [comment]
Oops.. I just ran the make command, and it seems that the build was successful.
I'm sorry for not checking properly. I modified source code.

**Comment by stweil** [comment]
Please check also your Git settings (`git config --global user.name`). Your commits currently show this:

    Author: afosscontact <afosscontact@gmail.com>

"afosscontact" does not look like a real name.

**Comment by junsik-kim0** [comment]
I replaced my username with my real name.

**Comment by amitdo** [comment]
stweil,

Should we merge this PR?

**Comment by stweil** [comment]
No, these changes are not required to fix a real issue, and they would hide problems with bad strings. I therefore closed the issue and close the pull request as well.

**Pull request closed without merging**
