### PR TITLE
Travis: build linux matrix

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by egorpugin** [comment]
Push changes here until it is fixed.
Ping me when you are done.

**Comment by Shreeshrii** [comment]
Thanks! Still getting some errors on diff arch, even though I have built manually on those platforms successfully.

**Comment by Shreeshrii** [comment]
text2image build is failing on Arm64, ppc64le and s390x. The errors are related to Pango. Build completes OK on AMD64.

The errors were different when the packages were included ass add-ons, now I manually install them. Seem to be linking errors.

Latest log: https://travis-ci.org/github/tesseract-ocr/tesseract/builds/761809581
```
Scanning dependencies of target pango_training
[ 87%] Building CXX object src/training/CMakeFiles/pango_training.dir/pango/boxchar.cpp.o
[ 88%] Building CXX object src/training/CMakeFiles/pango_training.dir/pango/ligature_table.cpp.o
[ 88%] Building CXX object src/training/CMakeFiles/pango_training.dir/pango/pango_font_info.cpp.o
[ 88%] Building CXX object src/training/CMakeFiles/pango_training.dir/pango/stringrenderer.cpp.o
[ 89%] Building CXX object src/training/CMakeFiles/pango_training.dir/pango/tlog.cpp.o
[ 89%] Linking CXX static library libpango_training.a
[ 89%] Built target pango_training
Scanning dependencies of target text2image
[ 89%] Building CXX object src/training/CMakeFiles/text2image.dir/text2image.cpp.o
[ 90%] Building CXX object src/training/CMakeFiles/text2image.dir/degradeimage.cpp.o
[ 90%] Linking CXX executable ../../bin/text2image
CMakeFiles/text2image.dir/text2image.cpp.o: In function `main':
text2image.cpp:(.text.startup+0x9e): undefined reference to `pango_version_string'
libpango_training.a(pango_font_info.cpp.o): In function `tesseract::PangoFontInfo::PangoFontInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
pango_font_info.cpp:(.text+0x80): undefined reference to `pango_font_description_from_string'
pango_font_info.cpp:(.text+0xb6): undefined reference to `pango_font_description_free'
pango_font_info.cpp:(.text+0xc6): undefined reference to `pango_font_description_get_family'
pango_font_info.cpp:(.text+0x194): undefined reference to `pango_font_description_copy'
pango_font_info.cpp:(.text+0x1a4): undefined reference to `pango_font_description_get_size'
pango_font_info.cpp:(.text+0x1b6): undefined reference to `pango_font_description_get_size_is_absolute'
pango_font_info.cpp:(.text+0x1dc): undefined reference to `pango_font_description_free'
pango_font_info.cpp:(.text+0x296): undefined reference to `pango_font_description_free'
pango_font_info.cpp:(.text+0x2a4): undefined reference to `pango_font_description_to_string'
pango_font_info.cpp:(.text+0x2c2): undefined reference to `g_free'
pango_font_info.cpp:(.text+0x2cc): undefined reference to `pango_font_description_free'
pango_font_info.cpp:(.text+0x310): undefined reference to `pango_font_description_free'
libpango_training.a(pango_font_info.cpp.o): In function `tesseract::PangoFontInfo::Clear()':
pango_font_info.cpp:(.text+0x3dc): undefined reference to `pango_font_description_free'
libpango_training.a(pango_font_info.cpp.o): In function `tesseract::PangoFontInfo::~PangoFontInfo()':
```

I build tesseract with training tools on AArch64 and Power8 and have in the past also build on the big-endian machine. 

@stweil Any idea what is causing the issue?

**Comment by Shreeshrii** [comment]
Builds fine when I changed the distro to `focal`. So the minimum Pango version is now higher than 1.40 which was failing on bionic.

https://travis-ci.org/github/tesseract-ocr/tesseract/builds/761812891

**Comment by Shreeshrii** [comment]
Recognition fails on s390x using tessdata file built elsewhere.

```
$ tesseract /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif - -l eng --tessdata-dir ./
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/home/travis/.travis/functions: line 109:  9412 Aborted                 (core dumped) tesseract /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif - -l eng --tessdata-dir ./
```

**Comment by egorpugin** [comment]
It's ok. This can be fixed later. Just make sure that builds are find in this PR.

**Comment by Shreeshrii** [comment]
All builds are OK. 
See https://travis-ci.org/github/tesseract-ocr/tesseract/builds/761817655

Please squash the commits and merge.

I tried to rebase and squash but am getting a conflict, so I'd rather not do it.

Thanks.

**Comment by stweil** [comment]
Is s390x big endian? Then I might have a fix for it.

**Comment by egorpugin** [comment]
> Is s390x big endian?

I think yes.

> Recognition fails on s390x using tessdata file built elsewhere.

@Shreeshrii 
Can we see it somewhere on CI?

**Comment by stweil** [comment]
>  Can we see it somewhere on CI?

https://travis-ci.org/github/tesseract-ocr/tesseract/jobs/761833458#L1790

**Comment by egorpugin** [comment]
Oh, I understand. (Saw that line, but did not expand.) It does not affect build status.
I prefer to show such things and do not hide issues.
So, I think it's better to put it into build, so we will be warned with red status until the issue is fixed.

**Comment by stweil** [comment]
It looks like my build passes that test for s390x: https://travis-ci.org/github/stweil/tesseract/jobs/761844092#L1913.

The relevant commit https://github.com/tesseract-ocr/tesseract/commit/b467f1a41cd898174bdfa8d626990b9877c14c83 is part of https://github.com/stweil/tesseract/tree/unpack.

**Comment by egorpugin** [comment]
1. from travis

> 0.00s$ tesseract /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif - -l eng --tessdata-dir ./
Unknown action: /home/travis/build/tesseract-ocr/tesseract/test/testing/phototest.tif

Does it really pass?

2. 
> relevant commit

I don't like specializations for serialis. I said it earlier.
Like when we'll replace the next `GenericVector` with `std::vector` of other type and it will try to use GenericVector::SerializeClasses, we need to change it to `TFile::SerializeClasses` (which you removes in this commit) or write the same code in second new specialization.

---

At the end I'm still fine with merging, but I hope you'll get the idea of common code (C++ templates) once.

**Comment by stweil** [comment]
> I don't like specializations for serialis.

Nor do I. It should be possible to have `Serialize` and `DeSerialize` templates which work for vectors of classes and non-classes by using SFINAE (something which I just learned yesterday), so there is no need for new method names like `SerializeClasses`. That's my preferred solution, and I'll try it later.

**Comment by stweil** [comment]
@egorpugin, I just pushed commit 0f1296c6f623f2070118e125bf5a1b8662afb4d9 which cleans the serialization code.

**Comment by egorpugin** [comment]
> which work for vectors of classes and non-classes by using SFINAE

We'll do it in C++17 after 5.0 branch is created.
See https://github.com/egorpugin/tgbot/blob/master/src/api_templates.h#L21
`is_instance` impl is on the first line of that file.

---

cc: @zdenop 
By the way, is there any big changes you want to add into 5.0 release?
I think we could 1) create 5.0 branch, 2) remove any C++17 code to be C++14 compatible, 3) do another alpha or beta release there, 4) fix issues, 5) iterate until release.
This allows us 1) to release 5.0 faster, 2) removes block on master branch, so we could continue doing major changes.

As I remember, for 5.0 (and for master also) we should restore some of removed C APIs.
Other items are not so big.

**Comment by zdenop** [comment]
IMO when C++ and C API will be stable (e.g. not known issues, or planned changes) we can go for beta release, so 3rd party projects can have a chance to report problems... I would leave 4 week for phase. In meantime

Then we should go for rc cycle(s) & fixing docs.

**Pull request merged**
