### PR TITLE
Address some build issues (mainly for Mingw-w64)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by amitdo** [comment]
What about using pkg-config for detecting Leptonica version?

**Comment by stweil** [comment]
Yes, that could be done as well. Maybe we should require a Leptonica installations with pkg-config. That would simplify that part of the configuration a lot.

**Comment by amitdo** [comment]
Leptonica provides pkg-config pc file since 1.70.

**Comment by stweil** [comment]
Then let's remove the unneeded code. :-)

**Comment by amitdo** [comment]
Any volunteer? :laughing:

**Pull request merged**
