### PR TITLE
[WIP] configure.ac: Fix debug mode

### PR DESCRIPTION
**Pull request by amitdo**
Debug mode should be "-g -O0".

See: https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/C_002b_002b-Compiler.html

### CODE REVIEW

**Comment by amitdo** [comment]
DON'T MERGE YET.

Needs testing.

**Comment by amitdo** [comment]
It does not work well  :(

Closing for now.

**Comment by amitdo** [comment]
I figured out what was the problem.

I'll submit a fix in a few days.

**Comment by stweil** [comment]
A simple solution which works without a code change is running `./configure [...] CXXFLAGS="-g -O0"`. My usual variant for testing is `mkdir bin/debug && cd bin/debug && ../../configure --enable-debug --disable-shared --disable-static CXXFLAGS="-Wall -Wextra -g -O0"`.

**Pull request closed without merging**
