### PR TITLE
RFC: ACTIONS CI: Crosscompile currently failing for leptonica

### PR DESCRIPTION
**Pull request by Shreeshrii**
Need help to fix error related to leptonica.

### CODE REVIEW

**Comment by egorpugin** [comment]
What is the purpose of this?

**Comment by Shreeshrii** [comment]
@amitdo suggested to do migw64 builds in ci. The crosscompile method is how the umanneheim windows binaries are built on Linux. Just trying to replicate that in CI.

**Comment by egorpugin** [comment]
Do mingw64 on win, we are not interested in crosscompilation CIs.

**Comment by Shreeshrii** [comment]
>Do mingw64 on win, 

Any example/instructions for this?

**Comment by amitdo** [comment]
https://www.google.com/search?q=github+actions+mingw-w64

https://github.com/msys2/setup-msys2

**Comment by Shreeshrii** [comment]
I have already created the msys2 workflows.
See

https://github.com/tesseract-ocr/tesseract/actions/runs/676905249

The one for 4.1.1 is set to run only once a month.

**Comment by Shreeshrii** [comment]
>we are not interested in crosscompilation CIs.

Cross compile is listed in the documentation as one of the compile options for windows. Having a working CI helps use it as an example. We can run it once a month/year not daily. If I can get it working !!!

**Comment by Shreeshrii** [comment]
@stweil Please share a link to your crosscompilation script so that I can try to fix this.

**Comment by stweil** [comment]
> Please share a link to your crosscompilation script so that I can try to fix this.

https://github.com/UB-Mannheim/tesseract/blob/windows/.github/workflows/build.sh

**Comment by Shreeshrii** [comment]
@stweil That's pretty involved! And, you already have it as one of your workflows. So, I'll close this.

**Pull request closed without merging**
