### PR TITLE
Tesseract not working fine with arabic 

### PR DESCRIPTION
**Pull request by waleedraza786**
Hello,
I installed tesseract and tested it , it gives correct result for english.
But i have to extract Arabic text for which i download ara.traineddata and its related files from here
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-400
then i tried a jpeg image and got its output on a text file. then it retrieves arabic txt but not proper result
 
   

جهمة # ك سو-ة

. ظرسظة عهود

١صي سعد إلاء . سلعة-ا
. سدلعدسسلعلىوس
وا{ قللا{ ٧تلا ٣تاتع٨ اق با لإت«اح» . سا مي ضجة دةسءع عظك
«قلم«ة٧حلا و و«تعهاق بي ئت»حه لة

and there is not such words in this image

image

and when i used -l ara+eng parameter then out says no best words !! and tesseract stoped working.
whats the problem here ?
image

### CODE REVIEW

**Comment by zdenop** [comment]
This not correct PR

**Comment by waleedraza786** [comment]
so please tell me whom can i ask to guide me about this issue ?

**Comment by amitdo** [comment]
How he made all those old comments from me, zdenko and others reappear here?

Really weird.

**Comment by Shreeshrii** [comment]
Arabic is not fully accurate with 4.0. there are already open issues
regarding same. You will have to wait for new training by Ray for
improvement.

- excuse the brevity, sent from mobile

**Pull request closed without merging**
