### PR TITLE
 Fix and enable stringrenderer_test

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
Some of the tests fail because of missing fonts. Maybe all required fonts can be added to the `test` directory.

**Comment by stweil** [comment]
@jbreiden, are the fonts Arab and Lohit Hindi free? If yes, could you please provide them so they can be added to the test data? The other required fonts UnBatang and Verdana are available for Linux.

**Comment by Shreeshrii** [comment]
Lohit Hindi is a free font but it has now been superseded by Lohit Devanagari. Please see 
https://src.fedoraproject.org/rpms/lohit-hindi-fonts
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=lohit-deva&searchon=names

I might have a downloaded version of Lohit Hindi that  I can upload to testdata.

**Comment by Shreeshrii** [comment]
[ RUN      ] StringRendererTest.DoesRenderToImage
WARNING: Dropped 43 uncovered characters
WARNING: Dropped 72 uncovered characters
WARNING: Dropped 102 uncovered characters
WARNING: Dropped 154 uncovered characters
WARNING: Dropped 35 uncovered characters
[       OK ] StringRendererTest.DoesRenderToImage (327 ms)
[ RUN      ] StringRendererTest.DoesRenderToImageWithUnderline
WARNING: Dropped 43 uncovered characters
WARNING: Dropped 43 uncovered characters
WARNING: Dropped 43 uncovered characters
[       OK ] StringRendererTest.DoesRenderToImageWithUnderline (1 ms)

Even though the test is not failing, it seems stringrenderer is not working correctly. 
eg. const char kEngText[] = "the quick brown fox jumps over the lazy dog"; is 43 characters long and all of these are getting dropped.

**Comment by stweil** [comment]
> I had to add LEPTONICA_LIBS to Makefile.am for this test

Thank you. This is fixed now.

**Comment by Shreeshrii** [comment]
I put copies of fonts locally in tesseract/test/testing and more subtests are passing now.

**Comment by stweil** [comment]
Subtests should not fail but be skipped (`GTEST_SKIP`) if a required font is missing.

**Comment by Shreeshrii** [comment]
@stweil Is there a way to run only one unittest at a time? 

Currently I use `make check` which runs all tests and takes long to run. I tried `./unittest/stringrenderer_test  > ./unittest/stringrenderer_test.log 2>&1` but that gets errors.

**Comment by stweil** [comment]
Please try it from the `unittest` directory:

    cd unittest && ./stringrenderer_test >stringrenderer_test.log 2>&1

That works for me. It should also work when run from the root directory, but fails for me there, too. Typically I run lots of tests parallel using `make check -j16` on a server or `make check -j4` on my notebook.

**Comment by Shreeshrii** [comment]
Arab font is part of
https://packages.ubuntu.com/trusty/all/fonts-arabeyes/filelist

/usr/share/fonts/truetype/fonts-arabeyes/ae_Arab.ttf

**Comment by Shreeshrii** [comment]
Only one subtest related to ligatures is failing now. 
```
[ RUN      ] StringRendererTest.DISABLED_DoesDropUncoveredChars
stringrenderer_test.cc:448: Failure
Value of: renderer_->font().CanRenderString(kWord.c_str(), kWord.length())
  Actual: true
Expected: false
stringrenderer_test.cc:449: Failure
Value of: renderer_->font().CoversUTF8Text(kWord.c_str(), kWord.length())
  Actual: true
Expected: false
stringrenderer_test.cc:454: Failure
Expected equality of these values:
  kCleanWord.length()
    Which is: 4
  boxchars.size()
    Which is: 5
[  FAILED  ] StringRendererTest.DISABLED_DoesDropUncoveredChars (0 ms)
```
I think it is related to change in processing of the same  in tesseract and can be disabled.

```
TEST_F(StringRendererTest, DISABLED_DoesDropUncoveredChars) {
```
To include it in test, please run 
```
cd unittest && ./stringrenderer_test --gtest_also_run_disabled_tests >stringrenderer_test.log 2>&1
```

**Pull request merged**
