### PR TITLE
Fix unittests

### PR DESCRIPTION
**Pull request by stweil**
Replace some more GenericVector by std::vector and use the old implementation for the remaining ones.

### CODE REVIEW

**Comment by stweil** [comment]
All unittests now pass (also with sanitizers enabled), so hopefully we have a stable version again.

**Comment by egorpugin** [comment]
Oh, I don't like it. Maybe keep current approach and fix tests one by one?

**Comment by egorpugin** [comment]
It's still fine.

**Comment by egorpugin** [comment]
So, it is fixed two more tests for me.
Seems like others need to be set up properly.

```Test results:
TOTAL:  56
PASSED: 43
FAILED: 13

List of failed tests:
test: [google.tesseract.libtesseract-master]/pango_font_info
test: [google.tesseract.libtesseract-master]/equationdetect
test: [google.tesseract.libtesseract-master]/params_model
test: [google.tesseract.libtesseract-master]/lstm
test: [google.tesseract.libtesseract-master]/imagedata
test: [google.tesseract.libtesseract-master]/shapetable
test: [google.tesseract.libtesseract-master]/indexmapbidi
test: [google.tesseract.libtesseract-master]/lang_model
test: [google.tesseract.libtesseract-master]/lstm_squashed
test: [google.tesseract.libtesseract-master]/ligature_table
test: [google.tesseract.libtesseract-master]/lstm_recode
test: [google.tesseract.libtesseract-master]/lstmtrainer
test: [google.tesseract.libtesseract-master]/stringrenderer
```

**Comment by stweil** [comment]
@egorpugin, did you install all required fonts in `test/testing`?

**Comment by egorpugin** [comment]
Not sure. Probably no. This is not an issue now.
Because when I open next test it shows other errors than missing files or something.
Like for example `equationdetect_test`
stdout:
```
Running main() from gmock_main.cc
[==========] Running 10 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 10 tests from EquationFinderTest
[ RUN      ] EquationFinderTest.IdentifySpecialText
```
stderr:
```
ClassId >= 0 && ClassId < MAX_NUM_CLASSES:Error:Assert failed:in file D:/dev/tesseract/src/classify/cutoffs.cpp, line 67
ObjectCache(00007FFCB834BF10)::~ObjectCache(): WARNING! LEAK! object 000001C9FEBEF750 still has count 1 (id D:/dev/tesseract/tessdata_unittest/tessdata/eng.traineddatapunc-dawg)
ObjectCache(00007FFCB834BF10)::~ObjectCache(): WARNING! LEAK! object 000001C9FEBEF440 still has count 1 (id D:/dev/tesseract/tessdata_unittest/tessdata/eng.traineddataword-dawg)
ObjectCache(00007FFCB834BF10)::~ObjectCache(): WARNING! LEAK! object 000001C9FEBEF4B0 still has count 1 (id D:/dev/tesseract/tessdata_unittest/tessdata/eng.traineddatanumber-dawg)
ObjectCache(00007FFCB834BF10)::~ObjectCache(): WARNING! LEAK! object 000001C9FEBEEBF0 still has count 1 (id D:/dev/tesseract/tessdata_unittest/tessdata/eng.traineddatabigram-dawg)
ObjectCache(00007FFCB834BF10)::~ObjectCache(): WARNING! LEAK! object 000001C9FEBEE870 still has count 1 (id D:/dev/tesseract/tessdata_unittest/tessdata/eng.traineddatafreq-dawg)
```

**Comment by stweil** [comment]
>  Because when I open next test it shows other errors than missing files or something.

The current test code is not very robust and will not always report missing files or skip such tests, so I'd make sure that all seven fonts are installed.

**Comment by egorpugin** [comment]
I see what is the problem there.
I cloned whole tessdata. equationdetect_test tries to load `equ.traineddata` during test setup phase and fails to do it.
But all tests in it are `GTEST_SKIP()`. Well done.

**Comment by egorpugin** [comment]
> equationdetect_test tries to load equ.traineddata during test setup phase and fails to do it.

It is either bad data or tess issue.

**Comment by Shreeshrii** [comment]
On the subject of fixing unittests, many of the tests use unicharset files provided by Ray. Some of these do not match current unicharset format (from langdata_lstm for script/language) or the lstm-unicharset from the traineddata or the unicharset generated during training. So I wonder whether the test results are accurate.

**Comment by egorpugin** [comment]
Very possible.

**Pull request merged**
