### PR TITLE
download and install eng and osd traineddata

### PR DESCRIPTION
**Pull request by Shreeshrii**
eng and osd traineddata files are required for default functioning of tesseract.
Added option to download the files with --no-clobber option and copy to tessdata directory
Removed option related to langdata, as tesseract does not install all langdata files

### CODE REVIEW

**Comment by Shreeshrii** [comment]
@stweil Please review and correct. Thanks!

**Comment by Shreeshrii** [comment]
The URL for the traineddata files can be changed to use files from tessdata_fast repo, when they become available.

**Comment by stweil** [comment]
I must admit that I never used that Makefile target. Do we need it at all? If we offer a target which
downloads eng.traineddata, I wonder whether it would be better to get one which supports both the old and the new recognizer (only as long as both are supported, of course).

A side notice:

Currently Tesseract requires eng.traineddata even if someone only wants to get the Tesseract version or the list of available languages. I don't think that this is satisfying.

Tesseract functions which are unrelated to eng.traineddata should work without it.

**Comment by Shreeshrii** [comment]
>Currently Tesseract requires eng.traineddata even if someone only wants to get the Tesseract version or the list of available languages. I don't think that this is satisfying.
Tesseract functions which are unrelated to eng.traineddata should work without it.

I agree.

>I wonder whether it would be better to get one which supports both the old and the new recognizer (only as long as both are supported, of course).

You mean to use the original 4.0 traineddata rather than best. I will make that change.

**Comment by Shreeshrii** [comment]
```
make engosddata-install
wget  -nc https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata
--2017-09-14 21:17:15--  https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata
Resolving github.com (github.com)... 192.30.255.113, 192.30.255.112
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata [following]
--2017-09-14 21:17:17--  https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.0.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31873501 (30M) [application/octet-stream]
Saving to: ‘eng.traineddata’

100%[===============================================================================================================================>] 3,18,73,501 2.86MB/s   in 11s

2017-09-14 21:17:29 (2.72 MB/s) - ‘eng.traineddata’ saved [31873501/31873501]

wget  -nc https://github.com/tesseract-ocr/tessdata/raw/master/osd.traineddata
--2017-09-14 21:17:29--  https://github.com/tesseract-ocr/tessdata/raw/master/osd.traineddata
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/osd.traineddata [following]
--2017-09-14 21:17:30--  https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/osd.traineddata
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10562727 (10M) [application/octet-stream]
Saving to: ‘osd.traineddata’

100%[===============================================================================================================================>] 1,05,62,727 2.64MB/s   in 5.0s

2017-09-14 21:17:36 (2.03 MB/s) - ‘osd.traineddata’ saved [10562727/10562727]

cp   eng.traineddata osd.traineddata /usr/local/share/tessdata
```

**Comment by Shreeshrii** [comment]
@stweil 

Should this be included as part of the default `make` and `make install` for the project?

If so, tesseract/Makefile.am will also need a change.

**Comment by stweil** [comment]
Getting the `traineddata` files needs an internet connection. A simple `make` should work without internet. But a `make install` should result in a working installation, so for that case it would be good to include your code.

**Comment by jbreiden** [comment]
Debian package building uses 'make install' and network access is forbidden
during that operation.

**Comment by stweil** [comment]
@jbreiden, how do you build the Debian packages with `traineddata` then? Is there a "standard" Makefile target to get files needed for the installation from the internet?

**Comment by stweil** [comment]
Related: would it make sense to add the Debian rules to the Tesseract repository?
Maybe rules for other distributions (e.g. I have files for the Windows installer), too?

**Comment by Shreeshrii** [comment]
https://packages.ubuntu.com/zesty/tesseract-ocr

dependencies include:

tesseract-ocr-eng (>= 3.01~)
tesseract-ocr language files for English
tesseract-ocr-equ
tesseract-ocr language files for equations
tesseract-ocr-osd
tesseract-ocr language files for script and orientation

**Comment by stweil** [comment]
It's similar for Debian: https://packages.debian.org/stretch/tesseract-ocr.

**Comment by amitdo** [comment]
Just quating Ray about best and fast:

>2 parallel sets of tessdata. "best" and "fast". "Fast" will exceed the speed of legacy Tesseract in real time, provided you have the required parallelism components, and in total CPU only slightly slower for English. Way faster for most non-latin languages, while being <5% worse than "best" Only "best" will be retrainable, as "fast" will be integer.

**Comment by stweil** [comment]
Are you referring to my [other comment](https://github.com/tesseract-ocr/tesseract/issues/1131#issuecomment-329764356) about "best" and "fast"?

**Comment by amitdo** [comment]
>Are you referring to my other comment about "best" and "fast"?

Sorry, I chose the wrong tab in the browser to paste the quote :-)

**Comment by jbreiden** [comment]
@stweil We are changing how the official Debian packages work. I'm collaborating with Александр Поздняков who has already done a terrific job making a PPA. Debian Experimental is the work in progress for turning his PPA work into official packages. See links below for details. Any questions?

https://github.com/AlexanderP/dsc-file/tree/master/debian-tesseract-lang
https://github.com/AlexanderP/dsc-file/tree/master/debian-tesseract

"Related: would it make sense to add the Debian rules to the Tesseract repository?" Maybe, maybe not, but there is enough going on right now that I don't want to even think about it. Priority is to get 4.x packages working and shipping to users.

**Comment by Shreeshrii** [comment]
Jeff, 
Thanks for the info regarding packaging. Great to know that 4.x will be shipping soon.

Please see https://github.com/tesseract-ocr/tesseract/issues/1133 and 1132 - regarding the osd.traineddata files.

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/1131
regarding TESSDATA_PREFIX and tessdata-dir

What will be the tessdata file structure under debian?
Will users be able to install both tesseract 3 and tesseract 4?

**Comment by jbreiden** [comment]
>What will be the tessdata file structure under debian?
Current /usr/share/tesseract-ocr/tessdata
Upcoming: /usr/share/tesseract-ocr/4.00/tessdata/

>Will users be able to install both tesseract 3 and tesseract 4?
Normal users will install Tesseract packages via apt-get. The only  option will be Tesseract 4.x and the fast LSTM traineddata. The current Tesseract 3.x packages will be replaced.

Advanced users can of course continue doing anything they want; building from source, choosing one of the alternate traineddata files from github, attempting to install multiple Tesseracts at the same time, etc.

**Comment by Shreeshrii** [comment]
Thanks for the info, Jeff.

I assume that training tools will be included in the debian package. If so, please see https://github.com/tesseract-ocr/tesseract/issues/1114.

Also note, https://github.com/tesseract-ocr/tessdata_fast/pull/3 regarding sanskrit traineddata.

You can check with Ray, whether the recommended action is just removing the config file vs. changing the default oem mode in it (since the other config variables probably only apply to legacy engine).

**Comment by Shreeshrii** [comment]
@zdenop Should the datadir in github project be made in sync with the structure for debian?

>What will be the tessdata file structure under debian?
Current: /usr/share/tesseract-ocr/tessdata
Upcoming: /usr/share/tesseract-ocr/4.00/tessdata/

**Comment by jbreiden** [comment]
Packages have been submitted to Debian Experimental and are awaiting manual approval. These packages are effectively identical to Alexander's Personal Package Archive (PPA) `tesseract` and `tesseract-lang`.

DEBIAN
https://packages.debian.org/source/experimental/tesseract
https://ftp-master.debian.org/new/tesseract-lang_4.00~git15-45ed289-1.html

PPA
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by stweil** [comment]
>  Upcoming: /usr/share/tesseract-ocr/4.00/tessdata/

@jbreiden, I still hope that we'll get semantic versioning for Tesseract. Therefore I suggest to use a different name `/usr/share/tesseract-ocr/4/tessdata/`, `/usr/share/tesseract-ocr/4.0/tessdata/` or even `/usr/share/tesseract4/tessdata/` (do you need the "-ocr" in the package names?).

**Comment by jbreiden** [comment]
@stweil We've been using tesseract-ocr as the package name for a very long time, and there is a pretty big installed base. I don't know how big the upgrade headache would be if we changed names. There is some time to consider this, as we wait for manual approval. I'm somewhat wary since I have managed to screw up every single Tesseract transition in Debian so far. Then again, it is probably now or never.

https://qa.debian.org/popcon.php?package=tesseract

The choice of `/usr/share/tesseract-ocr/4.00/tessdata/` was from Alexander and I suspect it is fairly arbitrary. I suspect we could do `/usr/share/tesseract-ocr/4/tessdata/` or `/usr/share/tesseract-ocr/4.0/tessdata/`. The only reason not to continue with  `/usr/share/tesseract-ocr/tessdata/` is as a courtesy to advanced users who wish to install Tessseract 3x on the same system. Anyway, maybe try installing his PPA, see if you have any comments, and we can discuss with Alexander. Again there is some time as we wait for approval in NEW queue.

https://www.debian.org/doc/debian-policy/index.html#shared-library-support-files

**Comment by Shreeshrii** [comment]
@jbreiden Jeff, Will you update the langdata repo with files with 4.0x too? Thanks!

**Comment by Shreeshrii** [comment]
Jeff, I just looked at https://packages.debian.org/sid/arm64/tesseract-ocr/filelist

It seems to have training tools for the legacy engine but not for LSTM. Is that intentional???

**Comment by jbreiden** [comment]
No, total accident. Need to fix that. Thank you for noticing.

**Comment by jbreiden** [comment]
What do people think? Should we that packages ship both legacy and LSTM training tools, or just LSTM? I figure only experts will use training tools, so I am less worried about confusion.

**Comment by Shreeshrii** [comment]
Also, two architectures are still at 3.04


Architecture | Version | Package Size | Installed Size | Files
-- | -- | -- | -- | --
i386	| 4.00~git2188-cdc35338-4	| 234.3 kB	|1,008.0 kB	|[list of files]
kfreebsd-amd64	|3.04.01-6	|139.0 kB	|562.0 kB	|[list of files]
kfreebsd-i386	|3.04.01-6	|147.7 kB	|546.0 kB	|[list of files]
m68k (unofficial port)	|4.00~git2188-cdc35338-4	|215.2 kB	|948.0 kB	|[list of files]

**Comment by Shreeshrii** [comment]
>Should we that packages ship both legacy and LSTM training tools, or just LSTM? I figure only experts will use training tools, so I am less worried about confusion.

Yes, both should be included, at least for this version. `tesstrain.sh` etc all support both types of training.

**Comment by jbreiden** [comment]
> https://packages.debian.org/sid/arm64/tesseract-ocr/filelist

I just checked and the web page is inaccurate.  No idea why. The package actually contains LSTM training tools; here is the list of shipping binaries.

```
/usr/bin/ambiguous_words
/usr/bin/classifier_tester
/usr/bin/cntraining
/usr/bin/combine_lang_model
/usr/bin/combine_tessdata
/usr/bin/dawg2wordlist
/usr/bin/lstmeval
/usr/bin/lstmtraining
/usr/bin/merge_unicharsets
/usr/bin/mftraining
/usr/bin/set_unicharset_properties
/usr/bin/shapeclustering
/usr/bin/tesseract
/usr/bin/text2image
/usr/bin/unicharset_extractor
/usr/bin/wordlist2dawg
```

Regarding kfreebsd-amd64, kfreebsd-i386, m68k, these can be ignored. They are extremely rare architectures, with very few users. Debian supports them on a best effort basis, but it is quite common for them to fall behind. Catching them up (if that happens at all) is Somebody Else's Problem.

**Comment by Shreeshrii** [comment]
Thanks for checking, Jeff.

Good that the files are included in the package. The filelist on their webpage is different for different architectures, some of them list the lstm training tools  others don't.

**Comment by Shreeshrii** [comment]
I would suggest that you add information regarding appropriate traineddata to be used for training in README somewhere, even though only 'experts' will use that option...

For **legacy tesseract training**, base traineddata should be used from **tessdata** repo, since that is the only one that will support --oem 0.

For **LSTM training**, base traineddata should be from **tessdata_best** repo.

**Pull request closed without merging**
