### PR TITLE
Change message display for debug_level -1 during lstmtraining

### PR DESCRIPTION
**Pull request by Shreeshrii**
```
Iteration 3282: ALIGNED TRUTH : including just place 18 service Articles as could these Community to link them Forum most 0
Iteration 3282: GROUND  TRUTH : including just place 18 service Articles as could these Community to link them Forum most 0
Iteration 3282: BEST OCR TEXT : including just place 18 service Articles as could these Community to 1ink them Forum most 0
File /tmp/eng-2019-03-30.Lcy/eng.Cousine.exp0.lstmf page 41 :
Mean rms=0.346%, delta=0.157%, train=0.512%(1.009%), skip ratio=0%
Iteration 3283: ALIGNED TRUTH : first 27 then 2.100 they FIG. 1 (GeneRIF) World and ABOUT time October the service through
File ./engrestrict/eng.Cutive_Mono.exp0.lstmf page 54 (Perfect):
Mean rms=0.346%, delta=0.157%, train=0.512%(1.009%), skip ratio=0%
Iteration 3284: ALIGNED TRUTH : for , Page CD AbstractPlus most Page , over Other reference 40 should a Posts my the search
File ./engrestrict/eng.DejaVu_Sans_Mono.exp0.lstmf page 54 (Perfect):
Mean rms=0.346%, delta=0.157%, train=0.512%(1.009%), skip ratio=0%
Iteration 3285: ALIGNED TRUTH : Music am search this Please time each How at Online (7) get quality Advanced can may such a
File /tmp/eng-2019-03-30.Lcy/eng.Fira_Mono.exp0.lstmf page 16 (Perfect):
```

### CODE REVIEW

**Comment by Shreeshrii** [comment]
@amitdo Is this OK?

**Comment by amitdo** [comment]
>Iteration 3282: GROUND  TRUTH : including just place 18 service Articles as could these Community to link them Forum most 0
Iteration 3282: BEST OCR TEXT : including just place 18 service Articles as could these Community to 1ink them Forum most 0

They are identical. no?

**Comment by Shreeshrii** [comment]
> link - lower case L
> 1ink - number 1

**Comment by Shreeshrii** [comment]
OCR TEXT and GROUND TRUTH are displayed only when different.

https://github.com/tesseract-ocr/tesseract/blob/0b980a75fd3d5021b8cbac1a98bb81c3d564eddc/src/lstm/lstmtrainer.cpp#L880-L887

ALIGNED TRUTH is displayed in all cases.

https://github.com/tesseract-ocr/tesseract/blob/0b980a75fd3d5021b8cbac1a98bb81c3d564eddc/src/lstm/lstmtrainer.cpp#L1049-L1050

**Comment by amitdo** [comment]
Shree, I prefer this behavior:
*Always display ground truth.
* Display align truth only if not the same as ground truth.
  * Otherwise, print "ALIGNED TRUTH is same as GROUND TRUTH"
* Display best ocr only if not the same as ground truth.
  * Otherwise, print "BEST OCR TEXT is same as GROUND TRUTH"

What do you think?

**Comment by Shreeshrii** [comment]
> Always display ground truth.
> Display align truth only if not the same as ground truth.
> Display best ocr only if not the same as ground truth.

Sounds good.

>Otherwise, print "ALIGNED TRUTH is same as GROUND TRUTH"
>Otherwise, print "BEST OCR TEXT is same as GROUND TRUTH"

This will clutter an already busy output. A description/example can be added to wiki page to explain this with samples.

```
Iteration 97: GROUND  TRUTH : 𒌉𒁀𒉌𒄿 𒄿𒋼𒇻𒌑 𒄬𒆷 𒌷𒄯𒁁𒁹𒆗𒁉 𒆠𒊹𒊏
Iteration 97: BEST OCR TEXT :  
File /home/ubuntu/tmp/akk/akk.CuneiformOB.exp0.lstmf page 131 :
Mean rms=1.959%, delta=48.181%, train=154.364%(100%), skip ratio=4.082%
Iteration 98: GROUND  TRUTH : 𒌌𒆷𒉡𒌋𒀀 𒁹𒀭𒌍𒌋𒌋𒉽 𒋫𒁖𒆠𒋙 𒀀𒃼𒈨𒌍𒋙𒌦
Iteration 98: BEST OCR TEXT :  
File /home/ubuntu/tmp/akk/akk.CuneiformOB.exp-2.lstmf page 1001 :
Mean rms=1.958%, delta=48.109%, train=153.773%(100%), skip ratio=4.04%
Iteration 99: GROUND  TRUTH : 𒀾𒋳𒅗𒈾 𒄵𒆠𒅀 𒉺𒅁𒁍𒊒 𒇺𒃻𒀀 𒉿𒋼𒂊
Iteration 99: ALIGNED TRUTH : 𒀾𒋳𒅗𒈾 𒄵𒆠𒅀 𒉺𒅁𒁍𒊒 𒇺𒃻𒀀  𒉿𒋼𒂊
Iteration 99: BEST OCR TEXT :  
File /home/ubuntu/tmp/akk/akk.Segoe_UI_Historic.exp-1.lstmf page 2168 :
Mean rms=1.957%, delta=48.005%, train=153.187%(100%), skip ratio=4%
At iteration 100/100/104, Mean rms=1.957%, delta=48.005%, char train=153.187%, word train=100%, skip ratio=4%,  New worst char error = 153.187 wrote checkpoint.
```

```
Iteration 2563: GROUND  TRUTH : on however, NJ rights an full check CBS Community 4 IV a It s -- 1 Amazon - 49 TV.com Blog
File /tmp/eng-2019-03-30.Lcy/eng.Lucida_Console_Semi-Condensed.exp0.lstmf page 40 (Perfect):
Mean rms=0.382%, delta=0.168%, train=0.531%(1.023%), skip ratio=0%
Iteration 2564: GROUND  TRUTH : back - SEARCH Click there to an may from Search , that NBA LCD ... TechRepublic up THE
File /tmp/eng-2019-03-30.Lcy/eng.Lucida_Sans_Typewriter_Semi-Condensed.exp0.lstmf page 16 (Perfect):
Mean rms=0.381%, delta=0.168%, train=0.529%(1.017%), skip ratio=0%
Iteration 2565: GROUND  TRUTH : with Send about 3G Video also 10 -- from about 2007, data March 5 also a Send From
File ./engrestrict/eng.Merchant_Copy_Doublesize.exp0.lstmf page 21 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.525%(1.007%), skip ratio=0%
Iteration 2566: GROUND  TRUTH : Music am search this Please time each How at Online (7) get quality Advanced can may such a
Iteration 2566: BEST OCR TEXT : Music am search this Please time each How at OUnline (7) get quality Advanced can may such a
File /tmp/eng-2019-03-30.Lcy/eng.Merchant_Copy.exp0.lstmf page 26 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
Iteration 2567: GROUND  TRUTH : 2008. and No Posted any AM be including Profile back Books United in post Popular here
File ./engrestrict/eng.Miriam_Mono_CLM.exp0.lstmf page 26 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
Iteration 2568: GROUND  TRUTH : Community 17 In Views look very with after click because I C. would July for is provided
File /tmp/eng-2019-03-30.Lcy/eng.Noto_Mono.exp0.lstmf page 26 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
Iteration 2569: GROUND  TRUTH : York on being have HTML OR because Privacy lm View a TMZ dbGaP 25, 1, more all add US all
File ./engrestrict/eng.PT_Mono.exp0.lstmf page 26 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
Iteration 2570: GROUND  TRUTH : the Policy Up Get by A. al., Us 50 other Links Contact Terms and first article XML in NFL
File /tmp/eng-2019-03-30.Lcy/eng.QuickType_II_Mono.exp0.lstmf page 5 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
```

**Comment by Shreeshrii** [comment]
However, the originally reported problem still remains:

```
Iteration 2566: GROUND  TRUTH : Music am search this Please time each How at Online (7) get quality Advanced can may such a
Iteration 2566: BEST OCR TEXT : Music am search this Please time each How at OUnline (7) get quality Advanced can may such a
File /tmp/eng-2019-03-30.Lcy/eng.Merchant_Copy.exp0.lstmf page 26 (Perfect):
Mean rms=0.381%, delta=0.167%, train=0.527%(1.013%), skip ratio=0%
```
The line is being marked as perfect even though OCR TEXT and GROUND TRUTH differ.

**Comment by amitdo** [comment]
OK, feel free to implement it :-)

**Comment by amitdo** [comment]
LGTM

**Comment by Shreeshrii** [comment]
```
Iteration 36502: ALIGNED TRUTH : 〔一〕慧耦耧瑾璜璀璎璁璋璇璆奭撵髯髫撷撕撒撅撩趣趟撑撮撬赭播墦擒撸
Iteration 36502: BEST OCR TEXT : 〔一〕壮甭杰开开开璆下璋正璆襄措绥缕扯拓帛括擦起趟掸捉握未挢堵拴措
File /tmp/chi_sim-2019-03-28.INN/chi_sim.Arial_Unicode_MS.exp0.lstmf page 39 :
Mean rms=1.855%, delta=11.133%, train=33.184%(49.419%), skip ratio=17.4%
Iteration 36503: ALIGNED TRUTH : 感兴趣
Iteration 36503: BEST OCR TEXT : 戌六赴
File /tmp/chi_sim-2019-03-28.INN/chi_sim.Noto_Sans_CJK_SC.exp0.lstmf page 79 :
```

Change `page` to `line` in above message.

**Comment by amitdo** [comment]
where is the gt in your latest example?

**Comment by Shreeshrii** [comment]
Had copied from an old log file. Have posted current output now. Edited the earlier message.

**Comment by Shreeshrii** [comment]
New output after change is the following:

```
Mean rms=0.532%, delta=0.302%, train=1.815%(5.85%), skip ratio=0%
Iteration 1213: GROUND  TRUTH : 0.23 2 -6X151 909 2 251.8kg 1.53 Q345L90X8 M16X180 L50X4 1214 65.22 0.40
File /tmp/chi_sim-2019-04-04.9ib/chi_sim.NSimSun.exp0.lstmf line 23 (Perfect):
Mean rms=0.532%, delta=0.302%, train=1.812%(5.842%), skip ratio=0%
Iteration 1214: GROUND  TRUTH : Φ 1 8568 Q345L63X5 1.65 531 312 用于塔脚板式 14.55 437 244 40.81 60 Φ 727 2 2.9
Iteration 1214: BEST OCR TEXT : ) 1 8568 Q345L63X5 1.65 531 312 用于塔脚板式 14.55 437 244 40.81 60 Φ 727 2 2.9
File /tmp/chi_sim-2019-04-04.9ib/chi_sim.SimSun.exp0.lstmf line 202 :
Mean rms=0.532%, delta=0.302%, train=1.812%(5.842%), skip ratio=0%
Iteration 1215: GROUND  TRUTH : -3X60 开角处理 10.6 812 2524 2 182.9 207 2516 Q420L160X1Φ 994 4 8.32 512
File /home/ubuntu/tesstutorial/chi_sim_train/chi_sim.Arial_Unicode_MS.exp0.lstmf line 243 :
Mean rms=0.532%, delta=0.302%, train=1.811%(5.835%), skip ratio=0%
Iteration 1216: GROUND  TRUTH : M20X65 2301 合计 671.9kg 1.26 中部压扁 203.80 1 Q235 备注 1 154Φ 1409 4 8.34 1
File /tmp/chi_sim-2019-04-04.9ib/chi_sim.Noto_Sans_CJK_SC.exp0.lstmf line 530 (Perfect):
Mean rms=0.531%, delta=0.302%, train=1.809%(5.817%), skip ratio=0%
```

File /tmp/chi_sim-2019-04-04.9ib/chi_sim.Noto_Sans_CJK_SC.exp0.lstmf **line** 530 (Perfect):

**Comment by zdenop** [comment]
@Shreeshrii: is this PR finalized from your perspective?

**Comment by Shreeshrii** [comment]
Yes. You can merge. Thank you!

**Pull request merged**
