### PR TITLE
Added osd renderer for psm 0.

### PR DESCRIPTION
**Pull request by amitdo**
Works for single page and multi-page.

### CODE REVIEW

**Comment by amitdo** [comment]
test:
```
convert -rotate 270 eurotext.tif eurotext270.tif

tesseract eurotext.tif eurotext -l osd -psm 0

tesseract eurotext270.tif eurotext270 -l osd -psm 0

cat eurotext270.tif | tesseract stdin stdout -l osd -psm 0
```

**Comment by zdenop** [comment]
thanks

**Comment by amitdo** [comment]
:+1:

**Comment by amitdo** [comment]
Fixed #85.

**Pull request merged**
