### PR TITLE
Appveyor CI (experimental, don't pull)

### PR DESCRIPTION
**Pull request by stweil**
This is a test with caching.

### CODE REVIEW

**Comment by stweil** [comment]
The [Appveyor cache](https://www.appveyor.com/docs/build-cache/) does not seem to work currently. According to the [documentation](https://www.appveyor.com/blog/2016/09/28/the-new-build-cache/), it is only enabled for new user accounts by default. @zdenop, you have to apply to get it enabled for your account.

**Comment by zdenop** [comment]
applied.

Zdenko

**Comment by egorpugin** [comment]
So, can we merge this?

**Comment by egorpugin** [comment]
Ok, cache is up'n'running, so build time for windows is only 4 minutes now.
https://ci.appveyor.com/project/zdenop/tesseract/build/master.843

**Comment by stweil** [comment]
Wow!

**Comment by egorpugin** [comment]
Yes. :) Thanks, Stefan!
I'm activating training tools for building too.

**Comment by stweil** [comment]
By the way: I think 0 warnings is not normal. Are they suppressed by compiler options? Then I suggest to raise to the next warning level.

**Comment by egorpugin** [comment]
Ok, done.

**Comment by egorpugin** [comment]
Also this means that we have full set of training tools in artifacts section of every build.
https://appveyorcidata.blob.core.windows.net/zdenop-27740/tesseract/master-844/m23d78nft28axsd6/build/bin/tesseract-master.844.zip
So people could download binaries from there.

**Comment by Shreeshrii** [comment]
This is great. Is there a generic link to artifacts section that can be
added to the wiki?

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by zdenop** [comment]
FYI: According reply from Appveyor: 

> Build cache is already enabled for all AppVeyor accounts.
> The issue is that it won’t be saved during PR build.

**Comment by egorpugin** [comment]
Saved, but not loaded.
We care only about loading cache.

**Comment by Shreeshrii** [comment]
Hi Egor,

I downloaded the zip file for tesseract-master.848.zip

It has some of the training tools, but not text2image .

$ ls -l
total 40036
-rwxr-xr-x 1 vvkum 197611    14336 May  7 20:14 ambiguous_words.exe*
-rwxr-xr-x 1 vvkum 197611    33792 May  7 20:14 classifier_tester.exe*
-rwxr-xr-x 1 vvkum 197611    28160 May  7 20:14 cntraining.exe*
-rwxr-xr-x 1 vvkum 197611    13824 May  7 20:14 combine_tessdata.exe*
-rwxr-xr-x 1 vvkum 197611    14336 May  7 20:14 dawg2wordlist.exe*
-rwxr-xr-x 1 vvkum 197611    31744 May  7 20:14 lstmeval.exe*
-rwxr-xr-x 1 vvkum 197611    50688 May  7 20:14 lstmtraining.exe*
-rwxr-xr-x 1 vvkum 197611    45056 May  7 20:14 mftraining.exe*
-rwxr-xr-x 1 vvkum 197611   406016 May  7 20:14
pvt.cppan.demo.behdad.harfbuzz-1.4.5.dll*
-rwxr-xr-x 1 vvkum 197611    58880 May  7 20:14
pvt.cppan.demo.bzip2-1.0.6.dll*
-rwxr-xr-x 1 vvkum 197611  1098240 May  7 20:14
pvt.cppan.demo.cairographics.cairo-1.15.4.dll*
-rwxr-xr-x 1 vvkum 197611  1929728 May  7 20:14
pvt.cppan.demo.danbloomberg.leptonica-1.74.1.dll*
-rwxr-xr-x 1 vvkum 197611   114176 May  7 20:14
pvt.cppan.demo.expat-2.2.0.dll*
-rwxr-xr-x 1 vvkum 197611   221184 May  7 20:14
pvt.cppan.demo.freedesktop.fontconfig.fontconfig-2.12.1.dll*
-rwxr-xr-x 1 vvkum 197611   489984 May  7 20:14
pvt.cppan.demo.freetype-2.7.1.dll*
-rwxr-xr-x 1 vvkum 197611   929792 May  7 20:14
pvt.cppan.demo.gnome.glib.glib-2.50.3.dll*
-rwxr-xr-x 1 vvkum 197611   214528 May  7 20:14
pvt.cppan.demo.gnome.glib.gobject-2.50.3.dll*
-rwxr-xr-x 1 vvkum 197611   236544 May  7 20:14
pvt.cppan.demo.gnome.pango.pango-1.40.3.dll*
-rwxr-xr-x 1 vvkum 197611    83968 May  7 20:14
pvt.cppan.demo.gnome.pango.pangocairo-1.40.3.dll*
-rwxr-xr-x 1 vvkum 197611    64000 May  7 20:14
pvt.cppan.demo.gnome.pango.pangoft2-1.40.3.dll*
-rwxr-xr-x 1 vvkum 197611    51200 May  7 20:14
pvt.cppan.demo.gnu.gettext.intl-0.19.8.dll*
-rwxr-xr-x 1 vvkum 197611     9728 May  7 20:14
pvt.cppan.demo.gnu.iconv.libcharset-1.15.0.dll*
-rwxr-xr-x 1 vvkum 197611   919040 May  7 20:14
pvt.cppan.demo.gnu.iconv.libiconv-1.15.0.dll*
-rwxr-xr-x 1 vvkum 197611   251904 May  7 20:14
pvt.cppan.demo.jpeg-9.2.0.dll*
-rwxr-xr-x 1 vvkum 197611    73728 May  7 20:14
pvt.cppan.demo.madler.zlib-1.2.11.dll*
-rwxr-xr-x 1 vvkum 197611   159744 May  7 20:14
pvt.cppan.demo.openjpeg.openjp2-2.1.2.dll*
-rwxr-xr-x 1 vvkum 197611   234496 May  7 20:14
pvt.cppan.demo.pcre.pcre-8.39.0.dll*
-rwxr-xr-x 1 vvkum 197611   157696 May  7 20:14
pvt.cppan.demo.png-1.6.28.dll*
-rwxr-xr-x 1 vvkum 197611   332800 May  7 20:14
pvt.cppan.demo.tiff-4.0.7.dll*
-rwxr-xr-x 1 vvkum 197611  1254400 May  7 20:14
pvt.cppan.demo.unicode.icu.common-59.1.0.dll*
-rwxr-xr-x 1 vvkum 197611 26293760 May  7 20:14
pvt.cppan.demo.unicode.icu.data-59.1.0.dll*
-rwxr-xr-x 1 vvkum 197611  1790464 May  7 20:14
pvt.cppan.demo.unicode.icu.i18n-59.1.0.dll*
-rwxr-xr-x 1 vvkum 197611   428032 May  7 20:14
pvt.cppan.demo.webp-0.6.0.dll*
-rwxr-xr-x 1 vvkum 197611    24064 May  7 20:14
pvt.cppan.demo.weltling.winlibs.libffi-3.2.1.dll*
-rwxr-xr-x 1 vvkum 197611   130048 May  7 20:14
pvt.cppan.demo.xz_utils.lzma-5.2.2.dll*
-rwxr-xr-x 1 vvkum 197611    37376 May  7 20:14
set_unicharset_properties.exe*
-rwxr-xr-x 1 vvkum 197611    30720 May  7 20:14 shapeclustering.exe*
-rwxr-xr-x 1 vvkum 197611    29184 May  7 20:14 tesseract.exe*
-rwxr-xr-x 1 vvkum 197611  2598400 May  7 20:14 tesseract400.dll*
-rwxr-xr-x 1 vvkum 197611    11264 May  7 20:14 unicharset_extractor.exe*
-rwxr-xr-x 1 vvkum 197611    18432 May  7 20:14 wordlist2dawg.exe*





ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by egorpugin** [comment]
True. I'll fix.

**Comment by stweil** [comment]
`text2image` is obviously not built, maybe because `pkg-config` is missing.

**Comment by egorpugin** [comment]
Ok, fixed. Thanks, @Shreeshrii!
Also backported to 3.05 branch.

**Comment by Shreeshrii** [comment]
I tried just now to use `git bash' (https://git-for-windows.github.io/) under windows with tesstrain.sh script for training. Works after putting the exe and dll files in the bin directory. 

This makes it possible for those using windows to try LSTM training using tesstrain.sh.

Thank you all for your work in making it possible.

**Comment by Shreeshrii** [comment]
@egorpugin https://ci.appveyor.com/project/zdenop/tesseract/build/3.05.851 failed.

**Comment by egorpugin** [comment]
Fixed.

**Comment by Shreeshrii** [comment]
Please also check if some setting needs to be changed so that 'info'
messages from leptonica are not displayed. The version built with automake
does not have these.

eg.

File
C:/Users/vvkum/AppData/Local/Temp/tmp.Q59kWa5fdq/hin/hin.FreeSerif.exp0.lstmf
page 218 :
Mean rms=5.246%, delta=46.464%, train=104.341%(100%), skip ratio=0%
Info in fopenReadFromMemory: work-around: writing to a temp file
Iteration 188: ALIGNED TRUTH : गई हैं. एशिया डैनियल श्रिया था. हैं.
Iteration 188: BEST OCR TEXT :
File
C:/Users/vvkum/AppData/Local/Temp/tmp.Q59kWa5fdq/hin/hin.FreeSerif.exp0.lstmf
page 94 :
Mean rms=5.245%, delta=46.466%, train=104.318%(100%), skip ratio=0%
Info in fopenReadFromMemory: work-around: writing to a temp file
Iteration 189: ALIGNED TRUTH : फ्लेमिंग लिया। बर्बाद स्पोर्ट्स %>
Iteration 189: BEST OCR TEXT :
File
C:/Users/vvkum/AppData/Local/Temp/tmp.Q59kWa5fdq/hin/hin.FreeSerif.exp0.lstmf
page 208 :
Mean rms=5.243%, delta=46.436%, train=104.295%(100%), skip ratio=0%
Info in fopenReadFromMemory: work-around: writing to a temp file
Iteration 190: ALIGNED TRUTH : हैप्पी सुर्ख घर मिलता हुई। के
Iteration 190: BEST OCR TEXT :

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/pull/543

related to info messages from leptonica

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by egorpugin** [comment]
#543 is present in master and 3.05.

**Pull request merged**
