### PR TITLE
Fix unbound variable $FONTS

### LINKED ISSUE #2054: Training tesseract tesstrain.sh exits with a warning
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain

throws warning : 
mktemp: option requires an argument -- t
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 

------------------------

### Environment

* **Tesseract Version**:  4.0.0
* **Commit Number**: NA
* **Platform**: Mac OS

### PR DESCRIPTION
**Pull request by johnlinp**
Fixes #2054

### CODE REVIEW

**Comment by johnlinp** [comment]
Sure. Should I close this pull request now?

**Comment by stweil** [comment]
@rakesh-km, @johnlinp, could you please try pull request #2057? If it works for you, we can merge it and close the pull request here.

**Comment by johnlinp** [comment]
@stweil No, it doesn't work. The error messages are:

```
$ ./src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only --noextract_font_properties --langdata_dir ../langdata --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain
./src/training/tesstrain_utils.sh: line 196: test: -v: unary operator expected
./src/training/tesstrain_utils.sh: line 199: test: -v: unary operator expected
./src/training/tesstrain_utils.sh: line 50: test: -v: unary operator expected

=== Starting training for language 'eng'
./src/training/language-specific.sh: line 1171: test: -v: unary operator expected
./src/training/language-specific.sh: line 1175: test: -v: unary operator expected
./src/training/language-specific.sh: line 1178: test: -v: unary operator expected
./src/training/tesstrain_utils.sh: line 234: FONTS[0]: unbound variable
```

It seems that `test` on macOS does not support `-v` option.

**Comment by stweil** [comment]
Thank you for testing. macOS uses an old bash without support for `test -v`. I now merged your pull request and will have to find a different solution for the other issues.

**Pull request merged**
