### PR TITLE
Update osdetect.cpp

### PR DESCRIPTION
**Pull request by ShahrukhSatti21**
//Keeping 
const int kMinCharactersToTry = 5
//Since working with text extraction from vehicle number plates needs less minimum number of characters. kMaxCharactersToTry may be //modified accordingly.

### CODE REVIEW

**Comment by amitdo** [comment]
The algorithm is designed to work with the current minimum value. Changing that const value might break it. I suggest not to accept this PR without Ray's approval.

**Comment by amitdo** [comment]
Another thing, Ray said he has a better OSD module (LSTM-based) that will replace the current one.

**Comment by amitdo** [comment]
@theraysmith, I think this PR should be rejected, right?

**Comment by theraysmith** [comment]
So far the new script id looks good.
I don't understand why you would ever want to run OSD on license plates? It makes no sense.

**Comment by ShahrukhSatti21** [comment]
Hi,
I was a beginner and too immature to ask such a basic question that too as
an issue. Later, I dug deeper into tesseract and a ROI finding algorithm
and compiled an executable to extract characters on number plates. There's
no need to consider this PR as the algo might not stay as generic as now.
Thanks for considering anyway.

**Pull request closed without merging**
